-- Generated by `cargo xtask facts generate` from plugins/builtin_v2/macros/stubs/keyword_abilities/*.ron and xtask's gate-column overlay; edit those, never this file.
module Experimental.FactsGen

import public Experimental.KeywordShapes

%default total

public export
keywordFacts : List KeywordFacts
keywordFacts =
  [ { word := "Haste", paramShapes := [NoParam], counterEligible := True } defaultKeywordFacts
  , { word := "Flying", paramShapes := [NoParam], counterEligible := True } defaultKeywordFacts
  , { word := "Trample", paramShapes := [NoParam], counterEligible := True } defaultKeywordFacts
  , { word := "Vigilance", paramShapes := [NoParam], counterEligible := True } defaultKeywordFacts
  , { word := "Deathtouch", paramShapes := [NoParam], counterEligible := True, regime := Just AtResolution } defaultKeywordFacts
  , { word := "DoubleStrike", paramShapes := [NoParam], counterEligible := True } defaultKeywordFacts
  , { word := "FirstStrike", paramShapes := [NoParam], counterEligible := True } defaultKeywordFacts
  , { word := "Reach", paramShapes := [NoParam], counterEligible := True } defaultKeywordFacts
  , { word := "Defender", paramShapes := [NoParam] } defaultKeywordFacts
  , { word := "Convoke", paramShapes := [NoParam], regime := Just AtCasting, onSpellCard := True } defaultKeywordFacts
  , { word := "Improvise", paramShapes := [NoParam], regime := Just AtCasting, onSpellCard := True } defaultKeywordFacts
  , { word := "Storm", paramShapes := [NoParam], regime := Just AtCasting, onSpellCard := True, bodied := True } defaultKeywordFacts
  , { word := "Lifelink", paramShapes := [NoParam], counterEligible := True, regime := Just AtResolution } defaultKeywordFacts
  , { word := "Ward", paramShapes := [CostParam], paidCost := True, bodied := True } defaultKeywordFacts
  , { word := "Protection", paramShapes := [QualityParam] } defaultKeywordFacts
  , { word := "Enchant", paramShapes := [SubjectParam] } defaultKeywordFacts
  , { word := "Equip", paramShapes := [CostParam, CompoundParam QualityHead], paidCost := True } defaultKeywordFacts
  , { word := "Suspend", paramShapes := [CompoundParam NumberHead], onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Ascend", paramShapes := [NoParam], onSpellCard := True } defaultKeywordFacts
  , { word := "Storied", paramShapes := [NoParam] } defaultKeywordFacts
  , { word := "Renown", paramShapes := [NumberParam], bodied := True } defaultKeywordFacts
  , { word := "Indestructible", paramShapes := [NoParam], counterEligible := True } defaultKeywordFacts
  , { word := "Flash", paramShapes := [NoParam], regime := Just AtCasting, onSpellCard := True } defaultKeywordFacts
  , { word := "Kicker", paramShapes := [CostParam], regime := Just AtCasting, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Multikicker", paramShapes := [CostParam], regime := Just AtCasting, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "CumulativeUpkeep", paramShapes := [CostParam], paidCost := True, bodied := True } defaultKeywordFacts
  , { word := "Echo", paramShapes := [CostParam], paidCost := True, bodied := True } defaultKeywordFacts
  , { word := "Hexproof", paramShapes := [NoParam, QualityParam], counterEligible := True } defaultKeywordFacts
  , { word := "Menace", paramShapes := [NoParam], counterEligible := True } defaultKeywordFacts
  , { word := "Skulk", paramShapes := [NoParam] } defaultKeywordFacts
  , { word := "Bushido", paramShapes := [NumberParam], bodied := True } defaultKeywordFacts
  , { word := "Unearth", paramShapes := [CostParam], paidCost := True } defaultKeywordFacts
  , { word := "Flashback", paramShapes := [CostParam], onPermanentCard := False, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Dredge", paramShapes := [NumberParam], onSpellCard := True } defaultKeywordFacts
  , { word := "Retrace", paramShapes := [NoParam], onSpellCard := True } defaultKeywordFacts
  , { word := "Cycling", paramShapes := [CostParam, CompoundParam QualityHead], onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Ninjutsu", paramShapes := [CostParam], paidCost := True } defaultKeywordFacts
  , { word := "Miracle", paramShapes := [CostParam], onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Warp", paramShapes := [CostParam], regime := Just AtCasting, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Afterlife", paramShapes := [NumberParam], bodied := True } defaultKeywordFacts
  , { word := "Boast", paramShapes := [AbilityParam] } defaultKeywordFacts
  , { word := "Exhaust", paramShapes := [AbilityParam] } defaultKeywordFacts
  , { word := "PowerUp", paramShapes := [AbilityParam] } defaultKeywordFacts
  , { word := "Affinity", paramShapes := [QualityParam], regime := Just AtCasting, onSpellCard := True } defaultKeywordFacts
  , { word := "Annihilator", paramShapes := [NumberParam], bodied := True } defaultKeywordFacts
  , { word := "Fear", paramShapes := [NoParam] } defaultKeywordFacts
  , { word := "Shroud", paramShapes := [NoParam] } defaultKeywordFacts
  , { word := "Banding", paramShapes := [NoParam] } defaultKeywordFacts
  , { word := "BandsWithOther", paramShapes := [QualityParam] } defaultKeywordFacts
  , { word := "Landwalk", paramShapes := [QualityParam] } defaultKeywordFacts
  , { word := "Changeling", paramShapes := [NoParam], onSpellCard := True } defaultKeywordFacts
  , { word := "Crew", paramShapes := [NumberParam] } defaultKeywordFacts
  , { word := "Saddle", paramShapes := [NumberParam] } defaultKeywordFacts
  , { word := "PartnerWith", paramShapes := [QualityParam] } defaultKeywordFacts
  , { word := "Emerge", paramShapes := [CostParam], regime := Just AtCasting, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Craft", paramShapes := [CostParam], paidCost := True } defaultKeywordFacts
  , { word := "Madness", paramShapes := [CostParam], onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Prowl", paramShapes := [CostParam], regime := Just AtCasting, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Surge", paramShapes := [CostParam], regime := Just AtCasting, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Spectacle", paramShapes := [CostParam], regime := Just AtCasting, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Freerunning", paramShapes := [CostParam], regime := Just AtCasting, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Sneak", paramShapes := [CostParam], regime := Just AtCasting, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Mayhem", paramShapes := [CostParam], onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Disturb", paramShapes := [CostParam], onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Morph", paramShapes := [CostParam], onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Entwine", paramShapes := [CostParam], regime := Just AtCasting, onSpellCard := True, paidCost := True, wantsModes := True } defaultKeywordFacts
  , { word := "Escalate", paramShapes := [CostParam], regime := Just AtCasting, onSpellCard := True, paidCost := True, wantsModes := True } defaultKeywordFacts
  , { word := "Fuse", paramShapes := [NoParam], regime := Just AtCasting, onPermanentCard := False, onSpellCard := True } defaultKeywordFacts
  , { word := "Escape", paramShapes := [CostParam], onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Foretell", paramShapes := [CostParam], onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Bestow", paramShapes := [CostParam], paidCost := True } defaultKeywordFacts
  , { word := "Disguise", paramShapes := [CostParam], paidCost := True } defaultKeywordFacts
  , { word := "Mutate", paramShapes := [CostParam], regime := Just AtCasting, paidCost := True } defaultKeywordFacts
  , { word := "Overload", paramShapes := [CostParam], regime := Just AtCasting, onPermanentCard := False, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Dash", paramShapes := [CostParam], regime := Just AtCasting, paidCost := True } defaultKeywordFacts
  , { word := "Evoke", paramShapes := [CostParam], paidCost := True } defaultKeywordFacts
  , { word := "Blitz", paramShapes := [CostParam], regime := Just AtCasting, paidCost := True } defaultKeywordFacts
  , { word := "Cleave", paramShapes := [CostParam], regime := Just AtCasting, onPermanentCard := False, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Harmonize", paramShapes := [CostParam], onPermanentCard := False, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Impending", paramShapes := [CompoundParam NumberHead], regime := Just AtCasting, paidCost := True } defaultKeywordFacts
  , { word := "Awaken", paramShapes := [CompoundParam NumberHead], regime := Just AtCasting, onPermanentCard := False, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Buyback", paramShapes := [CostParam], regime := Just AtCasting, onPermanentCard := False, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Casualty", paramShapes := [NumberParam], regime := Just AtCasting, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Squad", paramShapes := [CostParam], regime := Just AtCasting, paidCost := True } defaultKeywordFacts
  , { word := "Offspring", paramShapes := [CostParam], regime := Just AtCasting, paidCost := True } defaultKeywordFacts
  , { word := "Gift", paramShapes := [SubjectParam], regime := Just AtCasting, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Replicate", paramShapes := [CostParam], regime := Just AtCasting, onPermanentCard := False, onSpellCard := True, paidCost := True } defaultKeywordFacts
  , { word := "Delve", paramShapes := [NoParam], regime := Just AtCasting, onSpellCard := True } defaultKeywordFacts
  , { word := "Infect", paramShapes := [NoParam], regime := Just AtResolution } defaultKeywordFacts
  , { word := "Cascade", paramShapes := [NoParam], regime := Just AtCasting, onSpellCard := True, bodied := True } defaultKeywordFacts
  , { word := "Prowess", paramShapes := [NoParam], regime := Just AtCasting, bodied := True } defaultKeywordFacts
  , { word := "SplitSecond", paramShapes := [NoParam], onPermanentCard := False, onSpellCard := True } defaultKeywordFacts
  , { word := "Phasing", paramShapes := [NoParam] } defaultKeywordFacts
  , { word := "Decayed", paramShapes := [NoParam], counterEligible := True } defaultKeywordFacts
  , { word := "Exalted", paramShapes := [NoParam], counterEligible := True, bodied := True } defaultKeywordFacts
  , { word := "Shadow", paramShapes := [NoParam], counterEligible := True } defaultKeywordFacts
  ]
