//! The card-domain macro configuration: which core types are macroable, and
//! with what reader policy, glued onto [`macro_ron`]. Definitions live in
//! `plugins/*/macros/**/*.ron` (paths and file names are organizational
//! only) and are invoked by name where a value of one of their kinds is
//! expected — see [`crate::plugin`] for loading and the `macro_ron` crate
//! docs for the language itself.
//!
//! Subtype definitions are ordinary macro files, usually written as
//! meta-macro invocations (`CreatureType(name: "TimeLord", template:
//! "Time Lord")`) — `name` is the registration ident cards invoke,
//! `template` the printed name carried in the value.

pub use macro_ron::InsertError;
use macro_ron::KindSet;
pub use macro_ron::MacroDef;
pub use macro_ron::MacroSet;
pub use macro_ron::ParamType;
pub use macro_ron::ParamTypeSet;
pub use macro_ron::Params;

/// The kinds of value a macro can expand to: the core types whose parse
/// positions consult the macro namespace. Which types are macroable is
/// consumer policy (this list); the per-kind facts (remembers / embeds /
/// literal wrapper) are generated by each type's `#[derive(SupportsMacros)]`.
/// So `Count::kind()` carries the bare-numeral `Literal(N)` reader sugar
/// (core's grammar stays strict); `Selection::kind()` remembers *and*
/// embeds its `Reference` untagged, so a bare `This`/`Target(0)` at a
/// Selection slot reads as `Selection::Ref(...)` with no wrapper; and
/// `Action::kind()` — no `Expanded` variant, so no macros of its own —
/// only embeds `PlayerAction` untagged, so a bare `Draw(1)`/`Tap(This)`
/// reads as `Action::By(You, ...)`, the implicit-you default.
///
/// The struct kinds `CardFace`, `Subtype`, and `Macro` are name-erasing:
/// `Subtype` already self-names; nothing engine-meaningful invokes `CardFace`
/// macros; and `Macro` is the loader-only position for `MacroDef` itself.
// When adding a new macroable core type, add its `T::kind()` to the shared
// registry in `deckmaste_core::ron::kinds` AND its name in
// `kind_names_track_the_core_types`.
#[must_use]
pub fn kinds() -> KindSet {
    use deckmaste_core::SupportsMacros as _;
    // Core types come from the shared registry; cards-only macroable types
    // (the strategy `Preference`) are added on top.
    let mut kinds = deckmaste_core::ron::kinds();
    kinds.add(crate::strategy::Preference::kind());
    kinds
}

/// The param types in scope for deckmaste plugins: the domain-neutral
/// built-ins (`Any`, `String`) plus deckmaste's `Color`, `Filter`, and
/// `Reference`. A validator reads the argument as its Rust type with macros
/// in scope, so the check and the real grammar are one path.
#[must_use]
pub fn param_types() -> ParamTypeSet {
    let mut param_types = ParamTypeSet::default();
    param_types.add_typed::<deckmaste_core::Color>("Color");
    param_types.add_typed::<deckmaste_core::Filter>("Filter");
    // A reference slot: the object/player a macro compares against
    // (`SharesColorWith(Ref(This))`, `SharesColor(Subject, This)`). Also types
    // regeneration's `Regenerate(target)` param.
    param_types.add_typed::<deckmaste_core::Reference>("Reference");
    // A keyword/cost slot: the bracketed cost-component list authored as the
    // macro's argument (`[Mana([Generic(2)])]`, `[Mana(...), Do(LoseLife(2))]`).
    param_types.add_typed::<Vec<deckmaste_core::CostComponent>>("Cost");
    // A count slot (`PumpThisUntilEot`'s P/T magnitudes): a bare numeral reads as
    // `Count::Literal`, dynamic counts as `CountOf`/`StatOf`.
    param_types.add_typed::<deckmaste_core::Count>("Count");
    param_types
}

/// An empty [`MacroSet`] over the card kinds, reading deckmaste's RON
/// dialect.
#[must_use]
pub fn macro_set() -> MacroSet {
    MacroSet::new(kinds())
        .with_options(deckmaste_core::ron::raw_options())
        .with_param_types(param_types())
}

#[cfg(test)]
mod tests {
    use deckmaste_core::Ability;
    use deckmaste_core::Action;
    use deckmaste_core::AsThough;
    use deckmaste_core::CardFace;
    use deckmaste_core::CharacteristicFilter;
    use deckmaste_core::Condition;
    use deckmaste_core::CostComponent;
    use deckmaste_core::Count;
    use deckmaste_core::Counter;
    use deckmaste_core::Effect;
    use deckmaste_core::Event;
    use deckmaste_core::Filter;
    use deckmaste_core::KeywordAbility;
    use deckmaste_core::ManaRider;
    use deckmaste_core::ObjectKind;
    use deckmaste_core::PlayerAction;
    use deckmaste_core::Quantity;
    use deckmaste_core::Reference;
    use deckmaste_core::Replacement;
    use deckmaste_core::Selection;
    use deckmaste_core::StateFilter;
    use deckmaste_core::StaticEffect;
    use deckmaste_core::Subtype;
    use deckmaste_core::TargetSpec;
    use deckmaste_core::Type;
    use deckmaste_core::Zone;

    use super::*;
    use crate::strategy::Preference;

    /// Parses a definition the way plugin loading does: from RON source in
    /// deckmaste's dialect. (`MacroDef`'s body field is crate-private in
    /// `macro_ron`, so file-shaped source is the construction path here —
    /// which is also what real definitions are.)
    fn def(source: &str) -> MacroDef {
        deckmaste_core::ron::options().from_str(source).unwrap()
    }

    /// The registry matches on serde type names. The derived `kind()`s
    /// self-name from the Rust ident, so they track renames by
    /// construction; the tie this pins is the hand-registered struct kinds
    /// (`CardFace`, `Subtype`, `Macro`), which a Rust rename would strand
    /// without a compile error — plus the policy list's completeness (the
    /// length check).
    #[test]
    fn kind_names_track_the_core_types() {
        fn name_of<T>() -> &'static str {
            std::any::type_name::<T>().rsplit("::").next().unwrap()
        }
        let names = [
            name_of::<Ability>(),
            name_of::<Action>(),
            name_of::<AsThough>(),
            name_of::<CardFace>(),
            name_of::<Condition>(),
            name_of::<Count>(),
            name_of::<CostComponent>(),
            name_of::<Effect>(),
            name_of::<Event>(),
            name_of::<Filter>(),
            name_of::<KeywordAbility>(),
            name_of::<ManaRider>(),
            name_of::<PlayerAction>(),
            name_of::<Preference>(),
            name_of::<Quantity>(),
            name_of::<Reference>(),
            name_of::<Replacement>(),
            name_of::<Selection>(),
            name_of::<StaticEffect>(),
            name_of::<Subtype>(),
            name_of::<TargetSpec>(),
            name_of::<Counter>(),
            "Macro", // hand-registered: MacroDef's serde rename, loader-only
        ];
        let kinds = kinds();
        for name in names {
            assert!(kinds.contains(name), "`{name}` is not a registered kind");
        }
        assert_eq!(kinds.len(), names.len());
    }

    /// Filter's generated Deserialize calls `deserialize_enum` with the
    /// full flattened variant list (its own names plus the compartments'):
    /// that is what lets unknown names at Filter positions fall through to
    /// the macro namespace.
    #[test]
    fn filter_positions_expand_macros() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "AnyTargetish",
                    kinds: [Filter],
                    body: OneOf([Kind(Player), AllOf([InZone(Battlefield), Type(Creature)])]),
                )"#))
            .unwrap();
        let filter: Filter = macros.read_str("AnyTargetish").unwrap();
        // The invocation is remembered; the expansion lives under `.value`.
        let Filter::Expanded(expanded) = filter else {
            panic!("expected a remembered filter, got {filter:?}");
        };
        assert_eq!(expanded.name, "AnyTargetish");
        let Filter::OneOf(arms) = *expanded.value else {
            panic!("expected OneOf, got {:?}", expanded.value);
        };
        assert_eq!(arms[0], Filter::Kind(ObjectKind::Player));
        // The nested arm proves Filter positions *inside* an expansion stay
        // macro-aware too.
        assert_eq!(
            arms[1],
            Filter::AllOf(vec![
                Filter::State(StateFilter::InZone(Zone::Battlefield)),
                Filter::Characteristic(CharacteristicFilter::Type(Type::Creature)),
            ])
        );
        assert_eq!(arms.len(), 2);
    }

    /// Same pin for Selection positions: nothing exercises Selection macros
    /// in real data yet, and Plan 2 will make this path load-bearing.
    #[test]
    fn selection_positions_expand_macros() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "EachCreature",
                    kinds: [Selection],
                    body: Each(Type(Creature)),
                )"#))
            .unwrap();
        let selection: Selection = macros.read_str("EachCreature").unwrap();
        let Selection::Expanded(expanded) = selection else {
            panic!("expected a remembered selection, got {selection:?}");
        };
        assert_eq!(expanded.name, "EachCreature");
        assert_eq!(
            *expanded.value,
            Selection::Each(Filter::Characteristic(CharacteristicFilter::Type(
                Type::Creature
            )))
        );
    }

    /// A bare `Reference` at a `Selection` slot reads through the untagged
    /// embed — no `Ref(...)` wrapper in the source — and wraps in
    /// `Selection::Ref`. The macro layer's `embeds_untagged` hook routes the
    /// non-Selection identifier through `Selection`'s `visit_newtype_struct`.
    #[test]
    fn bare_reference_embeds_at_selection_slot() {
        let macros = macro_set();
        assert_eq!(
            macros.read_str::<Selection>("This").unwrap(),
            Selection::Ref(Reference::This),
        );
        assert_eq!(
            macros.read_str::<Selection>("Target(0)").unwrap(),
            Selection::Ref(Reference::Target(0)),
        );
        assert_eq!(
            macros.read_str::<Selection>("ControllerOf(This)").unwrap(),
            Selection::Ref(Reference::ControllerOf(Box::new(Reference::This))),
        );
    }

    /// A `Reference` *macro* invoked at a `Selection` slot routes through the
    /// embed to `Reference`'s own reader: it expands and is remembered as a
    /// `Reference::Expanded`, then wraps in `Selection::Ref`.
    #[test]
    fn reference_macro_embeds_at_selection_slot() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "MyController",
                    kinds: [Reference],
                    body: ControllerOf(This),
                )"#))
            .unwrap();
        let selection: Selection = macros.read_str("MyController").unwrap();
        let Selection::Ref(Reference::Expanded(expanded)) = selection else {
            panic!("expected Ref(Reference::Expanded(..)), got {selection:?}");
        };
        assert_eq!(expanded.name, "MyController");
        assert_eq!(
            *expanded.value,
            Reference::ControllerOf(Box::new(Reference::This)),
        );
    }

    /// A bare `PlayerAction` at an `Action` slot reads through the untagged
    /// embed — no `By(...)` wrapper in the source — and wraps in
    /// `Action::By(You, …)`, the implicit-you default. The macro layer's
    /// `embeds_untagged` hook routes the non-Action identifier through
    /// `Action`'s `visit_newtype_struct`.
    #[test]
    fn bare_player_action_embeds_at_action_slot() {
        let macros = macro_set();
        assert_eq!(
            macros.read_str::<Action>("Draw(1)").unwrap(),
            Action::By(Reference::You, PlayerAction::Draw(Count::Literal(1))),
        );
        assert_eq!(
            macros.read_str::<Action>("Sacrifice(This)").unwrap(),
            Action::By(
                Reference::You,
                PlayerAction::Sacrifice(Selection::Ref(Reference::This)),
            ),
        );
        assert_eq!(
            macros.read_str::<Action>("Tap(This)").unwrap(),
            Action::By(
                Reference::You,
                PlayerAction::Tap(Selection::Ref(Reference::This)),
            ),
        );
    }

    /// An explicit different agent (`By(Target(0), Draw(3))` — Ancestral
    /// Recall) reads natively through `Action`'s own variants, not the embed.
    #[test]
    fn explicit_agent_reads_natively_at_action_slot() {
        let macros = macro_set();
        assert_eq!(
            macros.read_str::<Action>("By(Target(0), Draw(3))").unwrap(),
            Action::By(Reference::Target(0), PlayerAction::Draw(Count::Literal(3))),
        );
    }

    /// A source-agent verb (`DealDamage`) reads natively at an `Action` slot;
    /// the `Selection` inside still embeds the bare reference.
    #[test]
    fn source_verb_reads_natively_at_action_slot() {
        let macros = macro_set();
        assert_eq!(
            macros.read_str::<Action>("DealDamage(This, 3)").unwrap(),
            Action::DealDamage(Selection::Ref(Reference::This), Count::Literal(3)),
        );
    }

    /// A `PlayerAction` *macro* invoked at an `Action` slot routes through the
    /// embed to `PlayerAction`'s own reader: it expands, is remembered as a
    /// `PlayerAction::Expanded`, then wraps in `Action::By(You, …)`.
    #[test]
    fn player_action_macro_embeds_at_action_slot() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "DrawTwo",
                    kinds: [PlayerAction],
                    body: Draw(2),
                )"#))
            .unwrap();
        let action: Action = macros.read_str("DrawTwo").unwrap();
        let Action::By(Reference::You, PlayerAction::Expanded(expanded)) = action else {
            panic!("expected By(You, PlayerAction::Expanded(..)), got {action:?}");
        };
        assert_eq!(expanded.name, "DrawTwo");
        assert_eq!(*expanded.value, PlayerAction::Draw(Count::Literal(2)));
    }

    /// Same pin for the `TargetSpec` positions (the announce-list type).
    #[test]
    fn target_spec_positions_expand_macros() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "TargetCreature",
                    kinds: [TargetSpec],
                    body: Target(Exactly(Literal(1)), Type(Creature)),
                )"#))
            .unwrap();
        let spec: TargetSpec = macros.read_str("TargetCreature").unwrap();
        let TargetSpec::Expanded(expanded) = spec else {
            panic!("expected a remembered target spec, got {spec:?}");
        };
        assert_eq!(expanded.name, "TargetCreature");
        assert_eq!(
            *expanded.value,
            TargetSpec::Target(
                Quantity::Exactly(Count::Literal(1)),
                Filter::Characteristic(CharacteristicFilter::Type(Type::Creature)),
            )
        );
    }

    /// And for Reference positions.
    #[test]
    fn reference_positions_expand_macros() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "MyController",
                    kinds: [Reference],
                    body: ControllerOf(This),
                )"#))
            .unwrap();
        let reference: Reference = macros.read_str("MyController").unwrap();
        let Reference::Expanded(expanded) = reference else {
            panic!("expected a remembered reference, got {reference:?}");
        };
        assert_eq!(expanded.name, "MyController");
        assert_eq!(
            *expanded.value,
            Reference::ControllerOf(Box::new(Reference::This))
        );
    }

    /// `CostComponent` positions participate in macro expansion: a
    /// registered `CostComponent` macro is expanded in place of its name.
    #[test]
    fn cost_positions_expand_macros() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "SacThis",
                    kinds: [CostComponent],
                    body: Do(Sacrifice(This)),
                )"#))
            .unwrap();
        let cost: CostComponent = macros.read_str("SacThis").unwrap();
        let CostComponent::Expanded(expanded) = cost else {
            panic!("expected a remembered cost component, got {cost:?}");
        };
        assert_eq!(expanded.name, "SacThis");
        assert_eq!(
            *expanded.value,
            CostComponent::Do(Box::new(PlayerAction::Sacrifice(Selection::from(
                Reference::This
            ))))
        );
    }

    /// A remembered invocation round-trips as the invocation through the
    /// real core types' `Serialize` impls: a nullary Ability
    /// macro serializes back to its bare name, a parameterized Filter macro
    /// to the original call text — not the expansion.
    #[test]
    fn remembered_invocations_round_trip_as_invocations() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "Flying",
                    kinds: [Ability],
                    body: Static(effects: [Cant(Attack(by: Ref(This)))]),
                )"#))
            .unwrap();
        macros
            .insert(&def(r#"(
                    name: "OfType",
                    kinds: [Filter],
                    params: [Any],
                    body: Type(Param(0)),
                )"#))
            .unwrap();

        let ability: Ability = macros.read_str("Flying").unwrap();
        assert_eq!(
            deckmaste_core::ron::options().to_string(&ability).unwrap(),
            "Flying"
        );

        let filter: Filter = macros.read_str("OfType(Creature)").unwrap();
        assert_eq!(
            deckmaste_core::ron::options().to_string(&filter).unwrap(),
            "OfType(Creature)"
        );
    }

    /// `expand_all` over a real converted type: an `Effect` read through the
    /// card macro set carries the remembered `Expanded` node (here nested in
    /// a `Sequence`, proving recursion through real grammar containers), and
    /// expanding strips it — the result serializes as the fully-expanded RON,
    /// not the invocation.
    #[test]
    fn expand_all_strips_remembered_invocations() {
        use deckmaste_core::Expand as _;

        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "DrawTwo",
                    kinds: [Effect],
                    body: Draw(2),
                )"#))
            .unwrap();
        let effect: Effect = macros.read_str("Sequence([DrawTwo])").unwrap();
        let Effect::Sequence(steps) = &effect else {
            panic!("expected a sequence, got {effect:?}");
        };
        assert!(matches!(steps[0], Effect::Expanded(_)));

        let expanded = effect.expand_all();
        assert_eq!(
            expanded,
            Effect::Sequence(vec![Effect::Act(Action::By(
                Reference::You,
                PlayerAction::Draw(Count::Literal(2)),
            ))])
        );
        let written = deckmaste_core::ron::options().to_string(&expanded).unwrap();
        assert!(!written.contains("DrawTwo"), "macro name leaked: {written}");
        // A `Count` literal writes bare — `2`, never `Literal(2)`.
        assert_eq!(written, "Sequence([Draw(2)])");
    }

    /// The literal sugar applies to `Count` through the glue's registry:
    /// a bare numeral splices to `Literal`, identifier-led variants pass
    /// straight through.
    #[test]
    fn count_sugar_applies_to_core_count() {
        let count: Count = macro_set().read_str("3").unwrap();
        assert_eq!(count, Count::Literal(3));
        let count: Count = macro_set().read_str("X").unwrap();
        assert_eq!(count, Count::X);
    }

    /// A `Count` macro expands at the *position* slot of `PutInLibrary`,
    /// read at an `Action` slot through the implicit-`You` embed. This is the
    /// seam that lets a `CardsInLibrary(...)`-style macro name the bottom of
    /// the library — the position stays macro-aware inside the 2-tuple verb.
    #[test]
    fn count_macro_expands_at_put_in_library_position() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "DeckSize",
                    kinds: [Count],
                    body: CountOf(InZone(Library)),
                )"#))
            .unwrap();
        let action: Action = macros.read_str("PutInLibrary(This, DeckSize)").unwrap();
        let Action::By(Reference::You, PlayerAction::PutInLibrary(sel, pos)) = action else {
            panic!("expected By(You, PutInLibrary(..)), got {action:?}");
        };
        assert_eq!(sel, Selection::Ref(Reference::This));
        let Count::Expanded(expanded) = pos else {
            panic!("expected a remembered count at the position, got {pos:?}");
        };
        assert_eq!(expanded.name, "DeckSize");
    }

    /// `Color` is a registered param type, so a definition may declare it.
    #[test]
    fn color_is_a_registered_param_type() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "TapsForColor",
                    kinds: [Subtype],
                    params: [Color],
                    body: Subtype(name: Param(0), types: [Land]),
                )"#))
            .expect("a Color param type should be registered");
    }

    /// `Reference` is a registered param type, so a macro may take one — the
    /// hook `SharesColorWith(ref)` / `SharesColor(a, b)` rely on.
    #[test]
    fn reference_is_a_registered_param_type() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "IsThat",
                    kinds: [Filter],
                    params: [Reference],
                    body: Ref(Param(0)),
                )"#))
            .expect("a Reference param type should be registered");
    }

    /// `SupportsMacros` guarantees `DeserializeOwned`: a function generic over
    /// the trait can deserialize a value of that type through the macro layer.
    /// This compiles only because the supertrait bond holds — the param-type
    /// validators (`read_str::<T>`) rely on exactly that guarantee.
    #[test]
    fn supports_macros_guarantees_deserialize_owned() {
        fn read_one<T: deckmaste_core::SupportsMacros>(
            macros: &MacroSet,
            src: &str,
        ) -> Result<T, ron::error::SpannedError> {
            macros.read_str::<T>(src)
        }
        let macros = macro_set();
        let parsed: Reference = read_one(&macros, "This").expect("This is a Reference");
        assert_eq!(parsed, Reference::This);
    }

    /// A `Color` param rejects a non-color at the call site, before the body
    /// ever expands — the headline behavior. (Body simplified; the real
    /// `confers` ability is exercised by the builtin validation test.)
    #[test]
    fn basic_land_type_rejects_non_color() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "BasicLandType",
                    kinds: [Subtype],
                    params: [String, Color],
                    body: Subtype(name: Param(0), types: [Land]),
                )"#))
            .unwrap();
        let error = macros
            .read_str::<Subtype>(r#"BasicLandType("Plains", Purple)"#)
            .unwrap_err();
        let msg = error.to_string();
        assert!(
            msg.contains("BasicLandType") && msg.contains("Color"),
            "unexpected error: {msg}"
        );
    }

    /// A real color is accepted and the name binds.
    #[test]
    fn basic_land_type_accepts_color() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "BasicLandType",
                    kinds: [Subtype],
                    params: [String, Color],
                    body: Subtype(name: Param(0), types: [Land]),
                )"#))
            .unwrap();
        let subtype: deckmaste_core::Subtype = macros
            .read_str(r#"BasicLandType("Plains", White)"#)
            .unwrap();
        assert_eq!(subtype.name, "Plains");
    }

    /// A quoted-string name at a `[String]` subtype macro still expands — the
    /// seven unchanged subtype macros keep working.
    #[test]
    fn creature_type_still_expands() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "CreatureType",
                    kinds: [Subtype],
                    params: [String],
                    body: Subtype(name: Param(0), types: [Creature]),
                )"#))
            .unwrap();
        let subtype: deckmaste_core::Subtype = macros.read_str(r#"CreatureType("Bear")"#).unwrap();
        assert_eq!(subtype.name, "Bear");
    }

    /// The real subtype-meta shape: `template` defaults to `name`, so the
    /// majority of subtype files omit it.
    #[test]
    fn subtype_meta_template_defaults_to_name() {
        let mut macros = macro_set();
        macros
            .insert(&def(r#"(
                    name: "CreatureType",
                    kinds: [Macro],
                    params: { "name": String, "template": Default(String, Param(name)) },
                    body: (
                        name: Param(name),
                        kinds: [Subtype],
                        body: Subtype(name: Param(template), types: [Creature]),
                    ),
                )"#))
            .unwrap();
        let produced: MacroDef = macros.read_str(r#"CreatureType(name: "Zombie")"#).unwrap();
        macros.insert(&produced).unwrap();
        let subtype: deckmaste_core::Subtype = macros.read_str("Zombie").unwrap();
        assert_eq!(subtype.name, "Zombie");
    }
}
