//! The macro layer over the authored grammar: which types are macroable, and
//! with what reader policy, glued onto [`macro_ron`]. Definitions live in
//! `plugins/*/macros/**/*.ron` (paths and file names are organizational only)
//! and are invoked by name where a value of one of their kinds is expected.
//!
//! Forked from `deckmaste_plugin::macros`, which keeps its own copy until
//! `plugin-repoint` retires it.

pub use macro_ron::InsertError;
use macro_ron::KindSet;
pub use macro_ron::MacroDef;
pub use macro_ron::MacroSet;
pub use macro_ron::ParamType;
pub use macro_ron::ParamTypeSet;
pub use macro_ron::Params;

/// The kinds of value a macro can expand to. Which types are macroable is
/// consumer policy; the per-kind facts (remembers / embeds / literal wrapper)
/// are generated by each type's `#[derive(SupportsMacros)]`.
#[must_use]
pub fn kinds() -> KindSet {
    crate::ron::kinds()
}

/// The param types in scope for deckmaste plugins: the domain-neutral built-ins
/// (`Any`, `String`) plus a validator for EVERY macroable grammar kind, so a
/// `params: [Any]` slot is the deliberate escape hatch, not the default. A
/// validator reads the argument as its Rust type with macros in scope, so the
/// check and the real grammar are one path (a bad `Color`, `OneShotEffect`,
/// `Predicate`, … fails at the call site exactly as it would at a real
/// position).
///
/// The registered name is the type's own serde name (`Predicate`,
/// `OneShotEffect`, `Reference`), with three shaped exceptions carrying their
/// own spelling: `Color` (a characteristic, not a macro kind), `Cost` (the
/// *list* form `Vec<CostComponent>`, the bracketed keyword-cost argument), and
/// `Abilities` (the `Vec<Ability>` a `Composite`/keyword meta forwards).
///
/// Load-bearing for reading, not just validation: [`MacroSet::insert`] rejects
/// a definition naming an unregistered param type.
#[must_use]
pub fn param_types() -> ParamTypeSet {
    use crate as da;
    let mut param_types = ParamTypeSet::default();
    // A characteristic, not a macro kind: the basic-land / protection color.
    param_types.add_typed::<da::Color>("Color");
    // The bracketed cost-component LIST authored as a macro's argument
    // (`[Mana([Generic(2)])]`, `[Mana(...), Do(LoseLife(2))]`) — the list form,
    // spliced by `Splice(Param(i))`; distinct from the single `CostComponent`.
    param_types.add_typed::<Vec<da::CostComponent>>("Cost");
    // The `Vec<Ability>` a keyword/`Composite` meta forwards
    // (`KeywordAbility(abilities: [...])`).
    param_types.add_typed::<Vec<da::Ability>>("Abilities");
    // A LIST of counts (`[1]`, `[2, 3]`) — the one-or-more chapter numbers a
    // saga `Chapter`'s crossing gate holds ([CR#714.2c] ranges), spliced into
    // `Crossed { thresholds }`; distinct from the single `Count`.
    param_types.add_typed::<Vec<da::Count>>("Counts");
    // Every macroable grammar kind gets its own-name validator.
    param_types.add_typed::<da::Ability>("Ability");
    param_types.add_typed::<da::Action>("Action");
    param_types.add_typed::<da::AsThough>("AsThough");
    param_types.add_typed::<da::Condition>("Condition");
    param_types.add_typed::<da::CostComponent>("CostComponent");
    param_types.add_typed::<da::Count>("Count");
    // The enters-with-counters macro's counter-kind argument
    // (`EntersWithCounters(P1P1Counter, 1)`) — a bare `CounterRef` ident, not a
    // `Counter`-kind macro invocation (`Counter` is decl-only/name-erasing;
    // nothing at a card position reads it — see `crate::ron::kinds`).
    param_types.add_typed::<da::CounterRef>("CounterRef");
    param_types.add_typed::<da::Destination>("Destination");
    param_types.add_typed::<da::OneShotEffect>("OneShotEffect");
    param_types.add_typed::<da::EventFilter>("EventFilter");
    param_types.add_typed::<da::Predicate>("Predicate");
    // A card-type-descriptor `Predicate` — the same `Predicate` value, but a
    // distinct param NAME so the `OneShotEffect`-macro slot reader routes it
    // through the card classifier ("snow" -> `Supertype(Snow)`,
    // "land"/"creature" -> `Type(_)`) rather than the general filter grammar,
    // and no other `Predicate` slot is affected.
    param_types.add_typed::<da::Predicate>("CardTypePredicate");
    param_types.add_typed::<da::KeywordAbility>("KeywordAbility");
    param_types.add_typed::<da::ManaRider>("ManaRider");
    param_types.add_typed::<da::Modification>("Modification");
    // The numeric-axis op (`Up`/`Down`/`Set`) — a macro arg for the arity-2
    // power+toughness building block `PowerAndToughness(op, op)`.
    param_types.add_typed::<da::NumericOp>("NumericOp");
    param_types.add_typed::<da::Quantity>("Quantity");
    param_types.add_typed::<da::Reference>("Reference");
    param_types.add_typed::<da::Replacement>("Replacement");
    param_types.add_typed::<da::Selection>("Selection");
    param_types.add_typed::<da::StaticEffect>("StaticEffect");
    param_types.add_typed::<da::TargetSpec>("TargetSpec");
    param_types.add_typed::<da::Subtype>("Subtype");
    // The card-TYPE arg of the `PermanentOfType(T)` / bare `Type(T)` filter
    // forms — a `TypeDef`-kind macro name (`Creature`), validated by reading it
    // as a `TypeDef` with macros in scope (an undeclared type is rejected at the
    // call site).
    param_types.add_typed::<da::TypeDef>("TypeDef");
    param_types.add_typed::<da::Zone>("Zone");
    // No `Preference` row: strategy RON is outside the authoring program
    // (§3/§4), and no plugin definition declares that param.
    // A plain non-negative literal number (`PayEnergy(2)`) — distinct from the
    // `Count` enum: a fixed count with no "for each …" reading. Read as `Uint`,
    // the type `Count::Literal` wraps.
    param_types.add_typed::<da::Uint>("Uint");
    param_types
}

/// An empty [`MacroSet`] over the authoring kinds, reading deckmaste's RON
/// dialect.
#[must_use]
pub fn macro_set() -> MacroSet {
    MacroSet::new(kinds())
        .with_options(crate::ron::raw_options())
        .with_param_types(param_types())
}
