use crate::Count;
use crate::Expansion;
use crate::SupportsMacros;

/// A cardinality range over a scalar [`Count`]: how many objects an effect
/// operates on, never a continuous magnitude (amounts use `Count` directly).
///
/// One canonical primitive — `Range(lo, hi)`, each bound optional (`None` =
/// unbounded that side) — with the readable named forms (`Exactly`, `AtLeast`,
/// `AtMost`, `Between`, `AnyNumber`) recovered as builtin **macros** at the
/// `Quantity` position (`plugins/builtin/macros/quantity/`). Because the kind
/// remembers its expansions, an `Exactly(1)` invocation round-trips back to
/// `Exactly(1)` rather than the bare `Range(1, 1)`.
///
/// Bound ordering and non-zero validity are runtime concerns: an inverted
/// `Range(Some(5), Some(2))` and a degenerate "up to 0" are equally
/// constructible here, exactly as they were under the named variants.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Quantity {
    /// `Range(lo, hi)` — an inclusive cardinality range. `None` on a side is
    /// unbounded ([CR#601.2c] "any number" = `Range(None, None)`).
    Range(Option<Count>, Option<Count>),
    /// A remembered `Quantity` macro invocation (`Exactly`, `AtLeast`, …).
    #[macro_ron(expanded)]
    Expanded(Expansion<Quantity>),
}

impl Quantity {
    /// Exactly one object — `Range(Some(1), Some(1))`, the single-target/
    /// single-choice cardinality that recurs across target specs and
    /// selections.
    #[must_use]
    pub fn one() -> Quantity {
        Quantity::Range(Some(Count::Literal(1)), Some(Count::Literal(1)))
    }

    /// The `(lower, upper)` bound pair, seeing through a remembered macro
    /// invocation ([`Quantity::Expanded`]). `None` on a side = unbounded.
    /// The one read every consumer makes — lower/upper bound is a field read,
    /// not a five-way match.
    #[must_use]
    pub fn bounds(&self) -> (Option<&Count>, Option<&Count>) {
        match self {
            Quantity::Range(lo, hi) => (lo.as_ref(), hi.as_ref()),
            Quantity::Expanded(e) => e.value.bounds(),
        }
    }

    /// Whether this quantity is exactly one (`Range(Some(1), Some(1))`),
    /// seeing through a remembered invocation — the single-target predicate the
    /// announce-list renderer and target machinery ask.
    #[must_use]
    pub fn is_one(&self) -> bool {
        matches!(
            self.bounds(),
            (Some(Count::Literal(1)), Some(Count::Literal(1)))
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Count;

    fn read(source: &str) -> Quantity {
        crate::ron::options().from_str(source).unwrap()
    }

    fn write(value: &Quantity) -> String {
        crate::ron::options().to_string(value).unwrap()
    }

    /// The single primitive parses with bare-numeral bounds and unbounded
    /// `None` sides, and round-trips identically.
    #[test]
    fn range_reads_and_round_trips() {
        let cases = [
            (
                "Range(1, 1)",
                Quantity::Range(Some(Count::Literal(1)), Some(Count::Literal(1))),
            ),
            (
                "Range(2, None)",
                Quantity::Range(Some(Count::Literal(2)), None),
            ),
            (
                "Range(None, 3)",
                Quantity::Range(None, Some(Count::Literal(3))),
            ),
            ("Range(None, None)", Quantity::Range(None, None)),
            ("Range(X, None)", Quantity::Range(Some(Count::X), None)),
        ];
        for (src, want) in cases {
            assert_eq!(read(src), want, "parse failed for {src}");
            assert_eq!(read(&write(&want)), want, "round-trip failed for {src}");
        }
    }

    /// `one()` is the exactly-one range, and `is_one`/`bounds` read it.
    #[test]
    fn one_is_exactly_one() {
        let q = Quantity::one();
        assert_eq!(
            q,
            Quantity::Range(Some(Count::Literal(1)), Some(Count::Literal(1)))
        );
        assert!(q.is_one());
        assert_eq!(
            q.bounds(),
            (Some(&Count::Literal(1)), Some(&Count::Literal(1)))
        );
        assert!(!Quantity::Range(None, None).is_one());
    }

    /// A remembered macro invocation (built by hand here) round-trips as the
    /// invocation, and `bounds`/`is_one` see through it.
    #[test]
    fn expanded_sees_through_to_bounds() {
        use crate::Expansion;
        use crate::ExpansionArgs;
        let exactly_one = Quantity::Expanded(Expansion {
            name: "Exactly".into(),
            args: ExpansionArgs::Positional(vec!["1".into()]),
            template: None,
            value: Box::new(Quantity::Range(
                Some(Count::Literal(1)),
                Some(Count::Literal(1)),
            )),
        });
        assert!(exactly_one.is_one());
        // Serializes as the invocation, not the expansion.
        assert_eq!(write(&exactly_one), "Exactly(1)");
    }
}
