//! The central RON configuration and helpers shared by everything that reads
//! or writes the authored grammar.

use std::sync::LazyLock;

use macro_ron::Kind;
use macro_ron::KindSet;
use macro_ron::MacroSet;
use macro_ron::SupportsMacros;
use serde::Serialize;
use serde::de::DeserializeOwned;

/// Every macro-position kind in deckmaste's RON dialect, keyed by serde name.
/// Used both by the literal-aware reader ([`options`]) and by the full macro
/// layer in [`crate::macros`]; lives here so the two share one registry. The
/// kind facts (`flatten`/`embed`/`expanded`/`literal` markers) are generated by
/// each type's `#[derive(SupportsMacros)]`, so this only enumerates the types.
///
/// Kinds are keyed by SERDE NAME, not by type path, so a `Kind` minted here and
/// one minted from the corresponding `deckmaste_core` type are the same kind to
/// `macro_ron`. That is what lets every existing macro definition in
/// `plugins/*/macros` parse against this grammar unchanged.
#[must_use]
pub fn kinds() -> KindSet {
    let mut kinds = KindSet::new();
    kinds.add(crate::Ability::kind());
    kinds.add(crate::AsThough::kind());
    kinds.add(crate::Action::kind());
    kinds.add(crate::Condition::kind());
    kinds.add(crate::CostComponent::kind());
    kinds.add(crate::Count::kind());
    // `Move`'s destination: a bare zone name flattens in from `Zone`, the
    // library form is `Library(FromTop/FromBottom(Count))`.
    kinds.add(crate::Destination::kind());
    kinds.add(crate::Zone::kind());
    kinds.add(crate::OneShotEffect::kind());
    kinds.add(crate::EventFilter::kind());
    kinds.add(crate::Predicate::kind());
    kinds.add(crate::KeywordAbility::kind());
    kinds.add(crate::ManaRider::kind());
    // Mana specs and the production wrapper embed their inner value untagged
    // (a bare `White`/`AnyColor` reads as `ManaSpec`; a bare spec at a
    // production slot reads as `ManaProduction::Bare`) — registered so the
    // macro layer takes the embed fall-through and a macro nested in a rider
    // stays on the macro-aware path.
    kinds.add(crate::ManaProduction::kind());
    kinds.add(crate::ManaSpec::kind());
    // The mana-symbol leaves embed their inner value untagged too, so a bare
    // `White`/`Generic(2)` reads at a symbol slot: `ColorOrColorless` embeds
    // `Color`, `SimpleManaSymbol` embeds `ColorOrColorless`, `ManaSymbol` embeds
    // `SimpleManaSymbol`. `Color` itself is the terminal payload (no embed), so
    // it needs no registration.
    kinds.add(crate::ColorOrColorless::kind());
    kinds.add(crate::SimpleManaSymbol::kind());
    kinds.add(crate::ManaSymbol::kind());
    // `StatValue::Number` is a bare-integer `literal` (like `Count::Literal`) —
    // registered so the literal reader splices a bare numeral at a stat slot.
    kinds.add(crate::StatValue::kind());
    // Change-bundling macros (`PowerAndToughnessUp`/`Down`, …) expand at
    // `changes: [...]` positions to a `Several` bundle, flattened away before
    // the engine.
    kinds.add(crate::Modification::kind());
    kinds.add(crate::Quantity::kind());
    kinds.add(crate::Reference::kind());
    kinds.add(crate::Replacement::kind());
    kinds.add(crate::Selection::kind());
    kinds.add(crate::StaticEffect::kind());
    kinds.add(crate::TargetSpec::kind());
    // NOTE: core's registry also carries the play-policy `strategy::Preference`
    // kind. It is absent here deliberately: engine strategy RON is authored
    // directly in core terms through plain serde and sits OUTSIDE the authoring
    // program (docs/decisions/authoring-spelling-lowering.md §3 and the §4
    // container table). No macro definition in any plugin invokes it.
    kinds.add(Kind::new("CardFace"));
    kinds.add(Kind::new("Subtype"));
    // Type-kind macros (the ten builtin `Artifact`..`Sorcery` defs) expand to
    // a `TypeDef` decl in the plugin loader; name-erasing like `Subtype`.
    kinds.add(Kind::new("TypeDef"));
    // Counter-kind macros (`P1P1Counter`, …) expand to a `Counter` decl in the
    // plugin loader; name-erasing like `Subtype`. No card position reads it.
    kinds.add(Kind::new("Counter"));
    // Designation-kind macros (`Monarch`, …) expand to a `DesignationDecl`
    // in the plugin loader; name-erasing like `Counter`. No card position
    // reads it — cards reference designations by bare `Ident`.
    kinds.add(Kind::new("DesignationDecl"));
    // Meta-macro positions: `MacroDef` reads in the plugin loader (serde name
    // "Macro"). No card position ever reads it; registering it keeps one kind
    // registry. Name-erasing like the other struct kinds.
    kinds.add(Kind::new("Macro"));
    // Keyword-action verb macros (`Destroy`, `Mill`, `Draw`, `Scry`, …) also
    // carry this grouping kind so the plugin loader collects them into a verb
    // side-table (name + param shape + canonical body). They are invoked at
    // `OneShotEffect` positions like any effect macro — this kind opens no card
    // position of its own, it is a name-erasing loader tag like `TypeDef`.
    kinds.add(Kind::new("KeywordAction"));
    kinds
}

/// The raw `ron::Options` everything is read and written with.
///
/// As default extensions these need no `#![enable(...)]` header:
/// `implicit_some` keeps `Option` fields flat, and `unwrap_variant_newtypes`
/// is what lets files spell a struct-carrying variant flat —
/// `Normal(name: ..., ...)` instead of `Normal((name: ...))`.
///
/// This is the bare options *value* — use it where an `ron::Options` itself is
/// needed (the macro-layer reader's base options, the migrations writer). For
/// reading, prefer [`options`], whose `from_str` is literal-aware.
#[must_use]
pub fn raw_options() -> ron::Options {
    ron::Options::default().with_default_extension(
        ron::extensions::Extensions::IMPLICIT_SOME
            | ron::extensions::Extensions::UNWRAP_VARIANT_NEWTYPES,
    )
}

/// A literal-aware reader: an otherwise-empty macro layer that knows the
/// `#[macro_ron(literal)]` kinds, so a bare numeral (`3`) reads as
/// `Count::Literal(3)`. Only types with a `literal` variant need registering;
/// every other position falls through to plain enum dispatch (with no macros,
/// this is exactly the raw-`ron` read plus the bare-numeral splice).
static LITERAL_READER: LazyLock<MacroSet> =
    LazyLock::new(|| MacroSet::new(kinds()).with_options(raw_options()));

/// The reader/writer facade every RON read and write goes through. Reads accept
/// bare numerals at `literal` positions; writes go through the derive, which
/// serializes literals bare. Method-compatible with the `ron::Options` calls it
/// replaced (`from_str`, `to_string`), so call sites are unchanged.
#[must_use]
pub fn options() -> RonOptions {
    RonOptions
}

/// The facade returned by [`options`].
pub struct RonOptions;

impl RonOptions {
    /// Read `T` from RON, accepting a bare numeral (`3`) at a `literal`
    /// position.
    ///
    /// # Errors
    ///
    /// RON syntax errors, and unknown names / malformed values per
    /// [`MacroSet::read_str`].
    pub fn from_str<T: DeserializeOwned>(&self, source: &str) -> ron::error::SpannedResult<T> {
        LITERAL_READER.read_str(source)
    }

    /// Write `value` to RON (literals serialize bare via the derive).
    ///
    /// # Errors
    ///
    /// Propagates the underlying `ron::Error`.
    pub fn to_string<T: Serialize>(&self, value: &T) -> Result<String, ron::Error> {
        raw_options().to_string(value)
    }
}
