use std::sync::Arc;

use serde::Deserialize;
use serde::Serialize;

use crate::Count;
use crate::EventFilter;
use crate::Expand;
use crate::Expansion;
use crate::Predicate;
use crate::Reference;
use crate::SupportsMacros;

/// A numeric comparison ([CR#107.3]). The named forms keep RON readable —
/// `AtLeast` rather than `>=`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Expand, Serialize)]
pub enum Cmp {
    Eq,
    AtLeast,
    AtMost,
    Greater,
    Less,
}

impl Cmp {
    /// Does `lhs <op> rhs` hold? The single comparator table every numeric
    /// test routes through — `Condition::Compare`'s two evaluated counts and
    /// `CountBound::satisfied_by`'s matched-set cardinality alike.
    #[must_use]
    pub fn apply(self, lhs: crate::Uint, rhs: crate::Uint) -> bool {
        match self {
            Cmp::Eq => lhs == rhs,
            Cmp::AtLeast => lhs >= rhs,
            Cmp::AtMost => lhs <= rhs,
            Cmp::Greater => lhs > rhs,
            Cmp::Less => lhs < rhs,
        }
    }
}

use crate::Lookback;

/// A truth-valued test the engine evaluates ([CR#603.4] intervening-if,
/// [CR#118.12a] "unless", ability words). Ability words (`Threshold`,
/// `Delirium`, `Morbid`) are declared `Condition` macros — unknown names at
/// Condition positions fall through to the macro layer.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back, and the `Happened` struct variant reads flat
/// in RON through a generated helper struct + `unwrap_variant_newtypes`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Condition {
    /// Compare two scalar counts ([CR#107.1]).
    Compare(Count, Cmp, Count),
    /// At least one object matches ([CR#603.4], "if you control a …").
    Exists(Predicate),
    /// A referenced object matches a predicate ([CR#603.4], "if it is a …").
    /// Idris `Matches`.
    Matches(Reference, Predicate),
    /// The referenced object has marked damage from at least one source whose
    /// deal-time abilities match the predicate ([CR#704.5h]).
    DealtDamageBy(Reference, Predicate),
    /// The referenced attachment is LEGALLY attached ([CR#701.3b,303.4d]): it
    /// has a host AND that (attachment, host) pair passes the attachment
    /// legality predicate (host-type / protection / `Cant(Attach)`). False when
    /// the object is unattached, attached to an illegal host, or self-attached
    /// — the exact "or is not attached / attached to an illegal object" trigger
    /// of the Aura graveyard SBA ([CR#704.5m]), whose static is
    /// `Sba(Not(LegallyAttached(Ref(This))), Move(Ref(This), Graveyard))`. The
    /// engine evaluates it through the one `attachment_legal` predicate (the
    /// same one the [CR#701.3b] attach no-op uses), never by subtype.
    LegallyAttached(Reference),
    /// An event happened within a window (morbid/raid, [CR#608.2i]).
    ///
    /// `event` is boxed: unboxed it made `Happened` a ~359 B outlier that set
    /// `Condition`'s whole size; the box drops the variant to ~16 B. serde
    /// treats `Arc<T>` transparently, so the RON reads flat (`Happened(event:
    /// …, within: …)`) unchanged — build one via [`Condition::happened`]
    /// rather than the struct literal. See `engine-event-size-boxing`.
    Happened {
        event: Arc<EventFilter>,
        within: Lookback,
    },
    /// The watched `value` was below a threshold before the triggering
    /// occurrence and became at least it after — [CR#714.2b]'s "the number of
    /// lore counters on it was less than N and became at least N", verbatim: a
    /// chapter ability's intervening-if. `value` NAMES the crossing quantity
    /// (a saga's lore total, `CounterCount(This, LoreCounter)`) for the
    /// checker to tie to the trigger's counter event; the engine reads the
    /// fired FACT's `before`/`after` channel, never a recomputation — a
    /// doubled 0→2 placement is one fact whose crossing both chapter I and
    /// chapter II observe.
    ///
    /// `thresholds` holds ONE OR MORE chapter numbers: a range
    /// `{rN1}, {rN2}—[Effect]` ([CR#714.2c] — the same effect at each listed
    /// chapter) is one condition whose crossing fires if the fact carried the
    /// count across ANY of them. Each threshold is a plain [`Count`] — crossing
    /// is inherently "became AT LEAST N" ([CR#714.2b]), so no comparator is
    /// stored. (Per-crossed-member firing when a single doubled batch crosses
    /// two members of one range at once is engine-sagas follow-up; normal
    /// one-at-a-time play fires each member on its own placement event.)
    Crossed {
        value: Count,
        thresholds: Arc<[Count]>,
    },
    /// The tagged optional cost ([`OptionalCost`](crate::OptionalCost)) was
    /// paid for this object — "if it was kicked" ([CR#702.33d]; buyback's
    /// "if the buyback cost was paid", [CR#702.27a]). The linked-ability read
    /// ([CR#702.33e,607.2]): the tag names the declaring `CostOption` on the
    /// same object. Replaces the bespoke `WasKicked` flag.
    PaidCost(crate::CostTag),
    /// "if its [keyword] cost was paid" — the alt-cost read, gating a rider
    /// on the alt base cost used to cast the resolving/source object
    /// ([CR#702.34a,702.74a]). The alt-cost twin of `PaidCost` (which reads
    /// optional/additional costs). Idris `WasCastWith`.
    CastWith(crate::CostTag),
    /// It is the evaluating player's turn (the `you` of the evaluation
    /// context — an ability's controller). Sugar for `TurnOf(Ref(You))`, kept
    /// as the common, frame-robust specialization.
    YourTurn,
    /// It is a matching player's turn ([CR#603.4]) — the active player
    /// satisfies the player predicate. Generalizes
    /// [`YourTurn`](Condition::YourTurn) (which is `TurnOf(Ref(You))`):
    /// "during an opponent's turn" is `TurnOf(OpponentOf(Ref(You)))`. The
    /// `Predicate` is a player predicate (`Ref(You)`, `OpponentOf(Ref(You))`,
    /// `Kind(Player)`, …).
    TurnOf(Predicate),
    /// The current phase/step is exactly the given one. Main phases are
    /// single-step bare variants, so `DuringPhase(PrecombatMain)` works
    /// today; phase-class matching (any combat step) accretes when a card
    /// needs it.
    DuringPhase(crate::PhaseStep),
    /// All sub-conditions hold.
    And(Arc<[Condition]>),
    /// At least one sub-condition holds.
    Or(Arc<[Condition]>),
    /// The sub-condition does not hold.
    Not(Arc<Condition>),
    /// A remembered `Condition` macro invocation (ability words: `Threshold`,
    /// `Delirium`, `Morbid`). Serialized as the invocation, not the struct.
    #[macro_ron(expanded)]
    Expanded(Expansion<Condition>),
}

impl Condition {
    /// Construct [`Condition::Happened`], boxing the fat `event` field, so call
    /// sites build `Condition::happened(event, within)` rather than boxing by
    /// hand — the counterpart of [`Ability`](crate::Ability)'s boxing
    /// constructors.
    #[must_use]
    pub fn happened(event: EventFilter, within: Lookback) -> Self {
        Condition::Happened {
            event: Arc::new(event),
            within,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    type SemValue = Count;

    fn read(source: &str) -> Condition {
        crate::ron::options().from_str(source).unwrap()
    }

    #[test]
    fn compare_reads() {
        assert_eq!(
            read("Compare(X, AtLeast, Literal(3))"),
            Condition::Compare(SemValue::X, Cmp::AtLeast, Count::Literal(3)),
        );
    }

    /// A chapter's crossing gate ([CR#714.2b]) holds ONE OR MORE thresholds:
    /// a range `{rN1}, {rN2}—[Effect]` ([CR#714.2c]) fires at each listed
    /// chapter number. Reads the bare-numeral `thresholds` list and
    /// round-trips.
    #[test]
    fn crossed_reads_plural_thresholds() {
        let v = read("Crossed(value: CounterCount(This, LoreCounter), thresholds: [2, 3])");
        let Condition::Crossed { thresholds, .. } = &v else {
            panic!("expected a Crossed condition");
        };
        assert_eq!(
            thresholds,
            &Arc::<[Count]>::from([Count::Literal(2), Count::Literal(3)])
        );
        let written = crate::ron::options().to_string(&v).unwrap();
        assert_eq!(read(&written), v, "round-trips");
    }

    /// A single chapter is a one-element `thresholds` list ([CR#714.2b]).
    #[test]
    fn crossed_reads_single_threshold() {
        let v = read("Crossed(value: CounterCount(This, LoreCounter), thresholds: [1])");
        let Condition::Crossed { thresholds, .. } = &v else {
            panic!("expected a Crossed condition");
        };
        assert_eq!(thresholds, &Arc::<[Count]>::from([Count::Literal(1)]));
    }

    #[test]
    fn your_turn_reads() {
        assert_eq!(read("YourTurn"), Condition::YourTurn);
    }

    /// `TurnOf(<player predicate>)` reads flat and round-trips; it carries the
    /// player filter `YourTurn` leaves implicit ([CR#603.4]).
    #[test]
    fn turn_of_reads_and_round_trips() {
        assert_eq!(
            read("TurnOf(Ref(You))"),
            Condition::TurnOf(Predicate::Ref(Reference::You)),
        );
        // "during an opponent's turn".
        let opp = read("TurnOf(OpponentOf(Ref(You)))");
        assert_eq!(
            opp,
            Condition::TurnOf(Predicate::Relation(crate::RelationPredicate::OpponentOf(
                Arc::new(Predicate::Ref(Reference::You))
            ))),
        );
        let written = crate::ron::options().to_string(&opp).unwrap();
        assert_eq!(read(&written), opp);
    }

    #[test]
    fn during_phase_reads() {
        assert_eq!(
            read("DuringPhase(PostcombatMain)"),
            Condition::DuringPhase(crate::PhaseStep::PostcombatMain),
        );
    }

    /// `LegallyAttached(This)` reads and round-trips ([CR#704.5m] trigger).
    #[test]
    fn legally_attached_reads() {
        assert_eq!(
            read("LegallyAttached(This)"),
            Condition::LegallyAttached(Reference::This),
        );
        let v = Condition::LegallyAttached(Reference::This);
        let w = crate::ron::options().to_string(&v).unwrap();
        assert_eq!(read(&w), v);
    }

    /// `PaidCost(tag)` — the paid-optional-cost read ("if it was kicked",
    /// [CR#702.33d]) — reads a bare-ident tag and round-trips.
    #[test]
    fn paid_cost_reads_and_round_trips() {
        let v = read("PaidCost(Kicker)");
        assert_eq!(v, Condition::PaidCost(crate::CostTag::from("Kicker")));
        let written = crate::ron::options().to_string(&v).unwrap();
        assert_eq!(written, "PaidCost(Kicker)");
        assert_eq!(read(&written), v);
    }

    /// `CastWith(tag)` — the alt-cost read ("if its flashback cost was
    /// paid", [CR#702.34a,702.74a]) — reads a bare-ident tag and
    /// round-trips.
    #[test]
    fn cast_with_reads_and_round_trips() {
        let v = read("CastWith(Flashback)");
        assert_eq!(v, Condition::CastWith(crate::CostTag::from("Flashback")));
        let written = crate::ron::options().to_string(&v).unwrap();
        assert_eq!(written, "CastWith(Flashback)");
        assert_eq!(read(&written), v);
    }

    #[test]
    fn happened_reads() {
        use crate::Cause;
        use crate::CausePattern;
        use crate::VerbName;
        use crate::Zone;

        assert_eq!(
            read(
                "Happened(event: ZoneChange(cause: Cause(verb: Sacrifice), from: Battlefield, to: Graveyard), within: ThisTurn)"
            ),
            Condition::happened(
                EventFilter::ZoneChange {
                    what: Predicate::Any,
                    from: Some(Zone::Battlefield),
                    to: Some(Zone::Graveyard),
                    cause: Some(Cause::Cause(CausePattern {
                        verb: Some(VerbName::from("Sacrifice")),
                        agency: None,
                        agent: None,
                    })),
                },
                Lookback::ThisTurn,
            ),
        );
    }

    /// The grant's sickness condition spells its subject BARE (`This`), not
    /// `Ref(This)`: `Matches`'s first slot is a `Reference` ([CR#302.6]).
    #[test]
    fn matches_summoning_sick_reads_with_bare_this() {
        let v = read("Matches(This, SummoningSick)");
        assert_eq!(
            v,
            Condition::Matches(
                Reference::This,
                Predicate::State(crate::StatePredicate::SummoningSick),
            ),
        );
        let written = crate::ron::options().to_string(&v).unwrap();
        assert_eq!(read(&written), v);
    }
}
