use std::sync::Arc;

use crate::Expansion;
use crate::Predicate;
use crate::Quantity;
use crate::SupportsMacros;

/// One entry in an ability's announce list ([CR#601.2c,115]). A `TargetSpec`
/// is the only place "target" lives, and the announce list is an INDEXED
/// channel: the body names this entry BY POSITION — as
/// [`Reference::Target(n)`](crate::Reference::Target) (singular) or
/// [`Selection::Targets(n)`](crate::Selection::Targets) (the slot's whole
/// group), where `n` is this spec's index. Rechecked at resolution
/// ([CR#608.2b]).
///
/// A target pushes NO antecedent: `It`/`That(Sort)`/`They`/`Them` resolve over
/// the antecedent stack (loop elements, binder choices, move/create products)
/// and can never name a target. A target is not something a clause produced
/// and then referred back to — it is announced at index `n` and read at index
/// `n`, so two same-sort slots (the fight family) need no labelling and admit
/// no ambiguity.
///
/// Separated from [`crate::Selection`] so that resolution-time choices
/// (`Each`, `Choose`, …) and announce-time targets never share a position —
/// targeting has legality recheck and retargeting rules that the other
/// choice forms don't.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum TargetSpec {
    /// A quantity of targets matching the filter ([CR#115.1,115.6,601.2c]).
    /// Use `Quantity::one()` for a single target, `Quantity::Range(None,
    /// Some(n))` for "up to N", and `Quantity::Range(None, None)` for "any
    /// number of targets" (or the `Exactly`/`AtMost`/`AnyNumber` macros at the
    /// RON surface).
    Target(Quantity, Predicate),
    /// A co-target set-distinctness constraint ([CR#115.7e], Arc Trail's
    /// "any *other* target"): this spec's final picks must not overlap the
    /// sibling specs at the given indices. Evaluated on the FINAL target
    /// set — retargeting may swap members; only the whole set is checked,
    /// at announce and at the [CR#608.2b] re-check. Never a fixed-binding
    /// exclusion (that is `And([…, Not(Ref(…))])` inside the filter).
    Distinct(Arc<[usize]>, Arc<TargetSpec>),
    /// A remembered `TargetSpec` macro invocation.
    #[macro_ron(expanded)]
    Expanded(Expansion<TargetSpec>),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CharacteristicPredicate;
    use crate::Count;
    use crate::Quantity;
    use crate::Supertype;

    fn read(source: &str) -> TargetSpec {
        crate::ron::options().from_str(source).unwrap()
    }

    fn basic_filter() -> Predicate {
        Predicate::Characteristic(CharacteristicPredicate::Supertype(Supertype::Basic))
    }

    /// The announce-list grammar: `Target(Quantity, Predicate)`, distinct from
    /// `Selection`'s resolution choices. This unit fixture has no macro set, so
    /// it spells the underlying `Range` primitive directly (the named
    /// `Exactly`/`AtMost`/`AnyNumber` forms are exercised at the cards layer,
    /// where the builtin macros are loaded).
    #[test]
    fn announce_forms_read() {
        assert_eq!(
            read("Target(Range(1, 1), Supertype(Basic))"),
            TargetSpec::Target(Quantity::one(), basic_filter()),
        );
        assert_eq!(
            read("Target(Range(None, 2), Supertype(Basic))"),
            TargetSpec::Target(
                Quantity::Range(None, Some(Count::Literal(2))),
                basic_filter(),
            ),
        );
        assert_eq!(
            read("Target(Range(None, None), Supertype(Basic))"),
            TargetSpec::Target(Quantity::Range(None, None), basic_filter()),
        );
    }

    /// Pins the derived `Serialize` round-trip — serialize → read is identity.
    #[test]
    fn target_round_trips() {
        for value in [
            TargetSpec::Target(Quantity::one(), basic_filter()),
            TargetSpec::Target(Quantity::Range(None, None), basic_filter()),
            TargetSpec::Target(
                Quantity::Range(None, Some(Count::Literal(2))),
                basic_filter(),
            ),
        ] {
            let written = crate::ron::options().to_string(&value).unwrap();
            assert_eq!(read(&written), value, "round-trip failed for {value:?}");
        }
    }
}
