[package]
publish = false
name = "deckmaste_tui"
version = "0.1.0"
edition = "2024"

[features]
slow-tests = []

[lints]
workspace = true

[dependencies]
deckmaste_card = { version = "0.1.0", path = "../deckmaste_card" }
deckmaste_core = { version = "0.1.0", path = "../deckmaste_core" }
deckmaste_semantics = { version = "0.1.0", path = "../deckmaste_semantics" }
deckmaste_plugin = { version = "0.1.0", path = "../deckmaste_plugin" }
deckmaste_legacy_render = { version = "0.1.0", path = "../deckmaste_legacy_render" }
deckmaste_engine = { version = "0.1.0", path = "../deckmaste_engine" }
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
ratatui = "0.29"
