//! Runtime support for `#[derive(SupportsMacros)]`: the trait generated
//! impls implement, compile-time variant-list concatenation, and the seq
//! visitors tuple variants read through.

use std::marker::PhantomData;

use serde::de::Deserialize;
use serde::de::DeserializeOwned;
use serde::de::SeqAccess;
use serde::de::VariantAccess;
use serde::de::Visitor;
use serde::de::{self};

use crate::Expansion;
use crate::Kind;

/// A macroable grammar enum: generated by `#[derive(SupportsMacros)]`.
///
/// `ALL_VARIANTS` is the *dispatch* set — every identifier
/// [`from_variant`](Self::from_variant) can construct from: the type's own
/// tagged variant names, plus (transitively) the names a `flatten`
/// compartment or an `embed`ded type accepts. Note the type's own
/// `deserialize_enum` call does NOT pass the embedded type's names (a
/// private list omits them) so the macro layer's `embeds_untagged` hook
/// still routes unknown identifiers to `visit_newtype_struct` — but a
/// *parent* that flattens this type consults `ALL_VARIANTS`, because from
/// the parent's dispatch the embed resolves natively.
///
/// The `DeserializeOwned` supertrait makes explicit what the derive already
/// emits — every macroable type carries a generated `Deserialize` impl — so
/// code generic over the trait can deserialize a value of `Self`. The
/// param-type validators (`read_str::<T>`) are exactly such code.
pub trait SupportsMacros: DeserializeOwned {
    /// This type's own tagged variant names (a name-erased `embed`
    /// newtype variant is not listed).
    const OWN_VARIANTS: &'static [&'static str];
    /// The full dispatch set — see the trait docs.
    const ALL_VARIANTS: &'static [&'static str];

    /// The kind facts for macro-layer registration: `remembers_expansion`
    /// ⇔ an `expanded` variant, `embeds_untagged` ⇔ an `embed` variant,
    /// `literal_wrapper` ⇔ a `literal` variant.
    fn kind() -> Kind;

    /// Builds a value from an already-read variant tag and its access.
    /// `None` means the identifier is not in
    /// [`ALL_VARIANTS`](Self::ALL_VARIANTS) — callers must check membership
    /// *before* calling when they need to fall through, since `access` is
    /// consumed.
    fn from_variant<'de, A: VariantAccess<'de>>(
        ident: &str,
        access: A,
    ) -> Option<Result<Self, A::Error>>;

    /// Creates the remembered form: `Some(Self::Expanded(e))` when the type
    /// carries an `expanded` variant, `None` otherwise (e.g. `Action`).
    fn expanded(e: Expansion<Self>) -> Option<Self>;

    /// This type's own variants' signatures, keyed by name (see
    /// [`OWN_VARIANTS`](Self::OWN_VARIANTS)).
    const OWN_SIGNATURES: &'static [(&'static str, VariantSignature)];
    /// The full transitive signature lookup — see
    /// [`ALL_VARIANTS`](Self::ALL_VARIANTS) for the same concatenation over
    /// names. May carry entries for names a `flatten exclude(...)` drops
    /// from dispatch; a name that never dispatches is never looked up here.
    const ALL_SIGNATURES: &'static [(&'static str, VariantSignature)];
}

/// Concatenates variant-name lists at compile time. `N` must equal the
/// total length (generated code computes it from the source lists' `len()`s;
/// a mismatch fails const evaluation). An over-large `N` trips the
/// `assert!` at the end; an under-large `N` fails const evaluation with an
/// out-of-bounds index write — both are compile errors at the generated call
/// sites.
///
/// # Panics
///
/// If `N` does not equal the summed list lengths — in const context that's
/// a compile error, not a runtime panic.
#[must_use]
pub const fn concat_variants<const N: usize>(
    lists: &[&'static [&'static str]],
) -> [&'static str; N] {
    let mut out = [""; N];
    let mut i = 0;
    let mut l = 0;
    while l < lists.len() {
        let list = lists[l];
        let mut j = 0;
        while j < list.len() {
            out[i] = list[j];
            i += 1;
            j += 1;
        }
        l += 1;
    }
    assert!(
        i == N,
        "concat_variants: N must equal the summed list lengths"
    );
    out
}

/// Whether a parameter may be omitted, and with what.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParamDefault {
    /// No default — the argument must be supplied.
    Required,
    /// A default exists but has no RON rendering (`#[serde(default)]`,
    /// `#[serde(default = "path")]`). Dropping the parameter from a scaffold
    /// would break the LONG spelling that supplies it, and requiring it would
    /// break the SHORT one that doesn't; a scaffolding consumer that needs
    /// both to round-trip declares the param `Elidable(...)`, which forwards
    /// a supplied argument and drops the body entry when there isn't one.
    Implicit,
    /// RON-renderable source text, from `#[macro_ron(default = ...)]`.
    Expr(&'static str),
}

/// One named parameter of a struct-shaped variant.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NamedParam {
    pub name: &'static str,
    pub default: ParamDefault,
}

/// A named struct whose fields a newtype variant splices into its own call:
/// `#[derive(MacroFields)]`.
///
/// A newtype-tuple variant over a named struct reads FLAT in RON — ron's
/// `unwrap_variant_newtypes` extension spells it `Activated(cost: …, effect:
/// …)`, never `Activated((cost: …))` — so its AUTHORED shape is the payload
/// struct's field list, not one opaque positional slot. Those fields belong
/// to another type entirely, which `#[derive(SupportsMacros)]` on the enum
/// cannot see; the payload derives this trait, and the enum's
/// `#[macro_ron(spliced)]` variant reads them back out through it to report a
/// [`VariantSignature::Named`].
pub trait MacroFields {
    /// The struct's fields in declaration order, under their RON names.
    const FIELDS: &'static [NamedParam];
}

/// A variant's authored shape — what an identity macro must mirror.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VariantSignature {
    Unit,
    /// One entry per position; arity is the slice length.
    Positional(&'static [ParamDefault]),
    Named(&'static [NamedParam]),
}

/// Concatenates variant-signature lists at compile time, mirroring
/// [`concat_variants`] exactly (same seed-and-copy shape, hence
/// `VariantSignature` must be `Copy`). `N` must equal the total length.
///
/// # Panics
///
/// If `N` does not equal the summed list lengths — in const context that's
/// a compile error, not a runtime panic.
#[must_use]
pub const fn concat_signatures<const N: usize>(
    lists: &[&'static [(&'static str, VariantSignature)]],
) -> [(&'static str, VariantSignature); N] {
    let mut out = [("", VariantSignature::Unit); N];
    let mut i = 0;
    let mut l = 0;
    while l < lists.len() {
        let list = lists[l];
        let mut j = 0;
        while j < list.len() {
            out[i] = list[j];
            i += 1;
            j += 1;
        }
        l += 1;
    }
    assert!(
        i == N,
        "concat_signatures: N must equal the summed list lengths"
    );
    out
}

/// `const`-context string equality (`str`'s `PartialEq` is not `const`).
const fn str_eq(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        if a[i] != b[i] {
            return false;
        }
        i += 1;
    }
    true
}

/// Whether `name` appears in `exclude` (a `#[macro_ron(flatten, exclude(...))]`
/// list), in `const` context.
const fn is_excluded(name: &str, exclude: &[&str]) -> bool {
    let mut i = 0;
    while i < exclude.len() {
        if str_eq(name, exclude[i]) {
            return true;
        }
        i += 1;
    }
    false
}

/// Counts the entries across `lists` NOT in `exclude` — the length a
/// [`concat_variants_excluding`] call yields for those tail lists. Generated
/// code uses it to compute the const-generic `N`.
#[must_use]
pub const fn count_kept(lists: &[&[&'static str]], exclude: &[&'static str]) -> usize {
    let mut n = 0;
    let mut l = 0;
    while l < lists.len() {
        let list = lists[l];
        let mut j = 0;
        while j < list.len() {
            if !is_excluded(list[j], exclude) {
                n += 1;
            }
            j += 1;
        }
        l += 1;
    }
    n
}

/// Like [`concat_variants`] but for a `flatten` with `exclude(...)`: `keep`
/// (the parent's OWN names) is copied verbatim, then each `filtered` tail
/// list's entries are appended EXCEPT those in `exclude`. `N` must equal
/// `keep.len() + count_kept(filtered, exclude)` (an out-of-bounds write or the
/// trailing `assert!` catches a mismatch at compile time).
///
/// # Panics
///
/// If `N` does not equal the kept length — a compile error in const context.
#[must_use]
pub const fn concat_variants_excluding<const N: usize>(
    keep: &'static [&'static str],
    filtered: &[&'static [&'static str]],
    exclude: &[&'static str],
) -> [&'static str; N] {
    let mut out = [""; N];
    let mut i = 0;
    let mut k = 0;
    while k < keep.len() {
        out[i] = keep[k];
        i += 1;
        k += 1;
    }
    let mut l = 0;
    while l < filtered.len() {
        let list = filtered[l];
        let mut j = 0;
        while j < list.len() {
            if !is_excluded(list[j], exclude) {
                out[i] = list[j];
                i += 1;
            }
            j += 1;
        }
        l += 1;
    }
    assert!(
        i == N,
        "concat_variants_excluding: N must equal keep.len() + count_kept(filtered, exclude)"
    );
    out
}

/// Seq visitor for 2-field tuple variants used by generated `SupportsMacros`
/// impls.
pub struct Pair<A, B>(PhantomData<(A, B)>);

impl<A, B> Pair<A, B> {
    #[must_use]
    pub fn new() -> Self {
        Pair(PhantomData)
    }
}

impl<A, B> Default for Pair<A, B> {
    fn default() -> Self {
        Self::new()
    }
}

impl<'de, A: Deserialize<'de>, B: Deserialize<'de>> Visitor<'de> for Pair<A, B> {
    type Value = (A, B);

    fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str("a 2-element tuple variant")
    }

    fn visit_seq<S: SeqAccess<'de>>(self, mut seq: S) -> Result<Self::Value, S::Error> {
        let a = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(0, &self))?;
        let b = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(1, &self))?;
        Ok((a, b))
    }
}

/// Seq visitor for a 2-field tuple variant whose LAST field is defaulted:
/// reads one required element then an optional second, falling back to the
/// `default_b` value the generated code supplies when the second is absent.
/// Backs a non-embed tuple variant with one required + one trailing
/// `#[macro_ron(default = "…")]` field (e.g. `Cast(A, b)` with `b` defaulting)
/// — the short form `Cast(a)` reads here (indistinguishable in RON from a
/// newtype spelling, so it needs this runtime visitor rather than the static
/// [`Pair`] layout), the long form `Cast(a, b)` supplies the second.
pub struct SinglePlusDefault<A, B> {
    default_b: B,
    _p: PhantomData<A>,
}

impl<A, B> SinglePlusDefault<A, B> {
    #[must_use]
    pub fn new(default_b: B) -> Self {
        SinglePlusDefault {
            default_b,
            _p: PhantomData,
        }
    }
}

impl<'de, A, B> Visitor<'de> for SinglePlusDefault<A, B>
where
    A: Deserialize<'de>,
    B: Deserialize<'de>,
{
    type Value = (A, B);

    fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str("a 1- or 2-element tuple variant")
    }

    fn visit_seq<S: SeqAccess<'de>>(self, mut seq: S) -> Result<Self::Value, S::Error> {
        let a = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(0, &self))?;
        let b = seq.next_element()?.unwrap_or(self.default_b);
        Ok((a, b))
    }
}

/// Seq visitor for a 3-field tuple variant whose LAST field is defaulted:
/// reads two required elements then an optional third, falling back to the
/// `default_c` value the generated code supplies when the third is absent.
/// Backs a non-embed tuple variant with one trailing `#[macro_ron(default =
/// "…")]` field (e.g. `Verb(A, B, c)` with `c` defaulting) — the short form
/// `Verb(a, b)` reads here, the long form `Verb(a, b, c)` supplies the third.
pub struct PairPlusDefault<A, B, C> {
    default_c: C,
    _p: PhantomData<(A, B)>,
}

impl<A, B, C> PairPlusDefault<A, B, C> {
    #[must_use]
    pub fn new(default_c: C) -> Self {
        PairPlusDefault {
            default_c,
            _p: PhantomData,
        }
    }
}

impl<'de, A, B, C> Visitor<'de> for PairPlusDefault<A, B, C>
where
    A: Deserialize<'de>,
    B: Deserialize<'de>,
    C: Deserialize<'de>,
{
    type Value = (A, B, C);

    fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str("a 2- or 3-element tuple variant")
    }

    fn visit_seq<S: SeqAccess<'de>>(self, mut seq: S) -> Result<Self::Value, S::Error> {
        let a = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(0, &self))?;
        let b = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(1, &self))?;
        let c = seq.next_element()?.unwrap_or(self.default_c);
        Ok((a, b, c))
    }
}

/// Seq visitor for a 4-field tuple variant whose LAST TWO fields are
/// defaulted: reads two required elements then up to two more, each absent
/// trailing element falling back to the `default_c`/`default_d` value the
/// generated code supplies. Backs a non-embed tuple variant with two
/// trailing `#[macro_ron(default = "…")]` fields (e.g. `Verb(A, B, c, d)`
/// with `c`/`d` defaulting) — `Verb(a, b)` reads here filling both, `Verb(a,
/// b, c)` fills only `d`, `Verb(a, b, c, d)` supplies every field. Mirrors
/// [`PairPlusDefault`] one default field further.
pub struct PairPlusTwoDefaults<A, B, C, D> {
    default_c: C,
    default_d: D,
    _p: PhantomData<(A, B)>,
}

impl<A, B, C, D> PairPlusTwoDefaults<A, B, C, D> {
    #[must_use]
    pub fn new(default_c: C, default_d: D) -> Self {
        PairPlusTwoDefaults {
            default_c,
            default_d,
            _p: PhantomData,
        }
    }
}

impl<'de, A, B, C, D> Visitor<'de> for PairPlusTwoDefaults<A, B, C, D>
where
    A: Deserialize<'de>,
    B: Deserialize<'de>,
    C: Deserialize<'de>,
    D: Deserialize<'de>,
{
    type Value = (A, B, C, D);

    fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str("a 2-, 3-, or 4-element tuple variant")
    }

    fn visit_seq<S: SeqAccess<'de>>(self, mut seq: S) -> Result<Self::Value, S::Error> {
        let a = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(0, &self))?;
        let b = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(1, &self))?;
        let c = seq.next_element()?.unwrap_or(self.default_c);
        let d = seq.next_element()?.unwrap_or(self.default_d);
        Ok((a, b, c, d))
    }
}

/// Seq visitor for 3-field tuple variants.
pub struct Triple<A, B, C>(PhantomData<(A, B, C)>);

impl<A, B, C> Triple<A, B, C> {
    #[must_use]
    pub fn new() -> Self {
        Triple(PhantomData)
    }
}

impl<A, B, C> Default for Triple<A, B, C> {
    fn default() -> Self {
        Self::new()
    }
}

impl<'de, A, B, C> Visitor<'de> for Triple<A, B, C>
where
    A: Deserialize<'de>,
    B: Deserialize<'de>,
    C: Deserialize<'de>,
{
    type Value = (A, B, C);

    fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str("a 3-element tuple variant")
    }

    fn visit_seq<S: SeqAccess<'de>>(self, mut seq: S) -> Result<Self::Value, S::Error> {
        let a = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(0, &self))?;
        let b = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(1, &self))?;
        let c = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(2, &self))?;
        Ok((a, b, c))
    }
}
