//! Runtime support for `#[derive(SupportsMacros)]`: the trait generated
//! impls implement, compile-time variant-list concatenation, and the seq
//! visitors tuple variants read through.

use std::marker::PhantomData;

use serde::de::{self, Deserialize, SeqAccess, VariantAccess, Visitor};

use crate::{Expansion, Kind};

/// A macroable grammar enum: generated by `#[derive(SupportsMacros)]`.
///
/// `ALL_VARIANTS` is the *dispatch* set — every identifier
/// [`from_variant`](Self::from_variant) can construct from: the type's own
/// tagged variant names, plus (transitively) the names a `flatten`
/// compartment or an `embed`ded type accepts. Note the type's own
/// `deserialize_enum` call does NOT pass the embedded type's names (a
/// private list omits them) so the macro layer's `embeds_untagged` hook
/// still routes unknown identifiers to `visit_newtype_struct` — but a
/// *parent* that flattens this type consults `ALL_VARIANTS`, because from
/// the parent's dispatch the embed resolves natively.
pub trait SupportsMacros: Sized {
    /// This type's own tagged variant names (an `embed` newtype variant
    /// like `Selection::Ref` is name-erased and not listed).
    const OWN_VARIANTS: &'static [&'static str];
    /// The full dispatch set — see the trait docs.
    const ALL_VARIANTS: &'static [&'static str];

    /// The kind facts for macro-layer registration: `remembers_expansion`
    /// ⇔ an `expanded` variant, `embeds_untagged` ⇔ an `embed` variant,
    /// `literal_wrapper` ⇔ a `literal` variant.
    fn kind() -> Kind;

    /// Builds a value from an already-read variant tag and its access.
    /// `None` means the identifier is not in
    /// [`ALL_VARIANTS`](Self::ALL_VARIANTS) — callers must check membership
    /// *before* calling when they need to fall through, since `access` is
    /// consumed.
    fn from_variant<'de, A: VariantAccess<'de>>(
        ident: &str,
        access: A,
    ) -> Option<Result<Self, A::Error>>;

    /// Creates the remembered form: `Some(Self::Expanded(e))` when the type
    /// carries an `expanded` variant, `None` otherwise (e.g. `Action`).
    fn expanded(e: Expansion<Self>) -> Option<Self>;
}

/// Concatenates variant-name lists at compile time. `N` must equal the
/// total length (generated code computes it from the source lists' `len()`s;
/// a mismatch fails const evaluation). An over-large `N` trips the
/// `assert!` at the end; an under-large `N` fails const evaluation with an
/// out-of-bounds index write — both are compile errors at the generated call
/// sites.
///
/// # Panics
///
/// If `N` does not equal the summed list lengths — in const context that's
/// a compile error, not a runtime panic.
#[must_use]
pub const fn concat_variants<const N: usize>(
    lists: &[&'static [&'static str]],
) -> [&'static str; N] {
    let mut out = [""; N];
    let mut i = 0;
    let mut l = 0;
    while l < lists.len() {
        let list = lists[l];
        let mut j = 0;
        while j < list.len() {
            out[i] = list[j];
            i += 1;
            j += 1;
        }
        l += 1;
    }
    assert!(
        i == N,
        "concat_variants: N must equal the summed list lengths"
    );
    out
}

/// Seq visitor for 2-field tuple variants used by generated `SupportsMacros`
/// impls.
pub struct Pair<A, B>(PhantomData<(A, B)>);

impl<A, B> Pair<A, B> {
    #[must_use]
    pub fn new() -> Self { Pair(PhantomData) }
}

impl<A, B> Default for Pair<A, B> {
    fn default() -> Self { Self::new() }
}

impl<'de, A: Deserialize<'de>, B: Deserialize<'de>> Visitor<'de> for Pair<A, B> {
    type Value = (A, B);

    fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str("a 2-element tuple variant")
    }

    fn visit_seq<S: SeqAccess<'de>>(self, mut seq: S) -> Result<Self::Value, S::Error> {
        let a = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(0, &self))?;
        let b = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(1, &self))?;
        Ok((a, b))
    }
}

/// Seq visitor for 3-field tuple variants.
pub struct Triple<A, B, C>(PhantomData<(A, B, C)>);

impl<A, B, C> Triple<A, B, C> {
    #[must_use]
    pub fn new() -> Self { Triple(PhantomData) }
}

impl<A, B, C> Default for Triple<A, B, C> {
    fn default() -> Self { Self::new() }
}

impl<'de, A, B, C> Visitor<'de> for Triple<A, B, C>
where
    A: Deserialize<'de>,
    B: Deserialize<'de>,
    C: Deserialize<'de>,
{
    type Value = (A, B, C);

    fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        f.write_str("a 3-element tuple variant")
    }

    fn visit_seq<S: SeqAccess<'de>>(self, mut seq: S) -> Result<Self::Value, S::Error> {
        let a = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(0, &self))?;
        let b = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(1, &self))?;
        let c = seq
            .next_element()?
            .ok_or_else(|| de::Error::invalid_length(2, &self))?;
        Ok((a, b, c))
    }
}
