use crate::Count;
use crate::Expansion;
use crate::Reference;
use crate::Selection;
use crate::SupportsMacros;
use crate::TokenSpec;
use crate::mana::ManaProduction;

/// An intrinsic game verb ([CR#700,701]) whose **agent is the source object or
/// the effect itself**, not a player: the source deals the damage, the effect
/// destroys/returns the object. Player-performed verbs (draw, sacrifice, …)
/// carry an explicit agent and live on [`PlayerAction`], reached through `By`.
///
/// Authored RON writes a bare [`PlayerAction`] in an effect slot (`Draw(1)`,
/// `Tap(This)`, `Sacrifice(This)`) and it reads as `By(Reference::You, …)` —
/// the implicit-you default, declared by `By`'s `#[macro_ron(embed)]` marker
/// with `#[macro_ron(default = "Reference::You")]` on the agent field, via
/// the macro layer's `embeds_untagged` hook (`Action` is registered with
/// `.embeds_untagged()`). An explicit different agent is written
/// `By(Target(0), Draw(3))` (Ancestral Recall) and read natively. Both serde
/// impls are generated by `#[derive(SupportsMacros)]` to carry that: the
/// reader tries `Action`'s own variants first, then falls through to a
/// `PlayerAction`; the writer emits the bare `PlayerAction`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Action {
    /// Deal an amount of damage to a selection ([CR#120.1]) — the source object
    /// is the agent.
    DealDamage(Selection, Count),
    /// Destroy a selected permanent ([CR#701.8]).
    Destroy(Selection),
    /// Return a selection to its owner's hand.
    ReturnToHand(Selection),
    /// A named player performs the [`PlayerAction`] ([CR#608.2]). `By(You, …)`
    /// is the implicit-you default and is written bare in RON.
    #[macro_ron(embed)]
    By(
        #[macro_ron(default = "Reference::You")] Reference,
        PlayerAction,
    ),
}

/// A verb a **player** performs, carrying an explicit agent via
/// [`Action::By`]. Authored bare in effect slots (the agent defaults to
/// `You`); a cost (`CostComponent::Do`) holds a bare `PlayerAction` whose
/// agent is implicitly the payer.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum PlayerAction {
    /// Draw a number of cards ([CR#121.1]).
    Draw(Count),
    /// Discard a number of cards ([CR#701.9]).
    Discard(Count),
    /// Gain an amount of life ([CR#119.3]).
    GainLife(Count),
    /// Lose an amount of life — pay-life when in a cost ([CR#119.3]).
    LoseLife(Count),
    /// Add mana to the player's mana pool ([CR#106.4]) — the production
    /// carries optional unit riders ([CR#106.6]).
    AddMana(Count, ManaProduction),
    /// Create a number of token permanents ([CR#111.1,701.7]).
    Create(Count, TokenSpec),
    /// Sacrifice a selected permanent ([CR#701.21]).
    Sacrifice(Selection),
    /// Exile a selection ([CR#701.13]).
    Exile(Selection),
    /// Tap a selection ([CR#701.26a]).
    Tap(Selection),
    /// Untap a selection ([CR#701.26b]).
    Untap(Selection),
    /// "You get an emblem with [abilities]" — a command-zone object that
    /// never touches the battlefield (rules-taxonomy §6: a degenerate
    /// token definition; [CR#114.1,114.4]).
    GetEmblem(Vec<crate::Ability>),
    /// A resolution choice stored under a note key ([CR#608.2d] choice +
    /// [CR#607.2] slot): "choose a color" and kin.
    ChooseAndNote(crate::Ident, crate::NotedKind),
    /// Put a copy of each selected spell on the stack ([CR#707.10] — a
    /// copy on the stack, NOT casting one; [CR#707.12] casting rides the
    /// 601 pipeline).
    CopySpell(Selection),
    /// Flip that many coins ([CR#705.1]) — results are events; call/win
    /// framing is the consumer's ([CR#705.2]).
    FlipCoins(Count),
    /// Roll that many dice with the given number of sides ([CR#706.1]);
    /// an IGNORED roll is considered to have never happened ([CR#706.6]).
    RollDice(Count, crate::Uint),
    /// Put counters of the named kind on each selected object/player
    /// ([CR#122.1] — counters go on objects AND players).
    PutCounters(Selection, crate::Ident, Count),
    /// Remove counters of the named kind ([CR#122.1]; cost-eligible —
    /// "Remove a +1/+1 counter from this creature:").
    RemoveCounters(Selection, crate::Ident, Count),
    /// Put a selection of cards into their owner's library at a `Count`
    /// position counted from the top: `0` = top, `CardsInLibrary(owner)` =
    /// bottom. An index past the bottom places the card on the bottom
    /// ([CR#401.7]). When the selection is two or more cards, the owner
    /// arranges them in any order ([CR#401.4]).
    PutInLibrary(Selection, Count),
    /// "[Player] wins the game" ([CR#104.2b]) — immediate on resolution,
    /// suppressed by a matching `CantWin` outcome gate ([CR#101.1]
    /// precedence; the last-player-standing win [CR#104.2a] never rides
    /// this verb and pierces gates).
    WinGame,
    /// "[Player] loses the game" ([CR#104.3e]) — immediate on resolution,
    /// suppressed by a matching `CantLose` outcome gate. A player who
    /// would win and lose simultaneously loses ([CR#104.3f]).
    LoseGame,
    /// Restart the game ([CR#727.1]) — a TERMINAL with explicit carryover
    /// (every card involved comes along, ownership unchanged [CR#727.2];
    /// effects may exempt cards [CR#727.5]; trailing instructions execute
    /// just before the new first untap step [CR#727.4]), never a state
    /// reset. The actor binding IS [CR#727.1a]: the restarting effect's
    /// controller starts the new game. The restarted game ends with no
    /// winner, loser, or draw. Subgames ([CR#729]) are a different,
    /// deferred concept (a context push, not a restart).
    RestartGame,
    /// Shuffle the actor's library ([CR#701.24a]) — an INFORMATION event
    /// too: order knowledge is destroyed for everyone, and revealed cards
    /// in the library stop being revealed and become new objects
    /// ([CR#701.20d]). Why library actions never rewind: [CR#733.1].
    Shuffle,
    /// Set the actor's life total to N ([CR#119.5]): resolves as a gain
    /// or loss of the necessary difference — triggers see the gain/loss,
    /// never a "set" event. Equal totals = no event (transition-only).
    SetLife(Count),
    /// Reveal a selection to all players ([CR#701.20a]); `to` names a
    /// player instead = "look at" — same operation shown to a subset
    /// ([CR#701.20e]). Revealing never moves the card ([CR#701.20b]).
    /// The reveal WINDOW (how long it stays shown, [CR#701.20a]) is the
    /// engine's effect-instance machinery, not grammar.
    Reveal {
        what: Selection,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        to: Option<Reference>,
    },
    /// A remembered `PlayerAction` macro invocation.
    #[macro_ron(expanded)]
    Expanded(Expansion<PlayerAction>),
}

impl PlayerAction {
    /// Whether this verb may appear in a cost (`CostComponent::Do`): the
    /// payer performs it, nothing targets ([CR#601.2b..601.2c]). Cost-eligible
    /// verbs are the self-directed ones a player can pay with — sacrifice,
    /// exile, tap, untap, discard, pay-life (`LoseLife`), and reveal
    /// ("reveal a blue card from your hand:" — a reveal that is part of a
    /// cost stays shown until the spell leaves the stack, [CR#701.20a]).
    #[must_use]
    pub fn is_cost_eligible(&self) -> bool {
        matches!(
            self,
            PlayerAction::Sacrifice(_)
                | PlayerAction::Exile(_)
                | PlayerAction::Tap(_)
                | PlayerAction::Untap(_)
                | PlayerAction::Discard(_)
                | PlayerAction::LoseLife(_)
                | PlayerAction::RemoveCounters(..)
                | PlayerAction::Reveal { .. }
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::count::Count;
    use crate::reference::Reference;
    use crate::selection::Selection;

    fn read(source: &str) -> Action { crate::ron::options().from_str(source).unwrap() }
    fn write(action: &Action) -> String { crate::ron::options().to_string(action).unwrap() }

    #[test]
    fn is_cost_eligible_covers_self_directed_verbs() {
        assert!(PlayerAction::Sacrifice(Selection::Ref(Reference::This)).is_cost_eligible());
        assert!(PlayerAction::Exile(Selection::Ref(Reference::This)).is_cost_eligible());
        assert!(PlayerAction::Tap(Selection::Ref(Reference::This)).is_cost_eligible());
        assert!(PlayerAction::Untap(Selection::Ref(Reference::This)).is_cost_eligible());
        assert!(PlayerAction::Discard(Count::Literal(1)).is_cost_eligible());
        assert!(PlayerAction::LoseLife(Count::Literal(1)).is_cost_eligible());

        assert!(!PlayerAction::Draw(Count::Literal(1)).is_cost_eligible());
        assert!(!PlayerAction::GainLife(Count::Literal(3)).is_cost_eligible());
        assert!(
            !PlayerAction::AddMana(Count::Literal(1), crate::ManaSpec::AnyColor.into())
                .is_cost_eligible()
        );
    }

    /// A bare player verb reads as `By(You, …)` — the implicit-you default:
    /// the derive-generated embed dispatch handles unknown identifiers even
    /// without a `MacroSet` in play (plain `ron` read).
    #[test]
    fn bare_player_verb_defaults_to_you() {
        assert_eq!(
            read("Draw(Literal(1))"),
            Action::By(Reference::You, PlayerAction::Draw(Count::Literal(1))),
        );
        assert_eq!(
            read("Sacrifice(This)"),
            Action::By(
                Reference::You,
                PlayerAction::Sacrifice(Selection::Ref(Reference::This)),
            ),
        );
        assert_eq!(
            read("Tap(This)"),
            Action::By(
                Reference::You,
                PlayerAction::Tap(Selection::Ref(Reference::This)),
            ),
        );
    }

    /// An explicit different agent reads natively — Ancestral Recall's
    /// `By(Target(0), Draw(3))`.
    #[test]
    fn explicit_agent_reads_natively() {
        assert_eq!(
            read("By(Target(0), Draw(Literal(3)))"),
            Action::By(Reference::Target(0), PlayerAction::Draw(Count::Literal(3)),),
        );
    }

    /// The source-agent verbs read natively.
    #[test]
    fn source_verbs_read_natively() {
        assert_eq!(
            read("DealDamage(Target(0), Literal(3))"),
            Action::DealDamage(Selection::Ref(Reference::Target(0)), Count::Literal(3)),
        );
        assert_eq!(
            read("Destroy(This)"),
            Action::Destroy(Selection::Ref(Reference::This)),
        );
    }

    /// `By(You, …)` writes the player action bare and round-trips.
    #[test]
    fn by_you_round_trips_bare() {
        let v = Action::By(Reference::You, PlayerAction::Draw(Count::Literal(1)));
        let written = write(&v);
        assert!(
            !written.contains("By("),
            "By(You, …) should write bare, got {written}"
        );
        assert_eq!(read(&written), v);
    }

    /// A non-`You` agent writes the explicit `By(other, …)` form and
    /// round-trips.
    #[test]
    fn by_other_round_trips() {
        let v = Action::By(Reference::Target(0), PlayerAction::Draw(Count::Literal(3)));
        let written = write(&v);
        assert!(
            written.contains("By("),
            "expected explicit By, got {written}"
        );
        assert_eq!(read(&written), v);
    }

    /// `PutInLibrary` under the implicit-`You` agent writes bare (no `By(`)
    /// through the new 2-tuple `(Selection, Count)` serialize arm, and
    /// round-trips back to the same value.
    #[test]
    fn put_in_library_round_trips_bare() {
        let v = Action::By(
            Reference::You,
            PlayerAction::PutInLibrary(Selection::Ref(Reference::This), Count::Literal(0)),
        );
        let written = write(&v);
        assert!(
            !written.contains("By("),
            "By(You, …) should write bare, got {written}"
        );
        assert_eq!(read(&written), v);
    }

    /// `PutInLibrary` is not cost-eligible — it isn't a self-directed cost
    /// the payer can offer.
    #[test]
    fn put_in_library_is_not_cost_eligible() {
        assert!(
            !PlayerAction::PutInLibrary(Selection::Ref(Reference::This), Count::Literal(0))
                .is_cost_eligible()
        );
    }
}
