use crate::Expansion;
use crate::Filter;
use crate::Quantity;
use crate::Reference;
use crate::Selection;
use crate::SupportsMacros;

/// The binder feeding [`Effect::With`](crate::With), [`Each`](crate::Each),
/// and [`DivideAmong`](crate::DivideAmong) — the Idris `Bindable`, collapsed
/// (cardinality is encoded by the variant, not a type index). A one-binder
/// (`TheRef`/`ChooseOne`) binds a single object read as
/// [`Reference::That`](crate::Reference::That); a many-binder
/// (`Choose`/`Existing`) binds a group read as
/// [`Selection::That`](crate::Selection::That). `Each`/`DivideAmong` take a
/// many-binder and expose each element in turn as
/// [`Reference::It`](crate::Reference::It).
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Binder {
    /// Bind an existing single reference (a captured target, `This`) — One →
    /// `That`.
    TheRef(Reference),
    /// The actor chooses exactly one match — One → `That`. ("sacrifice a
    /// creature")
    ChooseOne(Filter),
    /// The actor chooses a quantity of matches — Many → `That` (group).
    /// ("choose two cards")
    Choose(Quantity, Filter),
    /// An existing group/selection — Many → `That` (group).
    Existing(Selection),
    /// A remembered `Binder` macro invocation.
    #[macro_ron(expanded)]
    Expanded(Expansion<Binder>),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CharacteristicFilter;
    use crate::Type;

    fn read(source: &str) -> Binder {
        crate::ron::options().from_str(source).unwrap()
    }

    fn to_string(value: &Binder) -> String {
        crate::ron::options().to_string(value).unwrap()
    }

    /// Each binder variant round-trips through the `SupportsMacros` serde.
    #[test]
    fn binder_variants_round_trip() {
        let one_filter = Filter::Characteristic(CharacteristicFilter::Type(Type::Creature));
        for v in [
            Binder::TheRef(Reference::This),
            Binder::ChooseOne(one_filter.clone()),
            Binder::Choose(Quantity::one(), one_filter.clone()),
            Binder::Existing(Selection::That),
        ] {
            assert_eq!(read(&to_string(&v)), v, "round-trip failed for {v:?}");
        }
    }

    /// `Existing` wraps a `Selection` and reads it flat.
    #[test]
    fn existing_wraps_selection() {
        assert_eq!(read("Existing(That)"), Binder::Existing(Selection::That));
    }
}
