use std::sync::Arc;

use crate::Action;
use crate::Expansion;
use crate::Predicate;
use crate::Quantity;
use crate::Reference;
use crate::Selection;
use crate::SupportsMacros;
use crate::Zone;

/// The binder feeding [`OneShotEffect::With`](crate::With),
/// [`Each`](crate::Each), and [`Distribute`](crate::Distribute) — the Idris
/// `Bindable`, collapsed (cardinality is encoded by the variant, not a type
/// index). A one-binder (`TheRef`/`ChooseOne`) binds a single object read as
/// [`Reference::That`](crate::Reference::That); a many-binder
/// (`Choose`/`Existing`) binds a group read as
/// [`Selection::That`](crate::Selection::That). `Each`/`Distribute` take a
/// many-binder and expose each element in turn as
/// [`Reference::It`](crate::Reference::It).
///
/// The `Produce` binder is wired into engine resolution ([CR#400.7j]): a
/// `With(Produce(action), body)` runs the action and binds its moved product as
/// the singular `That`, chased through the same-resolution move record — the
/// "…this way" linkage madness's exile-and-cast rides. Only a `Move` action
/// produces-and-captures in this cut; other producer actions stay a labeled
/// seam. The search binders (`Search`/`SearchOne`) are wired into engine
/// resolution too ([CR#701.23,701.24]): the engine surfaces a `ChooseObjects`
/// decision over the (possibly hidden) `from` zones of `whose`, honoring the
/// three fail-to-find shapes ([CR#701.23b..701.23d]), and binds the result as
/// `That`/group — `if_none` runs, unbound, on a failed find. Reveal and
/// shuffle are NOT binder-level behavior: they ride the body as ordinary
/// `Reveal`/`Shuffle` steps, same as any other effect (see
/// `resolve/effect.rs`). All (de)serialize and round-trip here.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Binder {
    /// Bind an existing single reference (a captured target, `This`) — One →
    /// `That`.
    TheRef(Reference),
    /// The chooser picks exactly one match — One → `That`. ("sacrifice a
    /// creature") `by` names who chooses, mirroring the Idris `{default You
    /// by}`: the default is the controller; a foreign chooser ("that player
    /// sacrifices a creature of their choice", [CR#608.2d,701.21a]) overrides
    /// it.
    ChooseOne {
        /// What may be picked (the Idris `Predicate`).
        filter: Predicate,
        /// Who chooses (default `You`).
        #[serde(default = "ref_you", skip_serializing_if = "ref_is_you")]
        by: Reference,
    },
    /// Run an [`Action`] for effect and bind its product — the moved/created
    /// object — as the singular [`Reference::That`](crate::Reference::That) —
    /// One → `That`. The Idris `Produce : Action b -> Bindable b One AnObject`
    /// (Cavern-of-Souls-style "exile it":
    /// `With(Produce(Move(It, Exile)), …)`). Boxed: an open [`Action`] is the
    /// largest leaf enum (`clippy::large_enum_variant`).
    Produce(Arc<Action>),
    /// Search `whose`'s `from`-zones (hidden libraries/graveyards) for exactly
    /// ONE match, bound as `That` — One → `That`. The Idris `SearchOne`;
    /// `by`/`whose` default to `You`, `from` to `[Library]` (each omitted on
    /// write when default).
    SearchOne {
        /// The card sought (the Idris `Predicate`).
        filter: Predicate,
        /// Who performs the search (default `You`).
        #[serde(default = "ref_you", skip_serializing_if = "ref_is_you")]
        by: Reference,
        /// Whose zones are searched (default `You` — own library) — e.g.
        /// Bribery searches an opponent's library.
        #[serde(default = "ref_you", skip_serializing_if = "ref_is_you")]
        whose: Reference,
        /// The zones searched (default `[Library]`; e.g. library and/or
        /// graveyard).
        #[serde(default = "from_library", skip_serializing_if = "is_from_library")]
        from: Arc<[Zone]>,
        /// The explicit WHIFF branch ([CR#701.23b] — a search may fail to
        /// find): what happens when nothing is found. Whiff semantics are
        /// DATA — a whiffed search skips the product-dependent body, and the
        /// branch here runs instead; it runs WITHOUT the product
        /// binding, so reading the search's `That` inside it is unsound
        /// (rejected by the Idris re-emit gate).
        #[serde(default, skip_serializing_if = "Option::is_none")]
        if_none: Option<Arc<crate::OneShotEffect>>,
    },
    /// The chooser picks a quantity of matches — Many → `That` (group).
    /// ("choose two cards") Same `by` default as
    /// [`ChooseOne`](Self::ChooseOne).
    Choose {
        /// How many to pick (the Idris `Quantity`).
        quantity: Quantity,
        /// What may be picked (the Idris `Predicate`).
        filter: Predicate,
        /// Who chooses (default `You`).
        #[serde(default = "ref_you", skip_serializing_if = "ref_is_you")]
        by: Reference,
    },
    /// An existing group/selection — Many → `That` (group).
    Existing(Selection),
    /// Search `whose`'s `from`-zones for a [`Quantity`] of matches, bound as a
    /// group `That` (`Each`-iterated) — Many → `That`. The Idris `Search`,
    /// like [`Choose`](Self::Choose) but over (hidden) searched zones the
    /// engine reveals/shuffles. Same `by`/`whose`/`from` defaults as
    /// [`SearchOne`](Self::SearchOne).
    Search {
        /// How many cards to find (the Idris `Quantity`).
        quantity: Quantity,
        /// The cards sought (the Idris `Predicate`).
        filter: Predicate,
        /// Who performs the search (default `You`).
        #[serde(default = "ref_you", skip_serializing_if = "ref_is_you")]
        by: Reference,
        /// Whose zones are searched (default `You`).
        #[serde(default = "ref_you", skip_serializing_if = "ref_is_you")]
        whose: Reference,
        /// The zones searched (default `[Library]`).
        #[serde(default = "from_library", skip_serializing_if = "is_from_library")]
        from: Arc<[Zone]>,
        /// The explicit whiff branch ([CR#701.23b]) — see
        /// [`SearchOne::if_none`](Binder::SearchOne). Elaborates without the
        /// searched group bound.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        if_none: Option<Arc<crate::OneShotEffect>>,
    },
    /// A remembered `Binder` macro invocation.
    #[macro_ron(expanded)]
    Expanded(Expansion<Binder>),
}

/// The `by`/`whose` default — the searching/choosing player is the controller
/// ([`Reference::You`]). Mirrors the Idris `{default You by}` / `{default You
/// whose}` on `ChooseOne`/`Choose`/`Search`/`SearchOne`.
fn ref_you() -> Reference {
    Reference::You
}

/// Whether a [`Reference`] is the default `You` (so it is omitted on write).
fn ref_is_you(r: &Reference) -> bool {
    matches!(r, Reference::You)
}

/// The default search domain — a player's library. Mirrors the Idris
/// `{default [Library] from}` on `Search`/`SearchOne`.
fn from_library() -> Arc<[Zone]> {
    vec![Zone::Library].into()
}

/// Whether `from` is the default single-`Library` domain (so it is omitted on
/// write).
fn is_from_library(zones: &[Zone]) -> bool {
    zones == [Zone::Library]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CharacteristicPredicate;
    use crate::Destination;
    use crate::Supertype;

    fn read(source: &str) -> Binder {
        crate::ron::options().from_str(source).unwrap()
    }

    fn to_string(value: &Binder) -> String {
        crate::ron::options().to_string(value).unwrap()
    }

    /// Each binder variant round-trips through the `SupportsMacros` serde —
    /// including the producer/search binders and their `by`/`whose`/`from`
    /// defaults (both omitted-default and explicit-override forms).
    #[test]
    fn binder_variants_round_trip() {
        let one_filter =
            Predicate::Characteristic(CharacteristicPredicate::Supertype(Supertype::Basic));
        for v in [
            Binder::TheRef(Reference::This),
            Binder::ChooseOne {
                filter: one_filter.clone(),
                by: Reference::You,
            },
            // A foreign chooser ("that player sacrifices a creature of their
            // choice") writes its non-default `by` explicitly.
            Binder::ChooseOne {
                filter: one_filter.clone(),
                by: Reference::EventActor,
            },
            Binder::Choose {
                quantity: Quantity::one(),
                filter: one_filter.clone(),
                by: Reference::You,
            },
            Binder::Choose {
                quantity: Quantity::one(),
                filter: one_filter.clone(),
                by: Reference::Opponent,
            },
            Binder::Existing(Selection::They),
            Binder::Produce(Arc::new(Action::Move(
                Reference::It,
                Destination::Zone(Zone::Exile),
                vec![].into(),
                None,
            ))),
            // Bare defaults: by = whose = You, from = [Library].
            Binder::SearchOne {
                filter: one_filter.clone(),
                by: Reference::You,
                whose: Reference::You,
                from: vec![Zone::Library].into(),
                if_none: None,
            },
            // Explicit non-default by/whose/from (Bribery-style: search an
            // opponent's library and graveyard).
            Binder::SearchOne {
                filter: one_filter.clone(),
                by: Reference::You,
                whose: Reference::Opponent,
                from: vec![Zone::Library, Zone::Graveyard].into(),
                if_none: None,
            },
            Binder::Search {
                quantity: Quantity::one(),
                filter: one_filter.clone(),
                by: Reference::You,
                whose: Reference::You,
                from: vec![Zone::Library].into(),
                if_none: None,
            },
            Binder::Search {
                quantity: Quantity::one(),
                filter: one_filter.clone(),
                by: Reference::Opponent,
                whose: Reference::Opponent,
                from: vec![Zone::Graveyard].into(),
                if_none: None,
            },
        ] {
            assert_eq!(read(&to_string(&v)), v, "round-trip failed for {v:?}");
        }
    }

    /// `Existing` wraps a `Selection` and reads it flat.
    #[test]
    fn existing_wraps_selection() {
        assert_eq!(read("Existing(They)"), Binder::Existing(Selection::They));
    }

    /// The choose binders omit the default `by: You` on write and read it
    /// back — the common written form carries only the filter (and quantity).
    #[test]
    fn choose_binders_omit_default_by() {
        let creature =
            Predicate::Characteristic(CharacteristicPredicate::Supertype(Supertype::Basic));
        let one = Binder::ChooseOne {
            filter: creature.clone(),
            by: Reference::You,
        };
        let written = to_string(&one);
        assert!(
            !written.contains("by:"),
            "default by omitted, got {written}"
        );
        assert_eq!(read(&written), one);

        let many = Binder::Choose {
            quantity: Quantity::one(),
            filter: creature,
            by: Reference::EventActor,
        };
        let written = to_string(&many);
        assert!(
            written.contains("by:"),
            "non-default by written, got {written}"
        );
        assert_eq!(read(&written), many);
    }

    /// The search binders omit `by`/`whose`/`from` when default and read them
    /// back to the defaults — the bare written form carries only the filter.
    #[test]
    fn search_one_omits_default_resolver_inputs() {
        let creature =
            Predicate::Characteristic(CharacteristicPredicate::Supertype(Supertype::Basic));
        let bare = Binder::SearchOne {
            filter: creature.clone(),
            by: Reference::You,
            whose: Reference::You,
            from: vec![Zone::Library].into(),
            if_none: None,
        };
        let written = to_string(&bare);
        assert!(
            !written.contains("by:") && !written.contains("whose:") && !written.contains("from:"),
            "defaults must be omitted, got {written}"
        );
        assert_eq!(read(&written), bare);
    }

    /// The explicit whiff branch ([CR#701.23b]): an absent `if_none` is
    /// omitted on write; a present branch reads flat and round-trips.
    #[test]
    fn search_if_none_defaults_and_round_trips() {
        use crate::Action;
        use crate::Count;
        use crate::LifeOp;
        use crate::OneShotEffect;

        let creature =
            Predicate::Characteristic(CharacteristicPredicate::Supertype(Supertype::Basic));
        let bare = Binder::SearchOne {
            filter: creature.clone(),
            by: Reference::You,
            whose: Reference::You,
            from: vec![Zone::Library].into(),
            if_none: None,
        };
        assert!(
            !to_string(&bare).contains("if_none"),
            "absent if_none omitted"
        );

        let whiff = Binder::SearchOne {
            filter: creature,
            by: Reference::You,
            whose: Reference::You,
            from: vec![Zone::Library].into(),
            if_none: Some(Arc::new(OneShotEffect::Act(Action::ChangeLife(
                Reference::You,
                LifeOp::Down(Count::Literal(1)),
            )))),
        };
        assert_eq!(read(&to_string(&whiff)), whiff);
        assert_eq!(
            read("SearchOne(filter: Supertype(Basic), if_none: ChangeLife(You, Down(1)))"),
            whiff,
        );
    }
}
