use crate::Action;
use crate::Expansion;
use crate::Filter;
use crate::Quantity;
use crate::Reference;
use crate::Selection;
use crate::SupportsMacros;
use crate::Zone;

/// The binder feeding [`Effect::With`](crate::With), [`Each`](crate::Each),
/// and [`DivideAmong`](crate::DivideAmong) — the Idris `Bindable`, collapsed
/// (cardinality is encoded by the variant, not a type index). A one-binder
/// (`TheRef`/`ChooseOne`) binds a single object read as
/// [`Reference::That`](crate::Reference::That); a many-binder
/// (`Choose`/`Existing`) binds a group read as
/// [`Selection::That`](crate::Selection::That). `Each`/`DivideAmong` take a
/// many-binder and expose each element in turn as
/// [`Reference::It`](crate::Reference::It).
///
/// The producer/search binders (`Produce`/`Search`/`SearchOne`) carry the
/// Idris constructors' resolver inputs but are not yet wired into engine
/// resolution — there is no runtime produce-and-capture or library-search
/// primitive — so the engine surfaces a clearly-labeled seam for them (see
/// `resolve.rs`); they (de)serialize and round-trip here.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Binder {
    /// Bind an existing single reference (a captured target, `This`) — One →
    /// `That`.
    TheRef(Reference),
    /// The actor chooses exactly one match — One → `That`. ("sacrifice a
    /// creature")
    ChooseOne(Filter),
    /// Run an [`Action`] for effect and bind its product — the moved/created
    /// object — as the singular [`Reference::That`](crate::Reference::That) —
    /// One → `That`. The Idris `Produce : Action b -> Bindable b One AnObject`
    /// (Cavern-of-Souls-style "exile it":
    /// `With(Produce(Move(It, Exile)), …)`). Boxed: an open [`Action`] is the
    /// largest leaf enum (`clippy::large_enum_variant`).
    Produce(Box<Action>),
    /// Search `whose`'s `from`-zones (hidden libraries/graveyards) for exactly
    /// ONE match, bound as `That` — One → `That`. The Idris `SearchOne`;
    /// `by`/`whose` default to `You`, `from` to `[Library]` (each omitted on
    /// write when default).
    SearchOne {
        /// The card sought (the Idris `Predicate`).
        filter: Filter,
        /// Who performs the search (default `You`).
        #[serde(default = "ref_you", skip_serializing_if = "ref_is_you")]
        by: Reference,
        /// Whose zones are searched (default `You` — own library) — e.g.
        /// Bribery searches an opponent's library.
        #[serde(default = "ref_you", skip_serializing_if = "ref_is_you")]
        whose: Reference,
        /// The zones searched (default `[Library]`; e.g. library and/or
        /// graveyard).
        #[serde(default = "from_library", skip_serializing_if = "is_from_library")]
        from: Vec<Zone>,
    },
    /// The actor chooses a quantity of matches — Many → `That` (group).
    /// ("choose two cards")
    Choose(Quantity, Filter),
    /// An existing group/selection — Many → `That` (group).
    Existing(Selection),
    /// Search `whose`'s `from`-zones for a [`Quantity`] of matches, bound as a
    /// group `That` (`Each`-iterated) — Many → `That`. The Idris `Search`,
    /// like [`Choose`](Self::Choose) but over (hidden) searched zones the
    /// engine reveals/shuffles. Same `by`/`whose`/`from` defaults as
    /// [`SearchOne`](Self::SearchOne).
    Search {
        /// How many cards to find (the Idris `Quantity`).
        quantity: Quantity,
        /// The cards sought (the Idris `Predicate`).
        filter: Filter,
        /// Who performs the search (default `You`).
        #[serde(default = "ref_you", skip_serializing_if = "ref_is_you")]
        by: Reference,
        /// Whose zones are searched (default `You`).
        #[serde(default = "ref_you", skip_serializing_if = "ref_is_you")]
        whose: Reference,
        /// The zones searched (default `[Library]`).
        #[serde(default = "from_library", skip_serializing_if = "is_from_library")]
        from: Vec<Zone>,
    },
    /// A remembered `Binder` macro invocation.
    #[macro_ron(expanded)]
    Expanded(Expansion<Binder>),
}

/// The `by`/`whose` default — the searching/choosing player is the controller
/// ([`Reference::You`]). Mirrors the Idris `{default You by}` / `{default You
/// whose}` on `Search`/`SearchOne`.
fn ref_you() -> Reference {
    Reference::You
}

/// Whether a [`Reference`] is the default `You` (so it is omitted on write).
fn ref_is_you(r: &Reference) -> bool {
    matches!(r, Reference::You)
}

/// The default search domain — a player's library. Mirrors the Idris
/// `{default [Library] from}` on `Search`/`SearchOne`.
fn from_library() -> Vec<Zone> {
    vec![Zone::Library]
}

/// Whether `from` is the default single-`Library` domain (so it is omitted on
/// write).
fn is_from_library(zones: &[Zone]) -> bool {
    zones == [Zone::Library]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CharacteristicFilter;
    use crate::Destination;
    use crate::Type;

    fn read(source: &str) -> Binder {
        crate::ron::options().from_str(source).unwrap()
    }

    fn to_string(value: &Binder) -> String {
        crate::ron::options().to_string(value).unwrap()
    }

    /// Each binder variant round-trips through the `SupportsMacros` serde —
    /// including the producer/search binders and their `by`/`whose`/`from`
    /// defaults (both omitted-default and explicit-override forms).
    #[test]
    fn binder_variants_round_trip() {
        let one_filter = Filter::Characteristic(CharacteristicFilter::Type(Type::Creature));
        for v in [
            Binder::TheRef(Reference::This),
            Binder::ChooseOne(one_filter.clone()),
            Binder::Choose(Quantity::one(), one_filter.clone()),
            Binder::Existing(Selection::That),
            Binder::Produce(Box::new(Action::Move(
                Reference::It,
                Destination::Zone(Zone::Exile),
            ))),
            // Bare defaults: by = whose = You, from = [Library].
            Binder::SearchOne {
                filter: one_filter.clone(),
                by: Reference::You,
                whose: Reference::You,
                from: vec![Zone::Library],
            },
            // Explicit non-default by/whose/from (Bribery-style: search an
            // opponent's library and graveyard).
            Binder::SearchOne {
                filter: one_filter.clone(),
                by: Reference::You,
                whose: Reference::Opponent,
                from: vec![Zone::Library, Zone::Graveyard],
            },
            Binder::Search {
                quantity: Quantity::one(),
                filter: one_filter.clone(),
                by: Reference::You,
                whose: Reference::You,
                from: vec![Zone::Library],
            },
            Binder::Search {
                quantity: Quantity::one(),
                filter: one_filter.clone(),
                by: Reference::Opponent,
                whose: Reference::Opponent,
                from: vec![Zone::Graveyard],
            },
        ] {
            assert_eq!(read(&to_string(&v)), v, "round-trip failed for {v:?}");
        }
    }

    /// `Existing` wraps a `Selection` and reads it flat.
    #[test]
    fn existing_wraps_selection() {
        assert_eq!(read("Existing(That)"), Binder::Existing(Selection::That));
    }

    /// The search binders omit `by`/`whose`/`from` when default and read them
    /// back to the defaults — the bare written form carries only the filter.
    #[test]
    fn search_one_omits_default_resolver_inputs() {
        let creature = Filter::Characteristic(CharacteristicFilter::Type(Type::Creature));
        let bare = Binder::SearchOne {
            filter: creature.clone(),
            by: Reference::You,
            whose: Reference::You,
            from: vec![Zone::Library],
        };
        let written = to_string(&bare);
        assert!(
            !written.contains("by:") && !written.contains("whose:") && !written.contains("from:"),
            "defaults must be omitted, got {written}"
        );
        assert_eq!(read(&written), bare);
    }
}
