use serde::Deserialize;
use serde::Serialize;

use crate::Count;
use crate::EventFilter;
use crate::Expand;
use crate::Expansion;
use crate::Filter;
use crate::Reference;
use crate::SupportsMacros;

/// A numeric comparison ([CR#107.3]). The named forms keep RON readable —
/// `AtLeast` rather than `>=`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Expand, Serialize)]
pub enum Cmp {
    Eq,
    AtLeast,
    AtMost,
    Greater,
    Less,
}

impl Cmp {
    /// Does `lhs <op> rhs` hold? The single comparator table every numeric
    /// test routes through — `Condition::Compare`'s two evaluated counts and
    /// `CountBound::satisfied_by`'s matched-set cardinality alike.
    #[must_use]
    pub fn apply(self, lhs: crate::Uint, rhs: crate::Uint) -> bool {
        match self {
            Cmp::Eq => lhs == rhs,
            Cmp::AtLeast => lhs >= rhs,
            Cmp::AtMost => lhs <= rhs,
            Cmp::Greater => lhs > rhs,
            Cmp::Less => lhs < rhs,
        }
    }
}

use crate::Lookback;

/// A truth-valued test the engine evaluates ([CR#603.4] intervening-if,
/// [CR#118.12a] "unless", ability words). Ability words (`Threshold`,
/// `Delirium`, `Morbid`) are declared `Condition` macros — unknown names at
/// Condition positions fall through to the macro layer.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back, and the `Happened` struct variant reads flat
/// in RON through a generated helper struct + `unwrap_variant_newtypes`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Condition {
    /// Compare two scalar counts ([CR#107.1]).
    Compare(Count, Cmp, Count),
    /// At least one object matches ([CR#603.4], "if you control a …").
    Exists(Filter),
    /// A referenced object matches a filter ([CR#603.4], "if it is a …").
    Is(Reference, Filter),
    /// The referenced attachment is LEGALLY attached ([CR#701.3b,303.4d]): it
    /// has a host AND that (attachment, host) pair passes the attachment
    /// legality predicate (host-type / protection / `Cant(Attach)`). False when
    /// the object is unattached, attached to an illegal host, or self-attached
    /// — the exact "or is not attached / attached to an illegal object" trigger
    /// of the Aura graveyard SBA ([CR#704.5m]), whose static is
    /// `Sba(Not(LegallyAttached(Ref(This))), Move(Ref(This), Graveyard))`. The
    /// engine evaluates it through the one `attachment_legal` predicate (the
    /// same one the [CR#701.3b] attach no-op uses), never by subtype.
    LegallyAttached(Reference),
    /// The referenced creature has been dealt damage by a source with
    /// deathtouch since the last SBA check ([CR#704.5h]) — reads the
    /// deal-time `struck_by_deathtouch` flag. (Bespoke placeholder; a later
    /// damage-provenance pass replaces this with `Is(Ref(Source),
    /// Has(Deathtouch))`.)
    DamagedByDeathtouch(Reference),
    /// An event happened within a window (morbid/raid, [CR#608.2i]).
    Happened {
        event: EventFilter,
        within: Lookback,
    },
    /// The watched `value` was below `threshold` before the triggering
    /// occurrence and satisfies it after — [CR#714.2b]'s "the number of lore
    /// counters on it was less than N and became at least N", verbatim: a
    /// chapter ability's intervening-if. `value` NAMES the crossing quantity
    /// (a saga's lore total, `CounterCount(This, LoreCounter)`) for the
    /// checker to tie to the trigger's counter event; the engine reads the
    /// fired FACT's `before`/`after` channel, never a recomputation — a
    /// doubled 0→2 placement is one fact whose crossing both chapter I and
    /// chapter II observe.
    Crossed {
        value: Count,
        threshold: crate::CountBound,
    },
    /// The tagged optional cost ([`OptionalCost`](crate::OptionalCost)) was
    /// paid for this object — "if it was kicked" ([CR#702.33d]; buyback's
    /// "if the buyback cost was paid", [CR#702.27a]). The linked-ability read
    /// ([CR#702.33e,607.2]): the tag names the declaring `CostOption` on the
    /// same object. Replaces the bespoke `WasKicked` flag.
    PaidCost(crate::CostTag),
    /// It is the evaluating player's turn (the `you` of the evaluation
    /// context — an ability's controller). Sugar for `TurnOf(Ref(You))`, kept
    /// as the common, frame-robust specialization.
    YourTurn,
    /// It is a matching player's turn ([CR#603.4]) — the active player
    /// satisfies the player predicate. Generalizes
    /// [`YourTurn`](Condition::YourTurn) (which is `TurnOf(Ref(You))`):
    /// "during an opponent's turn" is `TurnOf(OpponentOf(Ref(You)))`. The
    /// `Filter` is a player predicate (`Ref(You)`, `OpponentOf(Ref(You))`,
    /// `Kind(Player)`, …).
    TurnOf(Filter),
    /// The current phase/step is exactly the given one. Main phases are
    /// single-step bare variants, so `DuringPhase(PrecombatMain)` works
    /// today; phase-class matching (any combat step) accretes when a card
    /// needs it.
    DuringPhase(crate::PhaseStep),
    /// All sub-conditions hold.
    AllOf(Vec<Condition>),
    /// At least one sub-condition holds.
    OneOf(Vec<Condition>),
    /// The sub-condition does not hold.
    Not(Box<Condition>),
    /// A remembered `Condition` macro invocation (ability words: `Threshold`,
    /// `Delirium`, `Morbid`). Serialized as the invocation, not the struct.
    #[macro_ron(expanded)]
    Expanded(Expansion<Condition>),
}

#[cfg(test)]
mod tests {
    use super::*;

    fn read(source: &str) -> Condition {
        crate::ron::options().from_str(source).unwrap()
    }

    #[test]
    fn compare_reads() {
        assert_eq!(
            read("Compare(X, AtLeast, Literal(3))"),
            Condition::Compare(Count::X, Cmp::AtLeast, Count::Literal(3)),
        );
    }

    #[test]
    fn your_turn_reads() {
        assert_eq!(read("YourTurn"), Condition::YourTurn);
    }

    /// `TurnOf(<player predicate>)` reads flat and round-trips; it carries the
    /// player filter `YourTurn` leaves implicit ([CR#603.4]).
    #[test]
    fn turn_of_reads_and_round_trips() {
        assert_eq!(
            read("TurnOf(Ref(You))"),
            Condition::TurnOf(Filter::Ref(Reference::You)),
        );
        // "during an opponent's turn".
        let opp = read("TurnOf(OpponentOf(Ref(You)))");
        assert_eq!(
            opp,
            Condition::TurnOf(Filter::Relation(crate::RelationFilter::OpponentOf(
                Box::new(Filter::Ref(Reference::You))
            ))),
        );
        let written = crate::ron::options().to_string(&opp).unwrap();
        assert_eq!(read(&written), opp);
    }

    #[test]
    fn during_phase_reads() {
        assert_eq!(
            read("DuringPhase(PostcombatMain)"),
            Condition::DuringPhase(crate::PhaseStep::PostcombatMain),
        );
    }

    /// `LegallyAttached(This)` reads and round-trips ([CR#704.5m] trigger).
    #[test]
    fn legally_attached_reads() {
        assert_eq!(
            read("LegallyAttached(This)"),
            Condition::LegallyAttached(Reference::This),
        );
        let v = Condition::LegallyAttached(Reference::This);
        let w = crate::ron::options().to_string(&v).unwrap();
        assert_eq!(read(&w), v);
    }

    /// `PaidCost(tag)` — the paid-optional-cost read ("if it was kicked",
    /// [CR#702.33d]) — reads a bare-ident tag and round-trips.
    #[test]
    fn paid_cost_reads_and_round_trips() {
        let v = read("PaidCost(Kicker)");
        assert_eq!(v, Condition::PaidCost(crate::CostTag::from("Kicker")));
        let written = crate::ron::options().to_string(&v).unwrap();
        assert_eq!(written, "PaidCost(Kicker)");
        assert_eq!(read(&written), v);
    }

    #[test]
    fn happened_reads() {
        use crate::Cause;
        use crate::CausePattern;
        use crate::CauseVerb;
        use crate::Zone;

        assert_eq!(
            read(
                "Happened(event: ZoneChange(cause: Cause(verb: Sacrifice), from: Battlefield, to: Graveyard), within: ThisTurn)"
            ),
            Condition::Happened {
                event: EventFilter::ZoneChange {
                    what: Filter::Any,
                    from: Some(Zone::Battlefield),
                    to: Some(Zone::Graveyard),
                    cause: Some(Cause::Cause(CausePattern {
                        verb: Some(CauseVerb::Sacrifice),
                        agency: None,
                        agent: None,
                    })),
                },
                within: Lookback::ThisTurn,
            },
        );
    }
}
