use serde::{Deserialize, Serialize};

use crate::{Count, Event, Expand, Expansion, Filter, Reference, SupportsMacros};

/// A numeric comparison ([CR#107.3]). The named forms keep RON readable —
/// `AtLeast` rather than `>=`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Serialize, Expand)]
pub enum Cmp {
    Eq,
    AtLeast,
    AtMost,
    Greater,
    Less,
}

/// The turn-history window a `Happened` condition looks back over
/// ([CR#608.2i]). Just `ThisTurn` for now; `ThisCombat` etc. accrete.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Serialize, Expand)]
pub enum Window {
    /// Since the start of the current turn (morbid, raid, "was kicked").
    ThisTurn,
}

/// A truth-valued test the engine evaluates ([CR#603.4] intervening-if,
/// [CR#118.12a] "unless", ability words). Ability words (`Threshold`,
/// `Delirium`, `Morbid`) are declared `Condition` macros — unknown names at
/// Condition positions fall through to the macro layer.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back, and the `Happened` struct variant reads flat
/// in RON through a generated helper struct + `unwrap_variant_newtypes`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Condition {
    /// Compare two scalar counts ([CR#107.3]).
    Compare(Count, Cmp, Count),
    /// At least one object matches ([CR#107.3], "if you control a …").
    Exists(Filter),
    /// A referenced object matches a filter ([CR#107.3], "if it is a …").
    Is(Reference, Filter),
    /// An event happened within a window (morbid/raid, [CR#608.2i]).
    Happened { event: Event, within: Window },
    /// It is the evaluating player's turn (the `you` of the evaluation
    /// context — an ability's controller).
    YourTurn,
    /// The current phase/step is exactly the given one. Main phases are
    /// single-step bare variants, so `DuringPhase(PrecombatMain)` works
    /// today; phase-class matching (any combat step) accretes when a card
    /// needs it.
    DuringPhase(crate::Phase),
    /// All sub-conditions hold.
    AllOf(Vec<Condition>),
    /// At least one sub-condition holds.
    OneOf(Vec<Condition>),
    /// The sub-condition does not hold.
    Not(Box<Condition>),
    /// A remembered `Condition` macro invocation (ability words: `Threshold`,
    /// `Delirium`, `Morbid`). Serialized as the invocation, not the struct.
    #[macro_ron(expanded)]
    Expanded(Expansion<Condition>),
}

#[cfg(test)]
mod tests {
    use super::*;

    fn read(source: &str) -> Condition { crate::ron::options().from_str(source).unwrap() }

    #[test]
    fn compare_reads() {
        assert_eq!(
            read("Compare(X, AtLeast, Literal(3))"),
            Condition::Compare(Count::X, Cmp::AtLeast, Count::Literal(3)),
        );
    }

    #[test]
    fn your_turn_reads() {
        assert_eq!(read("YourTurn"), Condition::YourTurn);
    }

    #[test]
    fn during_phase_reads() {
        assert_eq!(
            read("DuringPhase(PostcombatMain)"),
            Condition::DuringPhase(crate::Phase::PostcombatMain),
        );
    }

    #[test]
    fn happened_reads() {
        assert_eq!(
            read(r#"Happened(event: Performed(verb: "Sacrifice"), within: ThisTurn)"#),
            Condition::Happened {
                event: Event::Performed {
                    verb: "Sacrifice".into(),
                    by: Filter::Any,
                    on: Filter::Any,
                },
                within: Window::ThisTurn,
            },
        );
    }
}
