use crate::Expansion;
use crate::SupportsMacros;
use crate::action::PlayerAction;
use crate::mana::ManaCost;

/// A single component of an ability's cost ([CR#601.2b]).
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum CostComponent {
    /// Mana payment, e.g. `Mana([Generic(2)])`.
    Mana(ManaCost),
    /// The {T} symbol ([CR#107.5]).
    Tap,
    /// The {Q} symbol.
    Untap,
    /// Pay by performing a verb: the payer is implicitly you, so this holds a
    /// bare [`PlayerAction`] (no `By` wrapper). Only cost-eligible ones
    /// (`PlayerAction::is_cost_eligible`) belong here — enforced by the cards
    /// crate's validation lint, not the parser. Boxed: `PlayerAction` dwarfs
    /// the other variants, and `CostComponent` rides in `Vec<CostComponent>`
    /// cost lists, so an unboxed variant would size every element to it
    /// (`clippy::large_enum_variant`).
    Do(Box<PlayerAction>),
    /// A remembered `CostComponent` macro invocation (`SacrificeThis`, loyalty
    /// sugar, …).
    #[macro_ron(expanded)]
    Expanded(Expansion<CostComponent>),
}

/// The total-cost record of the [CR#601.2f] pipeline — an ENGINE-traffic
/// value, not card grammar: base (mana or alternative, per [CR#601.2b]) →
/// the `trace` of applied steps (`CostChange`: additional/increases, then
/// reductions, [CR#601.2f]) → mana floor → direct effects → `locked`.
/// After the lock (`LockPoint::TotalCost`) nothing changes the total
/// ([CR#601.2h]'s sacrificed-cost-reducer example); payment-stage
/// substitutions (the cost-modification hook: convoke/delve/…,
/// [CR#702.51b]) edit HOW it is paid, never the total. Paying a changed
/// cost still pays the original ([CR#118.7,118.11]).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TotalCost {
    pub base: Vec<CostComponent>,
    /// Applied modification steps, in application order ([CR#601.2f]).
    pub trace: Vec<crate::CostChange>,
    /// Set at [CR#601.2f]; a locked total never moves.
    pub locked: bool,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mana::ManaCost;
    use crate::mana::ManaSymbol;
    use crate::mana::SimpleManaSymbol;
    use crate::reference::Reference;
    use crate::selection::Selection;

    fn read(source: &str) -> CostComponent {
        crate::ron::options().from_str(source).unwrap()
    }

    #[test]
    fn cost_components_parse() {
        use crate::action::PlayerAction;

        assert_eq!(
            read("Mana([Generic(2)])"),
            CostComponent::Mana(ManaCost::from(vec![ManaSymbol::Simple(
                SimpleManaSymbol::Generic(2)
            )])),
        );
        assert_eq!(read("Tap"), CostComponent::Tap);
        assert_eq!(
            read("Do(Sacrifice(This))"),
            CostComponent::Do(Box::new(PlayerAction::Sacrifice(Selection::from(
                Reference::This
            )))),
        );
    }

    #[test]
    fn cost_list_round_trips() {
        let source = "[Mana([Generic(2)]),Tap,Do(Sacrifice(This))]";
        let parsed: Vec<CostComponent> = crate::ron::options().from_str(source).unwrap();
        let written = crate::ron::options().to_string(&parsed).unwrap();
        let reparsed: Vec<CostComponent> = crate::ron::options().from_str(&written).unwrap();
        assert_eq!(parsed, reparsed);
    }
}
