use std::sync::Arc;

use serde::Deserialize;
use serde::Serialize;

use crate::Binder;
use crate::Cmp;
use crate::Count;
use crate::Expand;
use crate::Expansion;
use crate::Normalize;
use crate::Predicate;
use crate::Stat;
use crate::SupportsMacros;
use crate::mana::ManaCost;
use crate::reference::Reference;

/// A single component of an ability's cost ([CR#601.2b]).
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum CostComponent {
    /// Mana payment, e.g. `Mana([Generic(2)])`.
    Mana(ManaCost),
    /// Pay mana equal to a referenced object's printed mana cost
    /// ([CR#202.1]) — the full *colored* cost, the cost-language twin of the
    /// numeric `ManaValueOf` read. Spells the granted-flashback "the flashback
    /// cost is equal to its mana cost" (Snapcaster Mage), where the referenced
    /// object is the card the flashback ability rides on (`This`). The engine
    /// resolves the reference, reads that object's mana cost, and requires
    /// paying it ([CR#601.2h]).
    ManaCostOf(Reference),
    /// The {T} symbol ([CR#107.5]).
    Tap,
    /// The {Q} symbol.
    Untap,
    /// Pay by performing an action ([CR#118.3]) — the Idris `Do : Action b
    /// -> Cost b`. The payer is `You` in cost context — spelled explicitly on
    /// every agent-bearing verb (`Do(Sacrifice(You, This))`, Law 2: no
    /// read-time default); holding the full [`Action`](crate::Action) is
    /// what lets a keyword-action composite be a cost — "Discard a card:" is
    /// `Do(Discard(1))`, cycling's "Discard this card:" the bound
    /// [`discard_what`](crate::Action::discard_what) form
    /// ([CR#701.9,702.29a]). Only cost-eligible actions
    /// ([`Action::is_cost_eligible`](crate::Action::is_cost_eligible))
    /// belong here — enforced by the cards crate's validation lint, not the
    /// parser. Boxed: `Action` dwarfs the other variants, and
    /// `CostComponent` rides in `Vec<CostComponent>` cost lists, so an
    /// unboxed variant would size every element to it
    /// (`clippy::large_enum_variant`).
    Do(Arc<crate::Action>),
    /// A *nested* cost list. It exists only to let a macro splice a
    /// list-valued cost param into a larger cost list — the body writes
    /// `cost: [Cost(Param(0)), Do(Discard(…))]`, so the spliced `[Mana(…)]`
    /// reads as `Cost([Mana(…)])` (cycling, [CR#702.29a]). Read is faithful:
    /// a nested `Cost` SURVIVES deserialization verbatim. [`Cost::normalize`]
    /// is what splices it into the surrounding list — call it at the boundary
    /// before consuming a (possibly macro-spliced) cost.
    Cost(Cost),
    /// An *aggregate-stat* cost: tap a chosen subset of the permanents matching
    /// `filter` whose summed `stat` satisfies `cmp` `count` ([CR#601.2b],
    /// tapping [CR#107.5]). The one shape for Crew — "Crew N" = "tap any number
    /// of other untapped creatures you control with total power N or greater"
    /// ([CR#702.122a]) is `TapTotal(Power, AtLeast, N, <those creatures>)` —
    /// and the convoke/devotion-scaling cost family the engine authors
    /// flagged it should subsume. The payer chooses which qualifying
    /// permanents to tap; the engine taps a subset whose summed `stat`
    /// meets the bound. `stat` is a numeric axis (power/toughness/defense).
    /// `filter` is an open [`Predicate`], so it stays plugin-safe; it is boxed
    /// because an open filter is large and `CostComponent` rides in
    /// `Vec<CostComponent>` cost lists, so an unboxed field would size
    /// every element to it (`clippy::large_enum_variant`).
    ///
    /// A struct variant (it reads flat in RON through a generated helper
    /// struct, like [`Condition::Happened`](crate::Condition)): four fields
    /// exceed the `SupportsMacros` tuple-variant arity, and the named
    /// fields read better than four bare positionals.
    TapTotal {
        stat: Stat,
        cmp: Cmp,
        count: Count,
        filter: Arc<Predicate>,
    },
    /// A choice/bind step made BEFORE the cost actions it scopes
    /// ([CR#601.2b]) — the cost-level twin of
    /// [`OneShotEffect::With`](crate::OneShotEffect). The `binder` makes
    /// the choice (e.g. `ChooseOne(Creature)`) and binds it
    /// as [`Reference::That`](crate::Reference)/
    /// [`Selection::That`](crate::Selection), then `body` (a nested cost)
    /// pays using that binding: "sacrifice a creature" = `With(binder:
    /// ChooseOne(Creature), body: [Do(Sacrifice(That))])`. Keeps choosing
    /// OUT of the verb — the cost action receives an already-bound
    /// reference. `binder` is boxed (an open `Binder` is large and
    /// `CostComponent` rides in `Vec<CostComponent>` cost lists).
    With { binder: Arc<Binder>, body: Cost },
    /// A remembered `CostComponent` macro invocation (`SacrificeThis`, loyalty
    /// sugar, …).
    #[macro_ron(expanded)]
    Expanded(Expansion<CostComponent>),
}

impl CostComponent {
    /// Pay by performing a full [`Action`](crate::Action) — the
    /// keyword-action composite forms ("Discard a card:" —
    /// [CR#701.9,601.2b]).
    #[must_use]
    pub fn do_action(action: crate::Action) -> CostComponent {
        CostComponent::Do(Arc::new(action))
    }
}

/// A cost: an ordered list of [`CostComponent`]s ([CR#601.2b]). A newtype
/// (not a bare `Vec`) so it can carry a [`Normalize`] impl. Read is FAITHFUL:
/// a nested cost — a [`CostComponent::Cost`] spliced in by a macro whose cost
/// param is itself a list — survives deserialization verbatim. A macro body
/// writes `[Param(0), Do(…)]` where `Param(0)` expands to `[Mana(…)]`; that
/// reads as the lumpy `[Cost([Mana(…)]), Do(…)]` and STAYS lumpy (cycling,
/// [CR#702.29a]). [`Cost::normalize`] is the explicit post-read step that
/// splices the nested `Cost` back into one flat list, yielding
/// `[Mana(…), Do(…)]`. Serializes and deserializes transparently as the bare
/// list.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Deserialize, Expand, Serialize)]
#[serde(transparent)]
pub struct Cost(pub Arc<[CostComponent]>);

impl Normalize for CostComponent {
    /// Recurse into a nested cost; every other variant is a leaf for
    /// normalization (no in-scope structural redundancy below it).
    fn normalize(self) -> Self {
        match self {
            CostComponent::Cost(inner) => CostComponent::Cost(inner.normalize()),
            // Recurse into a `With` step's scoped body so a macro-spliced nested
            // cost there still flattens.
            CostComponent::With { binder, body } => CostComponent::With {
                binder,
                body: body.normalize(),
            },
            other => other,
        }
    }
}

impl Normalize for Cost {
    /// Splice every [`CostComponent::Cost`] one level into the surrounding
    /// list (associativity of cost concatenation, [CR#601.2b]) — the inner
    /// list is already normalized by the per-component recursion, so one pass
    /// flattens arbitrarily-deep nesting. This is the explicit post-read
    /// replacement for the old read-time flatten: a macro-spliced cost reads
    /// lumpy and `.normalize()` collapses it (cycling, [CR#702.29a]).
    fn normalize(self) -> Self {
        let mut flat: Vec<CostComponent> = Vec::with_capacity(self.0.len());
        for component in self.0.iter().cloned() {
            match component.normalize() {
                CostComponent::Cost(inner) => flat.extend(inner.0.iter().cloned()),
                other => flat.push(other),
            }
        }
        Cost(flat.into())
    }
}

impl std::ops::Deref for Cost {
    type Target = Arc<[CostComponent]>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl From<Arc<[CostComponent]>> for Cost {
    fn from(components: Arc<[CostComponent]>) -> Self {
        Cost(components)
    }
}

impl<'a> IntoIterator for &'a Cost {
    type Item = &'a CostComponent;
    type IntoIter = std::slice::Iter<'a, CostComponent>;
    fn into_iter(self) -> Self::IntoIter {
        self.0.iter()
    }
}

/// A bare-identifier NAME for an optional cost ([CR#702.33e,607] — kicker's
/// linked "if it was kicked" readers refer to the specific kicker ability by
/// identity). Written as a bare ident in RON (`tag: Kicker`), mirroring
/// [`CounterRef`](crate::CounterRef)/[`KeywordRef`](crate::KeywordRef).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct CostTag(pub crate::Ident);

impl CostTag {
    #[must_use]
    pub fn as_str(&self) -> &'static str {
        self.0.as_str()
    }
}

impl From<&str> for CostTag {
    fn from(s: &str) -> Self {
        CostTag(s.into())
    }
}

impl crate::Expand for CostTag {
    // A leaf: a name, never an expandable value.
    fn expand_all(self) -> Self {
        self
    }
}

impl Serialize for CostTag {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // A unit variant writes as a bare identifier in RON.
        serializer.serialize_unit_variant("CostTag", 0, self.0.as_str())
    }
}

impl<'de> Deserialize<'de> for CostTag {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // A bare identifier is a unit enum variant in the serde data model —
        // the same channel `CounterRef`/`KeywordRef` read through.
        struct NameVisitor;
        impl<'de> serde::de::Visitor<'de> for NameVisitor {
            type Value = CostTag;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("a cost-tag name (bare identifier)")
            }
            fn visit_enum<A: serde::de::EnumAccess<'de>>(
                self,
                data: A,
            ) -> Result<Self::Value, A::Error> {
                use serde::de::VariantAccess;
                let (ident, variant) = data.variant_seed(macro_ron::IdentSeed)?;
                variant.unit_variant()?;
                Ok(CostTag(ident))
            }
        }
        deserializer.deserialize_enum("", &[], NameVisitor)
    }
}

/// A declared OPTIONAL cost ([CR#118.8b] "you may pay an additional [cost] as
/// you cast this spell") — the kicker/multikicker/buyback identity, carried by
/// `StaticEffect::CostOption`. One `tag`, three read channels:
/// `Condition::PaidCost(tag)` (was it paid — kicked, [CR#702.33d]),
/// `Count::TimesPaid(tag)` (how many times — multikicker, [CR#702.33c]), and
/// `Predicate::WasPaidWith(tag)` (an object whose cost was paid with it,
/// [CR#702.33e,607.2]). `repeatable: true` is multikicker's "any number of
/// times" ([CR#702.33c]); buyback is one more tag ([CR#702.27a]). Intentions
/// are announced at [CR#601.2b]; the total locks at [CR#601.2f].
#[derive(Debug, Clone, PartialEq, Eq, Hash, Deserialize, Expand, Serialize)]
pub struct OptionalCost {
    pub components: Arc<[CostComponent]>,
    pub tag: CostTag,
    #[serde(default, skip_serializing_if = "crate::ability::is_false")]
    pub repeatable: bool,
}

/// The total-cost record of the [CR#601.2f] pipeline — an ENGINE-traffic
/// value, not card grammar: base (mana or alternative, per [CR#601.2b]) →
/// the `trace` of applied steps (`CostChange`: additional/increases, then
/// reductions, [CR#601.2f]) → mana floor → direct effects → `locked`.
/// After the lock (`LockPoint::TotalCost`) nothing changes the total
/// ([CR#601.2h]'s sacrificed-cost-reducer example); payment-stage
/// substitutions (the cost-modification hook: convoke/delve/…,
/// [CR#702.51b]) edit HOW it is paid, never the total. Paying a changed
/// cost still pays the original ([CR#118.7,118.11]).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TotalCost {
    pub base: Arc<[CostComponent]>,
    /// Applied modification steps, in application order ([CR#601.2f]).
    pub trace: Arc<[crate::CostChange]>,
    /// Set at [CR#601.2f]; a locked total never moves.
    pub locked: bool,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mana::ManaCost;
    use crate::mana::ManaSymbol;
    use crate::mana::SimpleManaSymbol;
    use crate::reference::Reference;

    fn read(source: &str) -> CostComponent {
        crate::ron::options().from_str(source).unwrap()
    }

    fn to_string(value: &CostComponent) -> String {
        crate::ron::options().to_string(value).unwrap()
    }

    /// The cost-level `With` step keeps choosing OUT of the verb — it binds the
    /// choice as `Reference::That` BEFORE the action that pays. And exile,
    /// being a pure zone move, is paid as `Do(Move(This, Exile))`
    /// (Scavenge), not a dedicated verb. Both round-trip.
    #[test]
    fn with_choice_step_and_move_are_cost_forms() {
        use crate::Binder;
        use crate::CharacteristicPredicate;
        use crate::Predicate;
        use crate::Type;

        // "sacrifice a creature": choose one creature, then Sacrifice(You,
        // That(Creature)).
        let creature =
            Predicate::Characteristic(CharacteristicPredicate::Supertype(crate::Supertype::Basic));
        let with = CostComponent::With {
            binder: Arc::new(Binder::ChooseOne {
                filter: creature,
                by: Reference::You,
            }),
            body: Cost(
                vec![CostComponent::do_action(crate::Action::Sacrifice(
                    Reference::You,
                    Reference::That(crate::Sort::OfType(Type::Creature)),
                ))]
                .into(),
            ),
        };
        assert_eq!(read(&to_string(&with)), with, "With cost round-trips");

        // Exile-as-cost is a Move to the Exile zone — `Action::Move` is
        // agent-silent, so this spells with no agent slot.
        let exile =
            CostComponent::do_action(crate::Action::move_to(Reference::This, crate::Zone::Exile));
        assert_eq!(
            read(&to_string(&exile)),
            exile,
            "Do(Move(This, Exile)) round-trips"
        );
    }

    /// Read is FAITHFUL: a nested `Cost` component survives deserialization
    /// verbatim (the macro-splice shape stays lumpy), and `.normalize()` is the
    /// explicit step that splices it into one flat list. This is what lets a
    /// macro splice a list-valued cost param into a larger cost list:
    /// `cost: [Cost(Param(0)), Do(…)]` where `Param(0)` expands to `[Mana(…)]`
    /// reads as `[Cost([Mana(…)]), Do(…)]`, and normalization collapses it to
    /// `[Mana(…), Do(…)]` (cycling, [CR#702.29a]).
    #[test]
    fn nested_cost_survives_read_and_normalizes_flat() {
        // The named Cost variant wraps a sub-list.
        let comp: CostComponent = crate::ron::options().from_str("Cost([Tap])").unwrap();
        assert!(
            matches!(comp, CostComponent::Cost(_)),
            "Cost([…]) reads as the Cost variant, got {comp:?}"
        );

        // Faithful read: the nested Cost SURVIVES verbatim — no read-time flatten.
        let lumpy: Cost = crate::ron::options()
            .from_str(
                "[Cost([Mana([Generic(2)])]), \
                 Do(Composite(name: Discard, body: Move(This, Graveyard)))]",
            )
            .unwrap();
        let mana_two = CostComponent::Mana(ManaCost::from(Arc::<[ManaSymbol]>::from(vec![
            ManaSymbol::Simple(SimpleManaSymbol::Generic(2)),
        ])));
        let discard_self = CostComponent::do_action(crate::Action::discard_what(Reference::This));
        assert_eq!(
            lumpy,
            Cost(
                vec![
                    CostComponent::Cost(Cost(vec![mana_two.clone()].into())),
                    discard_self.clone(),
                ]
                .into()
            ),
            "read preserves the lumpy macro-splice shape",
        );

        // `.normalize()` splices the nested Cost into one flat list.
        assert_eq!(
            lumpy.normalize(),
            Cost(vec![mana_two, discard_self].into()),
            "normalize collapses the nested Cost",
        );
    }

    /// Normalization is one-pass over arbitrary nesting depth (the inner list
    /// is normalized before its parent splices it) and idempotent.
    #[test]
    fn normalize_flattens_deeply_and_is_idempotent() {
        let deep: Cost = crate::ron::options()
            .from_str("[Cost([Cost([Tap]), Untap])]")
            .unwrap();
        let flat = deep.normalize();
        assert_eq!(
            flat,
            Cost(vec![CostComponent::Tap, CostComponent::Untap].into())
        );
        assert_eq!(flat.clone().normalize(), flat, "normalize is idempotent");
    }

    #[test]
    fn cost_components_parse() {
        assert_eq!(
            read("Mana([Generic(2)])"),
            CostComponent::Mana(ManaCost::from(Arc::<[ManaSymbol]>::from(vec![
                ManaSymbol::Simple(SimpleManaSymbol::Generic(2)),
            ]))),
        );
        assert_eq!(read("Tap"), CostComponent::Tap);
        assert_eq!(
            read("Do(Sacrifice(You, This))"),
            CostComponent::do_action(crate::Action::Sacrifice(Reference::You, Reference::This)),
        );
    }

    /// `ManaCostOf(Reference)` reads and round-trips through the
    /// `SupportsMacros` serde (a referenced object's mana cost,
    /// [CR#202.1]).
    #[test]
    fn mana_cost_of_round_trips() {
        assert_eq!(
            read("ManaCostOf(This)"),
            CostComponent::ManaCostOf(Reference::This),
        );
        let v = CostComponent::ManaCostOf(Reference::ControllerOf(Arc::new(Reference::This)));
        let written = crate::ron::options().to_string(&v).unwrap();
        assert_eq!(read(&written), v, "round-trips: {written}");
    }

    /// `TapTotal(stat, cmp, count, filter)` reads flat and round-trips — the
    /// aggregate-stat (Crew) cost shape ([CR#702.122a]). The `filter` field is
    /// a boxed open [`Predicate`], so a bare `Type(Creature)` reads into it
    /// transparently.
    #[test]
    fn tap_total_reads_and_round_trips() {
        use crate::Cmp;
        use crate::Count;
        use crate::Predicate;
        use crate::Stat;

        // The Crew shape: "tap any number of creatures with total power 3 or
        // greater" ([CR#702.122a]).
        let crew = CostComponent::TapTotal {
            stat: Stat::Power,
            cmp: Cmp::AtLeast,
            count: Count::Literal(3),
            filter: Arc::new(Predicate::Characteristic(
                crate::CharacteristicPredicate::Supertype(crate::Supertype::Basic),
            )),
        };
        assert_eq!(
            read("TapTotal(stat: Power, cmp: AtLeast, count: 3, filter: Supertype(Basic))"),
            crew,
        );

        // Serialize -> read is identity (the highest-risk arm — a 4-field tuple
        // variant with a boxed filter and a bare-literal count).
        let written = crate::ron::options().to_string(&crew).unwrap();
        assert_eq!(read(&written), crew, "round-trips: {written}");
    }

    /// `OptionalCost` — the kicker/multikicker/buyback identity
    /// ([CR#118.8b,702.33a]) — reads flat with a bare-ident tag, omits the
    /// default `repeatable: false`, and round-trips; `repeatable: true` is
    /// multikicker ([CR#702.33c]).
    #[test]
    fn optional_cost_round_trips() {
        let kicker: crate::OptionalCost = crate::ron::options()
            .from_str("(components: [Mana([Generic(2)])], tag: Kicker)")
            .unwrap();
        assert_eq!(kicker.tag, crate::CostTag::from("Kicker"));
        assert!(!kicker.repeatable, "repeatable defaults false");
        let written = crate::ron::options().to_string(&kicker).unwrap();
        assert!(
            !written.contains("repeatable"),
            "default repeatable omitted: {written}"
        );
        assert!(
            written.contains("tag:Kicker"),
            "tag writes as a bare ident: {written}"
        );
        let reread: crate::OptionalCost = crate::ron::options().from_str(&written).unwrap();
        assert_eq!(reread, kicker);

        let multi: crate::OptionalCost = crate::ron::options()
            .from_str("(components: [Mana([Generic(1)])], tag: Multikicker, repeatable: true)")
            .unwrap();
        assert!(multi.repeatable);
        let written = crate::ron::options().to_string(&multi).unwrap();
        let reread: crate::OptionalCost = crate::ron::options().from_str(&written).unwrap();
        assert_eq!(reread, multi);
    }

    #[test]
    fn cost_list_round_trips() {
        // `Sacrifice` carries its agent slot explicitly now ([CR#701.21a]
        // "its controller"); in a cost, `You` is the payer.
        let source = "[Mana([Generic(2)]),Tap,Do(Sacrifice(You, This))]";
        let parsed: Arc<[CostComponent]> = crate::ron::options().from_str(source).unwrap();
        let written = crate::ron::options().to_string(&parsed).unwrap();
        let reparsed: Arc<[CostComponent]> = crate::ron::options().from_str(&written).unwrap();
        assert_eq!(parsed, reparsed);
    }
}
