use serde::Deserialize;
use serde::Serialize;

use crate::Expand;
use crate::Expansion;
use crate::Normalize;
use crate::SupportsMacros;
use crate::action::PlayerAction;
use crate::mana::ManaCost;
use crate::reference::Reference;

/// A single component of an ability's cost ([CR#601.2b]).
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum CostComponent {
    /// Mana payment, e.g. `Mana([Generic(2)])`.
    Mana(ManaCost),
    /// Pay mana equal to a referenced object's printed mana cost
    /// ([CR#202.1]) — the full *colored* cost, the cost-language twin of the
    /// numeric `ManaValueOf` read. Spells the granted-flashback "the flashback
    /// cost is equal to its mana cost" (Snapcaster Mage), where the referenced
    /// object is the card the flashback ability rides on (`This`). The engine
    /// resolves the reference, reads that object's mana cost, and requires
    /// paying it ([CR#601.2h]).
    ManaCostOf(Reference),
    /// The {T} symbol ([CR#107.5]).
    Tap,
    /// The {Q} symbol.
    Untap,
    /// Pay by performing a verb: the payer is implicitly you, so this holds a
    /// bare [`PlayerAction`] (no `By` wrapper). Only cost-eligible ones
    /// (`PlayerAction::is_cost_eligible`) belong here — enforced by the cards
    /// crate's validation lint, not the parser. Boxed: `PlayerAction` dwarfs
    /// the other variants, and `CostComponent` rides in `Vec<CostComponent>`
    /// cost lists, so an unboxed variant would size every element to it
    /// (`clippy::large_enum_variant`).
    Do(Box<PlayerAction>),
    /// A *nested* cost list. It exists only to let a macro splice a
    /// list-valued cost param into a larger cost list — the body writes
    /// `cost: [Cost(Param(0)), Do(Discard(…))]`, so the spliced `[Mana(…)]`
    /// reads as `Cost([Mana(…)])` (cycling, [CR#702.29a]). Read is faithful:
    /// a nested `Cost` SURVIVES deserialization verbatim. [`Cost::normalize`]
    /// is what splices it into the surrounding list — call it at the boundary
    /// before consuming a (possibly macro-spliced) cost.
    Cost(Cost),
    /// A remembered `CostComponent` macro invocation (`SacrificeThis`, loyalty
    /// sugar, …).
    #[macro_ron(expanded)]
    Expanded(Expansion<CostComponent>),
}

impl CostComponent {
    /// Pay by performing a (cost-eligible) player verb —
    /// `Do(Box::new(action))`, hiding the box the boxed variant requires.
    /// Eligibility itself stays a cards-layer validation lint ([CR#601.2b],
    /// `PlayerAction::is_cost_eligible`).
    #[must_use]
    pub fn do_(action: PlayerAction) -> CostComponent {
        CostComponent::Do(Box::new(action))
    }
}

/// A cost: an ordered list of [`CostComponent`]s ([CR#601.2b]). A newtype
/// (not a bare `Vec`) so it can carry a [`Normalize`] impl. Read is FAITHFUL:
/// a nested cost — a [`CostComponent::Cost`] spliced in by a macro whose cost
/// param is itself a list — survives deserialization verbatim. A macro body
/// writes `[Param(0), Do(…)]` where `Param(0)` expands to `[Mana(…)]`; that
/// reads as the lumpy `[Cost([Mana(…)]), Do(…)]` and STAYS lumpy (cycling,
/// [CR#702.29a]). [`Cost::normalize`] is the explicit post-read step that
/// splices the nested `Cost` back into one flat list, yielding
/// `[Mana(…), Do(…)]`. Serializes and deserializes transparently as the bare
/// list.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Deserialize, Expand, Serialize)]
#[serde(transparent)]
pub struct Cost(pub Vec<CostComponent>);

impl Normalize for CostComponent {
    /// Recurse into a nested cost; every other variant is a leaf for
    /// normalization (no in-scope structural redundancy below it).
    fn normalize(self) -> Self {
        match self {
            CostComponent::Cost(inner) => CostComponent::Cost(inner.normalize()),
            other => other,
        }
    }
}

impl Normalize for Cost {
    /// Splice every [`CostComponent::Cost`] one level into the surrounding
    /// list (associativity of cost concatenation, [CR#601.2b]) — the inner
    /// list is already normalized by the per-component recursion, so one pass
    /// flattens arbitrarily-deep nesting. This is the explicit post-read
    /// replacement for the old read-time flatten: a macro-spliced cost reads
    /// lumpy and `.normalize()` collapses it (cycling, [CR#702.29a]).
    fn normalize(self) -> Self {
        let mut flat = Vec::with_capacity(self.0.len());
        for component in self.0 {
            match component.normalize() {
                CostComponent::Cost(inner) => flat.extend(inner.0),
                other => flat.push(other),
            }
        }
        Cost(flat)
    }
}

impl std::ops::Deref for Cost {
    type Target = Vec<CostComponent>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl From<Vec<CostComponent>> for Cost {
    fn from(components: Vec<CostComponent>) -> Self {
        Cost(components)
    }
}

impl<'a> IntoIterator for &'a Cost {
    type Item = &'a CostComponent;
    type IntoIter = std::slice::Iter<'a, CostComponent>;
    fn into_iter(self) -> Self::IntoIter {
        self.0.iter()
    }
}

/// The total-cost record of the [CR#601.2f] pipeline — an ENGINE-traffic
/// value, not card grammar: base (mana or alternative, per [CR#601.2b]) →
/// the `trace` of applied steps (`CostChange`: additional/increases, then
/// reductions, [CR#601.2f]) → mana floor → direct effects → `locked`.
/// After the lock (`LockPoint::TotalCost`) nothing changes the total
/// ([CR#601.2h]'s sacrificed-cost-reducer example); payment-stage
/// substitutions (the cost-modification hook: convoke/delve/…,
/// [CR#702.51b]) edit HOW it is paid, never the total. Paying a changed
/// cost still pays the original ([CR#118.7,118.11]).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TotalCost {
    pub base: Vec<CostComponent>,
    /// Applied modification steps, in application order ([CR#601.2f]).
    pub trace: Vec<crate::CostChange>,
    /// Set at [CR#601.2f]; a locked total never moves.
    pub locked: bool,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mana::ManaCost;
    use crate::mana::ManaSymbol;
    use crate::mana::SimpleManaSymbol;
    use crate::reference::Reference;
    use crate::selection::Selection;

    fn read(source: &str) -> CostComponent {
        crate::ron::options().from_str(source).unwrap()
    }

    /// Read is FAITHFUL: a nested `Cost` component survives deserialization
    /// verbatim (the macro-splice shape stays lumpy), and `.normalize()` is the
    /// explicit step that splices it into one flat list. This is what lets a
    /// macro splice a list-valued cost param into a larger cost list:
    /// `cost: [Cost(Param(0)), Do(…)]` where `Param(0)` expands to `[Mana(…)]`
    /// reads as `[Cost([Mana(…)]), Do(…)]`, and normalization collapses it to
    /// `[Mana(…), Do(…)]` (cycling, [CR#702.29a]).
    #[test]
    fn nested_cost_survives_read_and_normalizes_flat() {
        use crate::action::PlayerAction;
        use crate::count::Count;

        // The named Cost variant wraps a sub-list.
        let comp: CostComponent = crate::ron::options().from_str("Cost([Tap])").unwrap();
        assert!(
            matches!(comp, CostComponent::Cost(_)),
            "Cost([…]) reads as the Cost variant, got {comp:?}"
        );

        // Faithful read: the nested Cost SURVIVES verbatim — no read-time flatten.
        let lumpy: Cost = crate::ron::options()
            .from_str("[Cost([Mana([Generic(2)])]), Do(Discard(count: Literal(1), what: This))]")
            .unwrap();
        let mana_two = CostComponent::Mana(ManaCost::from(vec![ManaSymbol::Simple(
            SimpleManaSymbol::Generic(2),
        )]));
        let discard_self = CostComponent::Do(Box::new(PlayerAction::Discard {
            count: Count::Literal(1),
            what: Some(Selection::Ref(Reference::This)),
        }));
        assert_eq!(
            lumpy,
            Cost(vec![
                CostComponent::Cost(Cost(vec![mana_two.clone()])),
                discard_self.clone(),
            ]),
            "read preserves the lumpy macro-splice shape",
        );

        // `.normalize()` splices the nested Cost into one flat list.
        assert_eq!(
            lumpy.normalize(),
            Cost(vec![mana_two, discard_self]),
            "normalize collapses the nested Cost",
        );
    }

    /// Normalization is one-pass over arbitrary nesting depth (the inner list
    /// is normalized before its parent splices it) and idempotent.
    #[test]
    fn normalize_flattens_deeply_and_is_idempotent() {
        let deep: Cost = crate::ron::options()
            .from_str("[Cost([Cost([Tap]), Untap])]")
            .unwrap();
        let flat = deep.normalize();
        assert_eq!(flat, Cost(vec![CostComponent::Tap, CostComponent::Untap]));
        assert_eq!(flat.clone().normalize(), flat, "normalize is idempotent");
    }

    #[test]
    fn cost_components_parse() {
        use crate::action::PlayerAction;

        assert_eq!(
            read("Mana([Generic(2)])"),
            CostComponent::Mana(ManaCost::from(vec![ManaSymbol::Simple(
                SimpleManaSymbol::Generic(2)
            )])),
        );
        assert_eq!(read("Tap"), CostComponent::Tap);
        assert_eq!(
            read("Do(Sacrifice(This))"),
            CostComponent::Do(Box::new(PlayerAction::Sacrifice(Selection::from(
                Reference::This
            )))),
        );
    }

    /// `ManaCostOf(Reference)` reads and round-trips through the
    /// `SupportsMacros` serde (a referenced object's mana cost,
    /// [CR#202.1]).
    #[test]
    fn mana_cost_of_round_trips() {
        assert_eq!(
            read("ManaCostOf(This)"),
            CostComponent::ManaCostOf(Reference::This),
        );
        let v = CostComponent::ManaCostOf(Reference::ControllerOf(Box::new(Reference::This)));
        let written = crate::ron::options().to_string(&v).unwrap();
        assert_eq!(read(&written), v, "round-trips: {written}");
    }

    #[test]
    fn cost_list_round_trips() {
        let source = "[Mana([Generic(2)]),Tap,Do(Sacrifice(This))]";
        let parsed: Vec<CostComponent> = crate::ron::options().from_str(source).unwrap();
        let written = crate::ron::options().to_string(&parsed).unwrap();
        let reparsed: Vec<CostComponent> = crate::ron::options().from_str(&written).unwrap();
        assert_eq!(parsed, reparsed);
    }
}
