use serde::Deserialize;
use serde::Serialize;

use crate::Expand;
use crate::Expansion;
use crate::Filter;
use crate::Reference;
use crate::SupportsMacros;

/// A measurable characteristic of an object, read by `Count::StatOf`
/// ([CR#109.3,208,209,210]). The open part (mana value, loyalty, defense) is
/// finite; new printed stats are rare and get a variant when one arrives.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Expand, Serialize)]
pub enum Stat {
    /// [CR#208].
    Power,
    /// [CR#208].
    Toughness,
    /// [CR#202.3].
    ManaValue,
    /// [CR#209] (planeswalker).
    Loyalty,
    /// [CR#210] (battle).
    Defense,
}

/// The engine-tracked history counters `Count::Query` bridges to
/// (read off the engine's event-history log; turn-scoped unless noted).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Deserialize, Expand, serde::Serialize)]
pub enum QueryKey {
    /// Cards the evaluating player drew this turn ([CR#121]).
    CardsDrawnThisTurn,
    /// Lands the evaluating player played this turn ([CR#305.2]).
    LandsPlayedThisTurn,
    /// Spells cast before this one this turn (storm, [CR#702.40a]).
    StormCount,
    /// Life the evaluating player has lost this turn ([CR#119.3]).
    LifeLostThisTurn,
    /// Life the evaluating player has gained this turn ([CR#119.3]).
    LifeGainedThisTurn,
}

/// A scalar magnitude an effect computes at resolution: an amount, never an
/// object (objects are `Reference`s, [CR#107.1,107.3]).
///
/// A literal is a bare numeral: `3`, never `Literal(3)` — the `Literal(…)`
/// wrapper is pure noise and never appears in RON. The derive's `literal`
/// marker gives the variant the `StatValue::Number` treatment: it serializes
/// its inner value bare and deserializes a bare numeral back (a tagged
/// `Literal(3)` still reads, for leniency). Full macro interception still
/// applies at and under `Count` positions.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back, and `Literal` is the bare-numeral variant.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Count {
    /// The value chosen for {X} as the spell or ability was put on the
    /// stack ([CR#107.3]).
    X,
    /// How many objects match a filter ([CR#107.3], "for each"). Boxed to
    /// break the `Filter` → `Stat` → `Count` → `Filter` size cycle.
    CountOf(Box<Filter>),
    /// A referenced object's stat ([CR#107.3], "equal to its power").
    StatOf(Reference, Stat),
    /// How many counters of the named kind sit on a referenced object or
    /// player proxy ([CR#122.1]) — "for each +1/+1 counter on ~", and the
    /// magnitude a counter's own conferred effect scales by (a +1/+1 counter
    /// confers `AddPower(CounterCount(This, P1P1Counter))`). The kind is a bare
    /// `CounterRef`, not a string. The `Reference` is boxed (it is 80 bytes) so
    /// this variant doesn't make `Count` larger than its `StatOf` peer.
    CounterCount(Box<Reference>, crate::CounterRef),
    /// The smaller of two counts — the +1/+1 vs -1/-1 annihilation removes
    /// `Min(CounterCount(+1/+1), CounterCount(-1/-1))` of each ([CR#704.5q]),
    /// and "the lesser of X and Y" appears across the card base. Boxed to keep
    /// `Count` small.
    Min(Box<Count>, Box<Count>),
    /// Magnitude anaphora: "that much" / "that many" — the amount fixed by
    /// an earlier instruction ([CR#107.3]).
    ThatMuch,
    /// An engine-tracked tally ([CR#608.2i] history reads — storm,
    /// lands-this-turn, cards-drawn), keyed like `Stat`.
    Query(QueryKey),
    /// A noted number read back from a slot ([CR#607.2] linked values).
    Noted(crate::Ident),
    /// A remembered `Count` macro invocation.
    #[macro_ron(expanded)]
    Expanded(Expansion<Count>),
    /// A bare integer literal — `3`, with no `Literal(…)` wrapper in RON.
    #[macro_ron(literal)]
    Literal(crate::Uint),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::reference::Reference;

    fn read(source: &str) -> Count {
        crate::ron::options().from_str(source).unwrap()
    }
    fn write(count: &Count) -> String {
        crate::ron::options().to_string(count).unwrap()
    }

    /// A bare numeral IS core grammar: `3` reads as `Literal(3)`, and
    /// `Literal(3)` writes back bare. `Literal(N)` is read/write noise the
    /// grammar elides — the literal wrapper has no tagged spelling to carry.
    #[test]
    fn literal_reads_and_writes_bare() {
        assert_eq!(read("3"), Count::Literal(3));
        assert_eq!(write(&Count::Literal(3)), "3");
    }

    #[test]
    fn constructors_read_named() {
        assert_eq!(read("X"), Count::X);
        assert_eq!(read("ThatMuch"), Count::ThatMuch);
        assert_eq!(
            read("StatOf(This, Power)"),
            Count::StatOf(Reference::This, Stat::Power),
        );
    }

    /// The 2-field tuple variant pins the derived `Serialize` round-trip —
    /// serialize → read is identity (the highest-risk arm).
    #[test]
    fn stat_of_round_trips() {
        let value = Count::StatOf(Reference::This, Stat::Power);
        let written = crate::ron::options().to_string(&value).unwrap();
        assert_eq!(read(&written), value);
    }

    /// The exact shape the dynamic-count parser emits must read back into core.
    #[test]
    fn count_of_filter_reads() {
        let value = read(r#"CountOf(AllOf([Subtype("Goblin"), ControlledBy(Ref(You))]))"#);
        assert!(matches!(value, Count::CountOf(_)));
    }
}
