//! The deontic layer ([CR#101.2,601.3]): clauses gating whether a *proposed
//! action* is legal. Boundary ([CR#614.17]): "doesn't"/"skip"/can't-happen
//! over events are replacement-family, never deontic; outcome "can't"s
//! ([CR#104]) are SBA-override machinery, also not here.

use serde::Deserialize;
use serde::Serialize;

use crate::Cmp;
use crate::CostComponent;
use crate::Count;
use crate::Expand;
use crate::Expansion;
use crate::Filter;
use crate::SupportsMacros;
use crate::Zone;

/// A cast/play timing window ([CR#117.1a..117.1b]). Closed vocabulary;
/// `SorcerySpeed` arrives with the deferred `Only` work.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Serialize, Expand)]
pub enum CastWindow {
    /// Any time you could cast an instant (flash, [CR#702.8a]).
    InstantSpeed,
}

/// A proposed-action pattern — the typed verb the deontic polarities range
/// over. Closed core enum (the engine pattern-matches it); openness comes
/// from macro interception at the `Deontic`/`Ability` positions. Slots
/// default to match-anything; the carrier side is spelled `Is(This)`.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: struct
/// variants read flat in RON through generated helper structs (carrying the
/// forwarded `#[serde(...)]` field defaults) + `unwrap_variant_newtypes`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum DeonticAction {
    /// `by` attacks `on` — a player/planeswalker/battle set
    /// ([CR#508.1a..508.1d]).
    Attack {
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default = "Filter::any")]
        on: Filter,
    },
    /// `by` blocks `on`. `count` bounds the matched blocking arrangement:
    /// anchored on `on` it bounds the blocker set per blocked creature
    /// (menace, [CR#702.111b]); anchored on `by` it bounds how many
    /// creatures the blocker blocks ([CR#509.1a..509.1c]).
    Block {
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default = "Filter::any")]
        on: Filter,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        count: Option<(Cmp, Count)>,
    },
    /// `by` (a spell/ability source) targets `on` ([CR#115.1,601.2c]).
    Target {
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default = "Filter::any")]
        on: Filter,
    },
    /// `by` casts `what`, optionally from a zone / in a window
    /// ([CR#601.3,701.5]).
    Cast {
        #[serde(default = "Filter::any")]
        what: Filter,
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        from: Option<Zone>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        window: Option<CastWindow>,
    },
    /// `by` plays `what` — land plays / play-a-card permissions
    /// ([CR#701.18]).
    Play {
        #[serde(default = "Filter::any")]
        what: Filter,
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        from: Option<Zone>,
    },
    /// `by` activates abilities of `what` ([CR#602.1]).
    Activate {
        #[serde(default = "Filter::any")]
        what: Filter,
        #[serde(default = "Filter::any")]
        by: Filter,
    },
    /// A remembered `DeonticAction` macro invocation. Serialized as the
    /// invocation, not the struct.
    #[macro_ron(expanded)]
    Expanded(Expansion<DeonticAction>),
}

/// A deontic clause over a proposed action ([CR#101.2,601.3]).
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Deontic {
    /// Permission row — the existential floor; granted rows widen the
    /// standing defaults ([CR#117.1a..117.1c,508.1a,509.1a], engine-side).
    May(DeonticAction),
    /// Prohibition; beats May ([CR#101.2]).
    Cant(DeonticAction),
    /// Requirement — if-able, arbitrated by the maximize solver
    /// ([CR#508.1d,509.1c]); never forces a toll payment.
    Must(DeonticAction),
    /// Declaration-gating toll ([CR#508.1d,509.1c]): the action is legal
    /// only in completions paying the cost, once per matching instance;
    /// the actor is never compelled. Resolution tolls (ward,
    /// [CR#702.21a,118.12a]) are trigger + unless, not this.
    MayIf(DeonticAction, Vec<CostComponent>),
    /// A remembered `Deontic` macro invocation (evasion keywords, …).
    #[macro_ron(expanded)]
    Expanded(Expansion<Deontic>),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Reference;

    fn read(source: &str) -> Deontic { crate::ron::options().from_str(source).unwrap() }

    /// Omitted slots default to `Any` (load-bearing serde defaults, like
    /// `Event::Performed`).
    #[test]
    fn slots_default_to_any() {
        assert_eq!(
            read("Cant(Attack(by: Is(This)))"),
            Deontic::Cant(DeonticAction::Attack {
                by: Filter::Is(Reference::This),
                on: Filter::Any,
            }),
        );
    }

    /// Menace's shape: a Cant over too-small blocker sets.
    #[test]
    fn block_count_bound_reads() {
        assert_eq!(
            read("Cant(Block(on: Is(This), count: (Less, Literal(2))))"),
            Deontic::Cant(DeonticAction::Block {
                by: Filter::Any,
                on: Filter::Is(Reference::This),
                count: Some((Cmp::Less, Count::Literal(2))),
            }),
        );
    }

    /// The Flash keyword's expansion target.
    #[test]
    fn flash_permission_row_reads() {
        assert_eq!(
            read("May(Cast(what: Is(This), window: InstantSpeed))"),
            Deontic::May(DeonticAction::Cast {
                what: Filter::Is(Reference::This),
                by: Filter::Any,
                from: None,
                window: Some(CastWindow::InstantSpeed),
            }),
        );
    }

    /// The old MayCastFrom(Zone) row in decomposed spelling.
    #[test]
    fn cast_from_zone_reads() {
        assert_eq!(
            read("May(Cast(what: Is(This), from: Graveyard))"),
            Deontic::May(DeonticAction::Cast {
                what: Filter::Is(Reference::This),
                by: Filter::Any,
                from: Some(Zone::Graveyard),
                window: None,
            }),
        );
    }

    /// A declaration toll (Propaganda-shaped, cost simplified to {T}).
    #[test]
    fn declaration_toll_reads() {
        assert_eq!(
            read("MayIf(Attack(on: Is(You)), [Tap])"),
            Deontic::MayIf(
                DeonticAction::Attack {
                    by: Filter::Any,
                    on: Filter::Is(Reference::You),
                },
                vec![CostComponent::Tap],
            ),
        );
    }
}
