//! The deontic layer ([CR#101.2,601.3]): clauses gating whether a *proposed
//! action* is legal. Boundary ([CR#614.17]): "doesn't"/"skip"/can't-happen
//! over events are replacement-family, never deontic; outcome "can't"s
//! ([CR#104]) are SBA-override machinery, also not here.

use serde::Deserialize;
use serde::Serialize;

use crate::CostComponent;
use crate::Count;
use crate::Expand;
use crate::Expansion;
use crate::Filter;
use crate::SupportsMacros;
use crate::Window;
use crate::Zone;

/// An alternative base cost on a cast-permission row ([CR#118.9]): paid
/// INSTEAD of the mana cost, chosen at announce ([CR#601.2b]); only one
/// alternative may apply per spell ([CR#118.9a] — an engine rule, not
/// encodable here). Additional costs, increases, and reductions apply on
/// top ([CR#118.9d]); an alternative unlocks an unpayable base
/// ([CR#118.6a]).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Deserialize, Expand, Serialize)]
pub enum AlternativeCost {
    /// "Without paying its mana cost" — the limiting case ([CR#118.9]).
    Free,
    /// "You may pay [cost] rather than …" ([CR#118.9b]).
    Components(Vec<CostComponent>),
}

/// A scoped counterfactual premise ([CR#609.4]): "treat the game as if
/// [premise] were true, for purposes of that effect only." Carried by
/// `StaticEffect::AsThough`. Many as-though cards compile to deontic rows
/// instead (cast-as-though-flash = `May(Cast(window: InstantSpeed))`); the
/// variants here are the residue. Premises accrete as cards demand them.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum AsThough {
    /// Payment freedom ([CR#609.4b]): changes only HOW a cost may be paid —
    /// never the cost itself, nor what was actually spent.
    SpendManaAsAnyColor,
    /// A remembered `AsThough` macro invocation. Serialized as the
    /// invocation, not the struct.
    #[macro_ron(expanded)]
    Expanded(Expansion<AsThough>),
}

/// A cardinality bound on a matched set — comparator-headed so it reads as
/// prose (`Less(Literal(2))` = "fewer than two"). A set-level predicate,
/// deliberately NOT a `Filter` atom: filters judge one object at a time,
/// bounds judge the arrangement ([CR#702.111b] menace; deontics set-level
/// evaluation).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Deserialize, Expand, Serialize)]
pub enum CountBound {
    Eq(Count),
    AtLeast(Count),
    AtMost(Count),
    Greater(Count),
    Less(Count),
}

impl CountBound {
    /// The comparator this bound heads with, and the `Count` it bounds
    /// against — comparator-headed variants map 1:1 onto [`Cmp`].
    #[must_use]
    pub fn split(&self) -> (crate::Cmp, &Count) {
        match self {
            CountBound::Eq(c) => (crate::Cmp::Eq, c),
            CountBound::AtLeast(c) => (crate::Cmp::AtLeast, c),
            CountBound::AtMost(c) => (crate::Cmp::AtMost, c),
            CountBound::Greater(c) => (crate::Cmp::Greater, c),
            CountBound::Less(c) => (crate::Cmp::Less, c),
        }
    }

    /// Does a matched set of cardinality `actual` satisfy this bound? `eval`
    /// is the engine's unified count evaluator, supplied by the caller to turn
    /// the bound's `Count` into a concrete cardinality — keeping this core
    /// predicate independent of the engine while still routing through the one
    /// evaluator (`GameState::eval_count`).
    pub fn satisfied_by(
        &self,
        actual: crate::Uint,
        eval: impl FnOnce(&Count) -> crate::Uint,
    ) -> bool {
        let (cmp, bound) = self.split();
        cmp.apply(actual, eval(bound))
    }
}

/// A proposed-action pattern — the typed verb the deontic polarities range
/// over. Closed core enum (the engine pattern-matches it); openness comes
/// from macro interception at the `Deontic`/`Ability` positions. Slots
/// default to match-anything; the carrier side is spelled `Ref(This)`.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: struct
/// variants read flat in RON through generated helper structs (carrying the
/// forwarded `#[serde(...)]` field defaults) + `unwrap_variant_newtypes`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum DeonticAction {
    /// `by` attacks `on` — a player/planeswalker/battle set
    /// ([CR#508.1a..508.1d]).
    Attack {
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default = "Filter::any")]
        on: Filter,
    },
    /// `by` blocks `on`. `count` bounds the matched blocking arrangement,
    /// and which slot carries `Ref(This)` decides the reading: anchored on
    /// `on` it bounds the blocker set per blocked creature (menace,
    /// [CR#702.111b]) — also the reading when neither slot is anchored —
    /// while anchored on `by` it bounds how many creatures the blocker
    /// blocks ([CR#509.1a..509.1c]).
    Block {
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default = "Filter::any")]
        on: Filter,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        count: Option<CountBound>,
    },
    /// `by` (a spell/ability source) targets `on` ([CR#115.1,601.2c]).
    Target {
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default = "Filter::any")]
        on: Filter,
    },
    /// `what` is attached to `to` ([CR#701.3a] legality — "can't be
    /// attached" rows; protection's can't-be-enchanted/equipped clauses
    /// [CR#702.16c], enchant's quality restriction [CR#702.5a]). An
    /// illegal existing attachment is the SBA's business
    /// ([CR#704.5m..704.5n]), not this row's.
    Attach {
        #[serde(default = "Filter::any")]
        what: Filter,
        #[serde(default = "Filter::any")]
        to: Filter,
    },
    /// `by` casts `what`, optionally from a zone / in a window
    /// ([CR#601.3,701.5]).
    Cast {
        #[serde(default = "Filter::any")]
        what: Filter,
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        from: Option<Zone>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        window: Option<Window>,
        /// An alternative base cost the permission carries ([CR#118.9]) —
        /// "you may cast … without paying its mana cost".
        #[serde(default, skip_serializing_if = "Option::is_none")]
        cost: Option<AlternativeCost>,
    },
    /// `by` plays `what` — land plays / play-a-card permissions
    /// ([CR#701.18]).
    Play {
        #[serde(default = "Filter::any")]
        what: Filter,
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        from: Option<Zone>,
    },
    /// `by` activates abilities of `what` ([CR#602.1]).
    Activate {
        #[serde(default = "Filter::any")]
        what: Filter,
        #[serde(default = "Filter::any")]
        by: Filter,
    },
    /// A remembered `DeonticAction` macro invocation. Serialized as the
    /// invocation, not the struct.
    #[macro_ron(expanded)]
    Expanded(Expansion<DeonticAction>),
}

/// A deontic clause over a proposed action ([CR#101.2,601.3]).
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Deontic {
    /// Permission row — the existential floor; granted rows widen the
    /// standing defaults ([CR#117.1a..117.1c,508.1a,509.1a], engine-side).
    May(DeonticAction),
    /// Prohibition; beats May ([CR#101.2]).
    Cant(DeonticAction),
    /// Requirement — if-able, arbitrated by the maximize solver
    /// ([CR#508.1d,509.1c]); never forces a toll payment.
    Must(DeonticAction),
    /// Gate — the declaration-gating price ([CR#508.1d,509.1c]): the
    /// action is legal only in completions paying the cost, once per
    /// matching instance; the actor is never compelled. Resolution Tolls
    /// (ward, [CR#702.21a,118.12a]) are trigger + unless, not a `Deontic`.
    Gate(DeonticAction, Vec<CostComponent>),
    /// A remembered `Deontic` macro invocation (evasion keywords, …).
    #[macro_ron(expanded)]
    Expanded(Expansion<Deontic>),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Reference;

    fn read(source: &str) -> Deontic {
        crate::ron::options().from_str(source).unwrap()
    }

    /// Omitted slots default to `Any` (load-bearing serde defaults, like
    /// `Event::Performed`).
    #[test]
    fn slots_default_to_any() {
        assert_eq!(
            read("Cant(Attack(by: Ref(This)))"),
            Deontic::Cant(DeonticAction::Attack {
                by: Filter::Ref(Reference::This),
                on: Filter::Any,
            }),
        );
    }

    /// `satisfied_by` routes the matched-set cardinality and the bound's
    /// evaluated `Count` through the right comparator — and feeds the closure
    /// the BOUND, not the actual. Menace (`Less(2)`) forbids a non-empty set
    /// of fewer than two: one blocker is too few, two is enough.
    #[test]
    fn count_bound_satisfied_by_routes_through_comparator() {
        let menace = CountBound::Less(Count::Literal(2));
        // The closure must receive the bound (Literal(2)), returning 2.
        let eval = |c: &Count| match c {
            Count::Literal(n) => *n,
            other => panic!("unexpected count {other:?}"),
        };
        assert!(
            menace.satisfied_by(1, eval),
            "1 < 2 → bound holds (too few)"
        );
        assert!(!menace.satisfied_by(2, eval), "2 < 2 is false");
        // Every comparator variant maps correctly against a fixed bound of 2.
        assert!(CountBound::Eq(Count::Literal(2)).satisfied_by(2, eval));
        assert!(CountBound::AtLeast(Count::Literal(2)).satisfied_by(2, eval));
        assert!(CountBound::AtMost(Count::Literal(2)).satisfied_by(2, eval));
        assert!(CountBound::Greater(Count::Literal(2)).satisfied_by(3, eval));
        assert!(!CountBound::Greater(Count::Literal(2)).satisfied_by(2, eval));
    }

    /// Menace's shape: a Cant over too-small blocker sets.
    #[test]
    fn block_count_bound_reads() {
        assert_eq!(
            read("Cant(Block(on: Ref(This), count: Less(Literal(2))))"),
            Deontic::Cant(DeonticAction::Block {
                by: Filter::Any,
                on: Filter::Ref(Reference::This),
                count: Some(CountBound::Less(Count::Literal(2))),
            }),
        );
    }

    /// The Flash keyword's expansion target.
    #[test]
    fn flash_permission_row_reads() {
        assert_eq!(
            read("May(Cast(what: Ref(This), window: InstantSpeed))"),
            Deontic::May(DeonticAction::Cast {
                what: Filter::Ref(Reference::This),
                by: Filter::Any,
                from: None,
                window: Some(Window::InstantSpeed),
                cost: None,
            }),
        );
    }

    /// The old MayCastFrom(Zone) row in decomposed spelling.
    #[test]
    fn cast_from_zone_reads() {
        assert_eq!(
            read("May(Cast(what: Ref(This), from: Graveyard))"),
            Deontic::May(DeonticAction::Cast {
                what: Filter::Ref(Reference::This),
                by: Filter::Any,
                from: Some(Zone::Graveyard),
                window: None,
                cost: None,
            }),
        );
    }

    /// A declaration Gate (Propaganda-shaped, cost simplified to {T}).
    #[test]
    fn declaration_gate_reads() {
        assert_eq!(
            read("Gate(Attack(on: Ref(You)), [Tap])"),
            Deontic::Gate(
                DeonticAction::Attack {
                    by: Filter::Any,
                    on: Filter::Ref(Reference::You),
                },
                vec![CostComponent::Tap],
            ),
        );
    }

    /// An unknown name at a `Deontic` position is a hard error, not a
    /// silent fallthrough (the macro layer's type-safety seam).
    #[test]
    fn unknown_names_error() {
        assert!(
            crate::ron::options()
                .from_str::<Deontic>("Bogus(1)")
                .is_err()
        );
    }

    /// The block-restriction shapes the static-ability parser emits read with
    /// BARE-numeral count bounds (`Greater(1)`, `AtMost(2)`) through the
    /// literal-aware core reader — no `Literal(…)` wrapper.
    #[test]
    fn block_restriction_bare_count_bounds_read() {
        assert_eq!(
            read("Cant(Block(on: Ref(This), count: Greater(1)))"),
            Deontic::Cant(DeonticAction::Block {
                by: Filter::Any,
                on: Filter::Ref(Reference::This),
                count: Some(CountBound::Greater(Count::Literal(1))),
            }),
        );
        assert_eq!(
            read("May(Block(by: Ref(This), count: AtMost(2)))"),
            Deontic::May(DeonticAction::Block {
                by: Filter::Ref(Reference::This),
                on: Filter::Any,
                count: Some(CountBound::AtMost(Count::Literal(2))),
            }),
        );
    }

    /// Serialize → read returns the same value for each polarity shape.
    #[test]
    fn deontic_round_trips() {
        let cases = [
            "Cant(Attack(by: Ref(This)))",
            "Cant(Block(on: Ref(This), count: Less(Literal(2))))",
            "Cant(Block(on: Ref(This), count: Greater(1)))",
            "May(Block(by: Ref(This), count: AtMost(2)))",
            "May(Cast(what: Ref(This), window: InstantSpeed))",
            "Gate(Attack(on: Ref(You)), [Tap])",
        ];
        for source in cases {
            let parsed = read(source);
            let written = crate::ron::options().to_string(&parsed).unwrap();
            assert_eq!(read(&written), parsed, "round-trip failed: {source}");
        }
    }
}
