//! The deontic layer ([CR#101.2,601.3]): clauses gating whether a *proposed
//! action* is legal. Boundary ([CR#614.17]): "doesn't"/"skip"/can't-happen
//! over events are replacement-family, never deontic; outcome "can't"s
//! ([CR#104]) are SBA-override machinery, also not here.

use serde::Deserialize;
use serde::Serialize;

use crate::CostComponent;
use crate::Count;
use crate::Expand;
use crate::Expansion;
use crate::Filter;
use crate::SupportsMacros;
use crate::Zone;

/// A cast/play timing window ([CR#117.1a..117.1b]). Just `InstantSpeed`
/// for now; `SorcerySpeed` accretes with the deferred `Only` work.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Serialize, Expand)]
pub enum CastWindow {
    /// Any time you could cast an instant (flash, [CR#702.8a]).
    InstantSpeed,
}

/// A cardinality bound on a matched set — comparator-headed so it reads as
/// prose (`Less(Literal(2))` = "fewer than two"). A set-level predicate,
/// deliberately NOT a `Filter` atom: filters judge one object at a time,
/// bounds judge the arrangement ([CR#702.111b] menace; deontics set-level
/// evaluation).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Deserialize, Serialize, Expand)]
pub enum CountBound {
    Eq(Count),
    AtLeast(Count),
    AtMost(Count),
    Greater(Count),
    Less(Count),
}

/// A proposed-action pattern — the typed verb the deontic polarities range
/// over. Closed core enum (the engine pattern-matches it); openness comes
/// from macro interception at the `Deontic`/`Ability` positions. Slots
/// default to match-anything; the carrier side is spelled `Is(This)`.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: struct
/// variants read flat in RON through generated helper structs (carrying the
/// forwarded `#[serde(...)]` field defaults) + `unwrap_variant_newtypes`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum DeonticAction {
    /// `by` attacks `on` — a player/planeswalker/battle set
    /// ([CR#508.1a..508.1d]).
    Attack {
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default = "Filter::any")]
        on: Filter,
    },
    /// `by` blocks `on`. `count` bounds the matched blocking arrangement,
    /// and which slot carries `Is(This)` decides the reading: anchored on
    /// `on` it bounds the blocker set per blocked creature (menace,
    /// [CR#702.111b]) — also the reading when neither slot is anchored —
    /// while anchored on `by` it bounds how many creatures the blocker
    /// blocks ([CR#509.1a..509.1c]).
    Block {
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default = "Filter::any")]
        on: Filter,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        count: Option<CountBound>,
    },
    /// `by` (a spell/ability source) targets `on` ([CR#115.1,601.2c]).
    Target {
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default = "Filter::any")]
        on: Filter,
    },
    /// `by` casts `what`, optionally from a zone / in a window
    /// ([CR#601.3,701.5]).
    Cast {
        #[serde(default = "Filter::any")]
        what: Filter,
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        from: Option<Zone>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        window: Option<CastWindow>,
    },
    /// `by` plays `what` — land plays / play-a-card permissions
    /// ([CR#701.18]).
    Play {
        #[serde(default = "Filter::any")]
        what: Filter,
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        from: Option<Zone>,
    },
    /// `by` activates abilities of `what` ([CR#602.1]).
    Activate {
        #[serde(default = "Filter::any")]
        what: Filter,
        #[serde(default = "Filter::any")]
        by: Filter,
    },
    /// A remembered `DeonticAction` macro invocation. Serialized as the
    /// invocation, not the struct.
    #[macro_ron(expanded)]
    Expanded(Expansion<DeonticAction>),
}

/// A deontic clause over a proposed action ([CR#101.2,601.3]).
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Deontic {
    /// Permission row — the existential floor; granted rows widen the
    /// standing defaults ([CR#117.1a..117.1c,508.1a,509.1a], engine-side).
    May(DeonticAction),
    /// Prohibition; beats May ([CR#101.2]).
    Cant(DeonticAction),
    /// Requirement — if-able, arbitrated by the maximize solver
    /// ([CR#508.1d,509.1c]); never forces a toll payment.
    Must(DeonticAction),
    /// Gate — the declaration-gating price ([CR#508.1d,509.1c]): the
    /// action is legal only in completions paying the cost, once per
    /// matching instance; the actor is never compelled. Resolution Tolls
    /// (ward, [CR#702.21a,118.12a]) are trigger + unless, not a `Deontic`.
    Gate(DeonticAction, Vec<CostComponent>),
    /// A remembered `Deontic` macro invocation (evasion keywords, …).
    #[macro_ron(expanded)]
    Expanded(Expansion<Deontic>),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Reference;

    fn read(source: &str) -> Deontic { crate::ron::options().from_str(source).unwrap() }

    /// Omitted slots default to `Any` (load-bearing serde defaults, like
    /// `Event::Performed`).
    #[test]
    fn slots_default_to_any() {
        assert_eq!(
            read("Cant(Attack(by: Is(This)))"),
            Deontic::Cant(DeonticAction::Attack {
                by: Filter::Is(Reference::This),
                on: Filter::Any,
            }),
        );
    }

    /// Menace's shape: a Cant over too-small blocker sets.
    #[test]
    fn block_count_bound_reads() {
        assert_eq!(
            read("Cant(Block(on: Is(This), count: Less(Literal(2))))"),
            Deontic::Cant(DeonticAction::Block {
                by: Filter::Any,
                on: Filter::Is(Reference::This),
                count: Some(CountBound::Less(Count::Literal(2))),
            }),
        );
    }

    /// The Flash keyword's expansion target.
    #[test]
    fn flash_permission_row_reads() {
        assert_eq!(
            read("May(Cast(what: Is(This), window: InstantSpeed))"),
            Deontic::May(DeonticAction::Cast {
                what: Filter::Is(Reference::This),
                by: Filter::Any,
                from: None,
                window: Some(CastWindow::InstantSpeed),
            }),
        );
    }

    /// The old MayCastFrom(Zone) row in decomposed spelling.
    #[test]
    fn cast_from_zone_reads() {
        assert_eq!(
            read("May(Cast(what: Is(This), from: Graveyard))"),
            Deontic::May(DeonticAction::Cast {
                what: Filter::Is(Reference::This),
                by: Filter::Any,
                from: Some(Zone::Graveyard),
                window: None,
            }),
        );
    }

    /// A declaration Gate (Propaganda-shaped, cost simplified to {T}).
    #[test]
    fn declaration_gate_reads() {
        assert_eq!(
            read("Gate(Attack(on: Is(You)), [Tap])"),
            Deontic::Gate(
                DeonticAction::Attack {
                    by: Filter::Any,
                    on: Filter::Is(Reference::You),
                },
                vec![CostComponent::Tap],
            ),
        );
    }

    /// An unknown name at a `Deontic` position is a hard error, not a
    /// silent fallthrough (the macro layer's type-safety seam).
    #[test]
    fn unknown_names_error() {
        assert!(
            crate::ron::options()
                .from_str::<Deontic>("Bogus(1)")
                .is_err()
        );
    }

    /// Serialize → read returns the same value for each polarity shape.
    #[test]
    fn deontic_round_trips() {
        let cases = [
            "Cant(Attack(by: Is(This)))",
            "Cant(Block(on: Is(This), count: Less(Literal(2))))",
            "May(Cast(what: Is(This), window: InstantSpeed))",
            "Gate(Attack(on: Is(You)), [Tap])",
        ];
        for source in cases {
            let parsed = read(source);
            let written = crate::ron::options().to_string(&parsed).unwrap();
            assert_eq!(read(&written), parsed, "round-trip failed: {source}");
        }
    }
}
