use serde::Deserialize;
use serde::Serialize;

use crate::Expand;
use crate::Expansion;
use crate::Filter;
use crate::Ident;
use crate::SupportsMacros;
use crate::Zone;

/// A turn phase (the 5xx turn structure). `BeginningOf` triggers key off
/// these. Each phase carries its constituent step(s); a phase that is a single
/// step (the main phases — [CR#505.1]) is a bare variant. Nested enums
/// round-trip in RON as `Beginning(Upkeep)`, `Combat(DeclareAttackers)`,
/// `PostcombatMain`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Serialize, Expand)]
pub enum Phase {
    /// The beginning phase ([CR#501]): untap, upkeep, draw.
    Beginning(BeginningStep),
    /// The precombat main phase ([CR#505], one step).
    PrecombatMain,
    /// The combat phase ([CR#506]): its five (or six, with first strike) steps.
    Combat(CombatStep),
    /// The postcombat main phase ([CR#505], one step).
    PostcombatMain,
    /// The ending phase ([CR#512]): end step, cleanup.
    Ending(EndingStep),
}

/// The steps of the beginning phase ([CR#501,502,503]).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Serialize, Expand)]
pub enum BeginningStep {
    /// [CR#502].
    Untap,
    /// [CR#503].
    Upkeep,
    /// [CR#504].
    Draw,
}

/// The steps of the combat phase ([CR#506,507,508,509,510,511]).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Serialize, Expand)]
pub enum CombatStep {
    /// [CR#507].
    BeginningOfCombat,
    /// [CR#508].
    DeclareAttackers,
    /// [CR#509].
    DeclareBlockers,
    /// The first combat-damage step ([CR#510.4]), present only when an
    /// attacker or blocker has first strike or double strike.
    FirstCombatDamage,
    /// [CR#510].
    CombatDamage,
    /// [CR#511].
    EndOfCombat,
}

/// The steps of the ending phase ([CR#512,513,514]).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Serialize, Expand)]
pub enum EndingStep {
    /// [CR#513].
    End,
    /// [CR#514].
    Cleanup,
}

/// Whose turn a step-based trigger watches ([CR#503.1] "your upkeep", etc.).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Serialize, Expand)]
pub enum WhoseTurn {
    /// The controller's own turn.
    Your,
    /// Every player's turn of that step.
    EachPlayers,
    /// An opponent's turn.
    AnOpponents,
}

/// The state a `StateBecomes` transition watches ([CR#603.2e]). A small set
/// today; variants accrete as cards force them.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Deserialize, Serialize, Expand)]
pub enum StateFilterEvent {
    /// Becomes tapped.
    Tapped,
    /// Becomes untapped.
    Untapped,
    /// Becomes attacking ([CR#508.1a]).
    Attacking,
    /// Becomes blocked ([CR#509.3c]).
    Blocked,
}

/// The machinery that demanded an event — the cause triple's AGENCY
/// coordinate (mtg-rules events.md §3). Closed CR vocabulary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Serialize, Expand)]
pub enum Agency {
    /// {T}/cost components being paid ([CR#107.5], "sacrificed to pay").
    CostPayment,
    /// The declare-attackers procedure's tap ([CR#508.1f] — explicitly
    /// not a cost).
    AttackDeclaration,
    /// An effect's instruction ("tap target creature", [CR#701.26a]).
    EffectInstruction,
    /// A turn-based action ([CR#703] — cleanup discard, phasing).
    TurnBasedAction,
    /// A state-based action ([CR#704] — lethal damage, deathtouch).
    StateBasedAction,
    /// A resolving mana ability ("tapped for mana", [CR#106.12]).
    ManaAbilityResolution,
    /// A special action ([CR#116.2] — land plays, foretell, …). NOTE: absent
    /// from the skill's events.md §3 agency list (erratum filed); the land
    /// play view ([CR#701.18a]) is unrepresentable without it.
    SpecialAction,
}

/// A trigger-side predicate over an event's cause triple (verb, agency,
/// agent). Every omitted coordinate matches anything. `verb` names the
/// performed view ("Destroy", "Sacrifice", …); `agent` filters the causing
/// object/controller (Karmic Justice's "a spell or ability an opponent
/// controls"). Agent-IDENTITY equality ("destroyed this way") is a
/// binding concern, not a pattern — it rides the event log.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Deserialize, Serialize, Expand)]
pub struct CausePattern {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub verb: Option<Ident>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agency: Option<Agency>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent: Option<Filter>,
}

/// A trigger-event pattern, matched structurally against the action log
/// ([CR#603.2]). Declared event names (`Dies`, `Enters`, `Landfall`) are macros
/// over these forms. Each form binds fixed roles (`ThatObject`,
/// `ThatPlayer`) for the body.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back, and the struct variants read flat in RON
/// through generated helper structs (carrying the forwarded `#[serde(...)]`
/// field defaults) + `unwrap_variant_newtypes`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Event {
    /// A verb was performed ([CR#603.2] over the action log). `by`/`on` default
    /// to match-anything (`Filter::Any`).
    Performed {
        verb: Ident,
        #[serde(default = "Filter::any")]
        by: Filter,
        #[serde(default = "Filter::any")]
        on: Filter,
    },
    /// An object changed zones ([CR#603.6]). `Dies` = `from: Battlefield,
    /// to: Graveyard` is a prelude macro over this. `cause` narrows by the
    /// cause triple ("destroyed" admits exactly two causes, [CR#701.8b];
    /// "sacrificed" is never destruction, [CR#701.21a]); omitted = any
    /// cause ("dies", [CR#700.4]).
    ZoneMove {
        what: Filter,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        from: Option<Zone>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        to: Option<Zone>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        cause: Option<CausePattern>,
    },
    /// The beginning of a step or phase ([CR#603.2], "at the beginning of …").
    BeginningOf(Phase, WhoseTurn),
    /// An object's state changed — transitions only ([CR#603.2e]).
    /// `cause` narrows by the tap-cause table (cost payment vs attack
    /// declaration vs crewing vs effect, [CR#107.5,508.1f,702.122b]).
    StateBecomes {
        of: Filter,
        becomes: StateFilterEvent,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        cause: Option<CausePattern>,
    },
    /// Any of several events ([CR#603.2], "whenever … or …").
    OneOfEvents(Vec<Event>),
    /// A remembered `Event` macro invocation (`Dies`, `Enters`, `Landfall`,
    /// …). Serialized as the invocation, not the struct.
    #[macro_ron(expanded)]
    Expanded(Expansion<Event>),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CharacteristicFilter;
    use crate::Type;

    fn read(source: &str) -> Event { crate::ron::options().from_str(source).unwrap() }

    /// `by`/`on` default to match-anything when omitted (the `Filter::Any`
    /// default is load-bearing — removing it breaks `Performed(verb: …)`).
    #[test]
    fn performed_defaults_by_and_on_to_any() {
        assert_eq!(
            read(r#"Performed(verb: "Sacrifice")"#),
            Event::Performed {
                verb: "Sacrifice".into(),
                by: Filter::Any,
                on: Filter::Any,
            },
        );
    }

    #[test]
    fn zone_move_options_default_none() {
        assert_eq!(
            read("ZoneMove(what: Type(Creature), from: Battlefield, to: Graveyard)"),
            Event::ZoneMove {
                what: Filter::Characteristic(CharacteristicFilter::Type(Type::Creature)),
                from: Some(Zone::Battlefield),
                to: Some(Zone::Graveyard),
                cause: None,
            },
        );
        assert_eq!(
            read("ZoneMove(what: Type(Creature))"),
            Event::ZoneMove {
                what: Filter::Characteristic(CharacteristicFilter::Type(Type::Creature)),
                from: None,
                to: None,
                cause: None,
            },
        );
    }

    #[test]
    fn beginning_of_reads() {
        assert_eq!(
            read("BeginningOf(Beginning(Upkeep), Your)"),
            Event::BeginningOf(Phase::Beginning(BeginningStep::Upkeep), WhoseTurn::Your),
        );
    }
}
