use crate::Count;
use crate::Expansion;
use crate::SupportsMacros;

/// A cardinality range over a scalar [`Count`]: how many objects an effect
/// operates on, never a continuous magnitude (amounts use `Count` directly).
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Quantity {
    /// Exactly `n` objects.
    Exactly(Count),
    /// At least `n` objects.
    AtLeast(Count),
    /// At most `n` objects.
    AtMost(Count),
    /// Between `lo` and `hi` objects (inclusive).
    Between(Count, Count),
    /// Any number of objects ([CR#601.2c]).
    AnyNumber,
    /// A remembered `Quantity` macro invocation.
    #[macro_ron(expanded)]
    Expanded(Expansion<Quantity>),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Count;

    fn read(source: &str) -> Quantity { crate::ron::options().from_str(source).unwrap() }

    #[test]
    fn exactly_reads() {
        assert_eq!(
            read("Exactly(Literal(3))"),
            Quantity::Exactly(Count::Literal(3)),
        );
    }

    #[test]
    fn at_most_reads() {
        assert_eq!(
            read("AtMost(Literal(2))"),
            Quantity::AtMost(Count::Literal(2)),
        );
    }

    #[test]
    fn at_least_reads() {
        assert_eq!(read("AtLeast(X)"), Quantity::AtLeast(Count::X),);
    }

    #[test]
    fn between_reads() {
        assert_eq!(
            read("Between(Literal(1), Literal(3))"),
            Quantity::Between(Count::Literal(1), Count::Literal(3)),
        );
    }

    #[test]
    fn any_number_reads() {
        assert_eq!(read("AnyNumber"), Quantity::AnyNumber);
    }

    /// `Between` (2-tuple) and `AnyNumber` (unit) pin the derived `Serialize`
    /// round-trip: serialize → read is identity.
    #[test]
    fn variants_round_trip() {
        for value in [
            Quantity::Between(Count::Literal(1), Count::Literal(3)),
            Quantity::AnyNumber,
            Quantity::Exactly(Count::X),
        ] {
            let written = crate::ron::options().to_string(&value).unwrap();
            assert_eq!(read(&written), value, "round-trip failed for {value:?}");
        }
    }
}
