use crate::Expansion;
use crate::SupportsMacros;

#[cfg(test)]
mod tests {
    use super::Reference;

    fn read(source: &str) -> Reference {
        crate::ron::options().from_str(source).unwrap()
    }

    #[test]
    fn attach_host_of_round_trips() {
        let v = Reference::AttachHostOf(Box::new(Reference::This));
        let w = crate::ron::options().to_string(&v).unwrap();
        assert_eq!(read(&w), v);
    }

    #[test]
    fn opponent_round_trips() {
        let v = Reference::Opponent;
        let w = crate::ron::options().to_string(&v).unwrap();
        assert_eq!(read(&w), v);
    }

    /// The provenance-explicit event roles read as bare variant names and
    /// round-trip — the agent/patient/actor split plus the first-class
    /// defending player ([CR#603.2e,608.2k,506.2]).
    #[test]
    fn event_roles_round_trip() {
        for (source, value) in [
            ("EventAgent", Reference::EventAgent),
            ("EventPatient", Reference::EventPatient),
            ("EventActor", Reference::EventActor),
            ("DefendingPlayer", Reference::DefendingPlayer),
        ] {
            assert_eq!(read(source), value, "reads bare: {source}");
            let written = crate::ron::options().to_string(&value).unwrap();
            assert_eq!(read(&written), value, "round-trips: {written}");
        }
    }

    /// The legacy `ThatObject`/`ThatPlayer` spellings still read (migration
    /// aliases for the agent/actor roles).
    #[test]
    fn legacy_event_aliases_round_trip() {
        for (source, value) in [
            ("ThatObject", Reference::ThatObject),
            ("ThatPlayer", Reference::ThatPlayer),
        ] {
            assert_eq!(read(source), value);
            let written = crate::ron::options().to_string(&value).unwrap();
            assert_eq!(read(&written), value, "round-trips: {written}");
        }
    }
}

/// A bound variable: a value fixed earlier (at announce, by the rules of
/// the position, or by a binder) and referenced later. References name
/// *objects*; amounts live in [`crate::Quantity`].
///
/// Players are objects — `You`, `ControllerOf`, `OwnerOf` resolve to
/// player objects.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Reference {
    /// The object this ability is printed on / the resolving spell.
    This,
    /// The controller of this ability ([CR#109.5]).
    You,
    /// An opponent of `You` ([CR#102.1]); in a two-player game, the other
    /// player. Multiplayer "an opponent" that requires a choice is a future
    /// edge — single-opponent assumption for now.
    Opponent,
    /// The object a per-object filter is currently testing — "it" relative to
    /// the matched candidate, not the carrier. Bound only inside a
    /// [`Filter::Where`](crate::Filter::Where) (and re-bound to the related
    /// object across relation filters, since the matcher recurses with a new
    /// candidate). Undefined at frameless positions, like the carrier
    /// references. Lets candidate-relative predicates be spelled —
    /// `SharesColor(Subject, This)`, "with the same name as ~".
    Subject,
    /// The nth target this ability announced ([CR#115.3,601.2c]).
    Target(usize),
    /// The triggering event's AGENT — the doer/source: the moving object of a
    /// zone change, the source of damage ([CR#603.2e,608.2k]). The
    /// provenance-explicit name for the moved/acting object; `ThatObject` is
    /// kept as a migration alias resolving the same way.
    EventAgent,
    /// The triggering event's PATIENT — the acted-upon thing (a damage
    /// recipient, a destroyed/countered object), kind-polymorphic: a player OR
    /// an object, fixed by the event ([CR#120.3,608.2k]). Distinct from the
    /// agent ([`EventAgent`](Reference::EventAgent)), so a two-object event
    /// ("whenever a creature deals damage to another creature") can name source
    /// and recipient separately — unspellable with the flat
    /// `ThatObject`/`ThatPlayer` pair. For the combat defender prefer
    /// [`DefendingPlayer`](Reference::DefendingPlayer) (always a player).
    EventPatient,
    /// The triggering event's responsible player ("that player") — the event's
    /// ACTOR ([CR#603.2e]). The provenance-explicit name for `ThatPlayer`,
    /// kept as a migration alias resolving the same way.
    EventActor,
    /// The defending player of an attack/combat — ALWAYS a player, even versus
    /// a planeswalker or battle ([CR#506.2,508.5]). Reachable today otherwise
    /// only as a [`DeciderSpec::DefendingPlayer`](crate::DeciderSpec) — this is
    /// the first-class reference for bodies that name "the defending player"
    /// (landwalk, Annihilator, Afflict).
    DefendingPlayer,
    /// The single object bound by an enclosing [`With`](crate::With)
    /// one-binder ([`Binder::ChooseOne`](crate::Binder::ChooseOne) /
    /// [`Binder::TheRef`](crate::Binder::TheRef)) — the Idris `That` (One).
    /// Distinct from [`ThatObject`](Reference::ThatObject), which is the
    /// `ForEach`/`DivideAmong` per-element binding and the event agent.
    /// Carries no payload.
    That,
    /// The object that participated in the enclosing trigger's event —
    /// bound by the trigger's event pattern ([CR#603.2e], "that creature").
    /// Migration alias for [`EventAgent`](Reference::EventAgent); resolves to
    /// the event's agent.
    ThatObject,
    /// The player that participated in the enclosing trigger's event —
    /// bound by the trigger's event pattern ([CR#603.2e], "that player").
    /// Migration alias for [`EventActor`](Reference::EventActor); resolves to
    /// the event's actor.
    ThatPlayer,
    /// A named role bound by an event pattern or instruction (e.g. the
    /// attacker vs. the blocker).
    Bound(crate::Ident),
    /// Information remembered by a linked ability ([CR#607]): the object
    /// exiled with this, the chosen value, the cost paid.
    Linked(crate::Ident),
    /// The controller of a referenced object ([CR#109.5]).
    ControllerOf(Box<Reference>),
    /// The owner of a referenced object ([CR#108.3]).
    OwnerOf(Box<Reference>),
    /// The permanent that attachment R is attached to — attachment→host
    /// direction ([CR#301.5,303.4]).  Covers Equipment hosts, Aura
    /// enchantees, and Fortification hosts alike.
    AttachHostOf(Box<Reference>),
    /// What is attached to R — host→attachment direction (inverse of
    /// [`AttachHostOf`]).
    AttachedTo(Box<Reference>),
    /// A remembered `Reference` macro invocation.
    #[macro_ron(expanded)]
    Expanded(Expansion<Reference>),
}
