use crate::Expansion;
use crate::SupportsMacros;

#[cfg(test)]
mod tests {
    use super::Reference;

    fn read(source: &str) -> Reference { crate::ron::options().from_str(source).unwrap() }

    #[test]
    fn attach_host_of_round_trips() {
        let v = Reference::AttachHostOf(Box::new(Reference::This));
        let w = crate::ron::options().to_string(&v).unwrap();
        assert_eq!(read(&w), v);
    }
}

/// A bound variable: a value fixed earlier (at announce, by the rules of
/// the position, or by a binder) and referenced later. References name
/// *objects*; amounts live in [`crate::Quantity`].
///
/// Players are objects — `You`, `ControllerOf`, `OwnerOf` resolve to
/// player objects.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Reference {
    /// The object this ability is printed on / the resolving spell.
    This,
    /// The controller of this ability ([CR#109.5]).
    You,
    /// The nth target this ability announced ([CR#115.3,601.2c]).
    Target(usize),
    /// The object that participated in the enclosing trigger's event —
    /// bound by the trigger's event pattern ([CR#603.2e], "that creature").
    ThatObject,
    /// The player that participated in the enclosing trigger's event —
    /// bound by the trigger's event pattern ([CR#603.2e], "that player").
    ThatPlayer,
    /// A named role bound by an event pattern or instruction (e.g. the
    /// attacker vs. the blocker).
    Bound(crate::Ident),
    /// Information remembered by a linked ability ([CR#607]): the object
    /// exiled with this, the chosen value, the cost paid.
    Linked(crate::Ident),
    /// The controller of a referenced object ([CR#109.5]).
    ControllerOf(Box<Reference>),
    /// The owner of a referenced object ([CR#108.3]).
    OwnerOf(Box<Reference>),
    /// The permanent that attachment R is attached to — attachment→host
    /// direction ([CR#301.5,303.4]).  Covers Equipment hosts, Aura
    /// enchantees, and Fortification hosts alike.
    AttachHostOf(Box<Reference>),
    /// What is attached to R — host→attachment direction (inverse of
    /// [`AttachHostOf`]).
    AttachedTo(Box<Reference>),
    /// A remembered `Reference` macro invocation.
    #[macro_ron(expanded)]
    Expanded(Expansion<Reference>),
}
