use serde::Deserialize;
use serde::Serialize;

use crate::Count;
use crate::Effect;
use crate::Event;
use crate::Expand;
use crate::Expansion;
use crate::Filter;
use crate::Phase;
use crate::SupportsMacros;
use crate::continuous::Duration;

/// A replacement effect: the CR's closed template list ([CR#614]).
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back, and the struct variants read flat in RON
/// through generated helper structs + `unwrap_variant_newtypes`.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Replacement {
    /// "If [event] would happen, [effect] instead" — replace ([CR#614.1a]).
    Instead { would: Event, instead: Effect },
    /// Skip a step or phase — omit ([CR#614.1b]).
    Skip { what: Phase },
    /// "If [event] would happen, [event] and [effect]" — augment, all-at-once
    /// ([CR#614.1c]). `AsEnters` is a prelude macro over this.
    Also { would: Event, also: Effect },
    /// A remembered `Replacement` macro invocation (`AsEnters`, …).
    #[macro_ron(expanded)]
    Expanded(Expansion<Replacement>),
}

/// A prevention effect ([CR#615]).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Deserialize, Expand, Serialize)]
pub enum Prevention {
    /// Prevent the next N damage from `from` to `to` ([CR#615.7]).
    /// `duration: None` = the carrier's implicit duration — a static's
    /// prevention lasts while it functions ([CR#611.3]); one-shots state
    /// theirs ([CR#615.3]).
    PreventNext {
        n: Count,
        from: Filter,
        to: Filter,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        duration: Option<Duration>,
    },
    /// Prevent the next instance of damage ([CR#615.8]).
    PreventNextInstance { from: Filter, to: Filter },
    /// Prevent all damage from `from` to `to` ([CR#615.1,615.3] —
    /// Fog-style shields; no dedicated prevent-all rule). `duration: None`
    /// = the carrier's implicit duration (statics: while it functions,
    /// [CR#611.3] — protection's [CR#702.16e] clause rides this).
    PreventAll {
        from: Filter,
        to: Filter,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        duration: Option<Duration>,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn skip_reads_flat() {
        let parsed: Replacement = crate::ron::options()
            .from_str("Skip(what: Beginning(Upkeep))")
            .unwrap();
        assert_eq!(
            parsed,
            Replacement::Skip {
                what: Phase::Beginning(crate::BeginningStep::Upkeep)
            },
        );
    }

    /// The three primitive variants round-trip through the derived `Serialize`.
    #[test]
    fn primitives_round_trip() {
        for source in [
            "Skip(what: Beginning(Upkeep))",
            "Also(would: ZoneMove(what: Any, to: Battlefield), also: Tap(This))",
            "Instead(would: ZoneMove(what: Any, to: Graveyard), instead: Tap(This))",
        ] {
            let parsed: Replacement = crate::ron::options().from_str(source).unwrap();
            let written = crate::ron::options().to_string(&parsed).unwrap();
            let reparsed: Replacement = crate::ron::options().from_str(&written).unwrap();
            assert_eq!(parsed, reparsed, "round-trip mismatch for {source}");
        }
    }
}
