//! The central RON configuration and helpers shared by everything that reads
//! or writes deckmaste's RON files.

use std::sync::LazyLock;

use macro_ron::Kind;
use macro_ron::KindSet;
use macro_ron::MacroSet;
use macro_ron::SupportsMacros;
use serde::Serialize;
use serde::de::DeserializeOwned;

/// Every macro-position kind in deckmaste's RON dialect, keyed by serde name.
/// Used both by the core literal-aware reader ([`options`]) and by the cards
/// crate's full macro layer; lives here so the two share one registry. The
/// kind facts (`flatten`/`embed`/`expanded`/`literal` markers) are generated by
/// each type's `#[derive(SupportsMacros)]`, so this only enumerates the types.
#[must_use]
pub fn kinds() -> KindSet {
    let mut kinds = KindSet::new();
    kinds.add(crate::Ability::kind());
    kinds.add(crate::AsThough::kind());
    kinds.add(crate::Action::kind());
    kinds.add(crate::Condition::kind());
    kinds.add(crate::CostComponent::kind());
    kinds.add(crate::Count::kind());
    // `Move`'s destination: a bare zone name flattens in from `Zone`, the
    // library form is `Library(FromTop/FromBottom(Count))`.
    kinds.add(crate::Destination::kind());
    kinds.add(crate::Zone::kind());
    kinds.add(crate::Effect::kind());
    kinds.add(crate::Event::kind());
    kinds.add(crate::Filter::kind());
    kinds.add(crate::KeywordAbility::kind());
    kinds.add(crate::ManaRider::kind());
    // Change-bundling macros (`AddPowerToughness`, …) expand at `changes: [...]`
    // positions to a `Several` bundle, flattened away before the engine.
    kinds.add(crate::Modification::kind());
    kinds.add(crate::PlayerAction::kind());
    kinds.add(crate::Quantity::kind());
    kinds.add(crate::Reference::kind());
    kinds.add(crate::Replacement::kind());
    kinds.add(crate::Selection::kind());
    kinds.add(crate::StaticEffect::kind());
    kinds.add(crate::TargetSpec::kind());
    // Play-policy: the choose-a-play vocabulary expands at `prefer:` positions.
    kinds.add(crate::strategy::Preference::kind());
    kinds.add(Kind::new("CardFace"));
    kinds.add(Kind::new("Subtype"));
    // Counter-kind macros (`P1P1Counter`, …) expand to a `Counter` decl in the
    // plugin loader; name-erasing like `Subtype`. No card position reads it.
    kinds.add(Kind::new("Counter"));
    // Meta-macro positions: `MacroDef` reads in the plugin loader (serde name
    // "Macro"). No card position ever reads it; registering it keeps one kind
    // registry. Name-erasing like the other struct kinds.
    kinds.add(Kind::new("Macro"));
    kinds
}

/// The raw `ron::Options` everything is read and written with.
///
/// As default extensions these need no `#![enable(...)]` header:
/// `implicit_some` keeps `Option` fields flat, and `unwrap_variant_newtypes`
/// is what lets files spell a struct-carrying variant flat —
/// `Normal(name: ..., ...)` instead of `Normal((name: ...))`.
///
/// This is the bare options *value* — use it where an `ron::Options` itself is
/// needed (the macro-layer reader's base options, the migrations writer). For
/// reading, prefer [`options`], whose `from_str` is literal-aware.
#[must_use]
pub fn raw_options() -> ron::Options {
    ron::Options::default().with_default_extension(
        ron::extensions::Extensions::IMPLICIT_SOME
            | ron::extensions::Extensions::UNWRAP_VARIANT_NEWTYPES,
    )
}

/// A literal-aware reader: an otherwise-empty macro layer that knows the
/// `#[macro_ron(literal)]` kinds, so a bare numeral (`3`) reads as
/// `Count::Literal(3)` at the core channel — the read counterpart of the
/// derive's bare write. Only types with a `literal` variant need registering;
/// every other position falls through to plain enum dispatch (with no macros,
/// this is exactly the raw-`ron` read plus the bare-numeral splice).
static LITERAL_READER: LazyLock<MacroSet> =
    LazyLock::new(|| MacroSet::new(kinds()).with_options(raw_options()));

/// The reader/writer facade every RON read and write goes through. Reads accept
/// bare numerals at `literal` positions; writes go through the derive, which
/// serializes literals bare. Method-compatible with the `ron::Options` calls it
/// replaced (`from_str`, `to_string`), so call sites are unchanged.
#[must_use]
pub fn options() -> RonOptions {
    RonOptions
}

/// The facade returned by [`options`].
pub struct RonOptions;

impl RonOptions {
    /// Read `T` from RON, accepting a bare numeral (`3`) at a `literal`
    /// position.
    ///
    /// # Errors
    ///
    /// RON syntax errors, and unknown names / malformed values per
    /// [`MacroSet::read_str`].
    pub fn from_str<T: DeserializeOwned>(&self, source: &str) -> ron::error::SpannedResult<T> {
        LITERAL_READER.read_str(source)
    }

    /// Write `value` to RON (literals serialize bare via the derive).
    ///
    /// # Errors
    ///
    /// Propagates the underlying `ron::Error`.
    pub fn to_string<T: Serialize>(&self, value: &T) -> Result<String, ron::Error> {
        raw_options().to_string(value)
    }
}
