use serde::Deserialize;
use serde::Serialize;

use crate::Count;
use crate::Expand;
use crate::Expansion;
use crate::Filter;
use crate::Quantity;
use crate::Reference;
use crate::SupportsMacros;

/// Which extreme a [`Selection::Pick`] takes — the subset of the aggregate
/// ops along which an *element* is well-defined ([CR#107.1]). Only the
/// extremal ops are representable here (no "pick the sum"); the value-twin
/// fold over the same projection is the aggregate-count work.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Expand, Serialize)]
pub enum Extremum {
    /// The element with the greatest projected value ("the creature with the
    /// greatest power").
    Greatest,
    /// The element with the least projected value.
    Least,
}

/// A resolution-time group or query over objects — the plural/collective
/// shape a combinator binds ([CR#608.2d]). This is the pure group/query type:
/// effect verbs no longer take a `Selection` patient (they take a single
/// [`Reference`]); plurality and choice live in the
/// [`Each`](crate::Each) / [`DivideAmong`](crate::DivideAmong)
/// iterators and the [`With`](crate::With) [`Binder`](crate::Binder).
///
/// Targeting is NOT here — it lives in [`crate::TargetSpec`], the announce
/// list — because a target has legality recheck and retargeting rules the
/// other choice forms lack ([CR#115]).
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Selection {
    /// All matching objects as one set — the shape continuous-effect
    /// scopes and set-wide instructions consume.
    Filter(Filter),
    /// A random selection of a quantity of matching objects.
    Random(Quantity, Filter),
    /// A choice from among a PREVIOUSLY COMPUTED set ("exile two of them",
    /// "…from among them" — the among-restriction, queries.md §2): the
    /// domain is whatever `Effect::Noting{key, …}` recorded under the
    /// key, not a re-evaluated filter — re-evaluation would be wrong for
    /// "this way" anaphora ([CR#607.2a] linkage).
    AmongNoted(crate::Ident, Quantity),
    /// The top `count` cards of a library, top → down (an ORDERED set —
    /// position is the whole point). `of` names the library's player; the
    /// default `You` writes bare. Feeds `With`/`Distribute` ([CR#701.22a]).
    TopOfLibrary {
        count: Count,
        #[serde(default = "ref_you", skip_serializing_if = "ref_is_you")]
        of: Reference,
    },
    /// The whole ordered group bound by an enclosing `Effect::With` — the
    /// plural anaphor. Resolves to the frame's `those` binding, order
    /// preserved. Distinct from singular `That` (a `Reference`).
    Those,
    /// The set of objects chosen for the nth announced target spec
    /// ([CR#115.3,601.2c]) — the plural-target group fed to
    /// [`DivideAmong`](crate::DivideAmong) / [`Each`](crate::Each)
    /// (Idris `GetTargets`). Reads the announced-target set.
    GetTargets(usize),
    /// The extremal element(s) of a set, ranked by a per-element projection
    /// ([CR#107.1]): "the creature with the greatest power" =
    /// `Pick(op: Greatest, of: Type(Creature), by: StatOf(Subject, Power))`.
    /// The element-twin of the aggregate fold; the projection `by` reads each
    /// candidate via `Reference::Subject`, and ties yield the whole group
    /// (narrowed by the usual single/choice path downstream).
    Pick {
        op: Extremum,
        of: Filter,
        by: Box<Count>,
    },
    /// A remembered `Selection` macro invocation.
    #[macro_ron(expanded)]
    Expanded(Expansion<Selection>),
}

/// serde default for [`TopOfLibrary.of`] — the library belongs to "you"
/// unless the text names another player.
fn ref_you() -> Reference {
    Reference::You
}

/// `skip_serializing_if` predicate for [`TopOfLibrary.of`]: the default `You`
/// is omitted from RON.
fn ref_is_you(r: &Reference) -> bool {
    matches!(r, Reference::You)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CharacteristicFilter;
    use crate::Count;
    use crate::ObjectKind;
    use crate::Quantity;
    use crate::Type;

    fn read(source: &str) -> Selection {
        crate::ron::options().from_str(source).unwrap()
    }

    fn to_string(value: &Selection) -> String {
        crate::ron::options().to_string(value).unwrap()
    }

    #[test]
    fn filter_variant_round_trip() {
        let v = Selection::Filter(Filter::Kind(ObjectKind::Player));
        assert_eq!(read(&to_string(&v)), v);
    }

    #[test]
    fn random_round_trips() {
        let v = Selection::Random(
            Quantity::one(),
            Filter::Characteristic(CharacteristicFilter::Type(Type::Creature)),
        );
        assert_eq!(read(&to_string(&v)), v);
    }

    /// `GetTargets(n)` carries the announced-target index and round-trips — the
    /// plural-target group fed to `DivideAmong`/`Each` ([CR#115.3,601.2c]).
    #[test]
    fn get_targets_round_trips() {
        assert_eq!(read("GetTargets(0)"), Selection::GetTargets(0));
        let v = Selection::GetTargets(2);
        assert_eq!(read(&to_string(&v)), v);
    }

    #[test]
    fn top_of_library_round_trips() {
        let v = Selection::TopOfLibrary {
            count: Count::Literal(2),
            of: crate::Reference::You,
        };
        // `of: You` is the default and writes bare.
        assert_eq!(read("TopOfLibrary(count:2)"), v);
        assert_eq!(read(&to_string(&v)), v);
    }

    #[test]
    fn those_round_trips() {
        assert_eq!(read("Those"), Selection::Those);
        assert_eq!(read(&to_string(&Selection::Those)), Selection::Those);
    }

    /// `Pick` (extremal element) parses from named RON and round-trips — the
    /// element-twin of the aggregate fold.
    #[test]
    fn pick_round_trips() {
        let v = Selection::Pick {
            op: Extremum::Greatest,
            of: Filter::Characteristic(CharacteristicFilter::Type(Type::Creature)),
            by: Box::new(Count::StatOf(crate::Reference::This, crate::Stat::Power)),
        };
        assert_eq!(read(&to_string(&v)), v);
        assert!(matches!(
            read("Pick(op: Least, of: Type(Creature), by: StatOf(Subject, Toughness))"),
            Selection::Pick {
                op: Extremum::Least,
                ..
            },
        ));
    }
}
