use crate::Count;
use crate::Expansion;
use crate::Filter;
use crate::Quantity;
use crate::Reference;
use crate::SupportsMacros;

/// A Filter lifted into a resolution-time choice context: who picks, when,
/// how many ([CR#608.2d]). Verb object slots take exactly one `Selection`.
///
/// Targeting is NOT here — it lives in [`crate::TargetSpec`], the announce
/// list — because a target has legality recheck and retargeting rules the
/// other choice forms lack ([CR#115]). A [`Reference`] lifts into `Selection`
/// via [`Selection::Ref`] so a bound object can stand where a choice would.
///
/// `Ref` embeds `Reference` **untagged**, declared via `#[macro_ron(embed)]`:
/// authored RON writes a reference bare in a `Selection` slot (`Target(0)`,
/// `This`, `ControllerOf(This)`) with no `Ref(...)` wrapper, and reads back
/// as `Ref(...)`. Both serde impls are generated by
/// `#[derive(SupportsMacros)]` to carry that: the reader tries `Selection`'s
/// own variants and macros first, then falls through to a `Reference` (the
/// macro layer's `embeds_untagged` hook routes the fall-through here); the
/// writer emits the bare reference. `Expanded` writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum Selection {
    /// Every matching object, one at a time — distributive "each", no
    /// targeting, evaluated when the instruction applies ([CR#608.2d]).
    Each(Filter),
    /// All matching objects as one set — the shape continuous-effect
    /// scopes and set-wide instructions consume.
    Filter(Filter),
    /// A quantity of untargeted choices made at resolution ([CR#608.2d]).
    Choose(Quantity, Filter),
    /// A random selection of a quantity of matching objects.
    Random(Quantity, Filter),
    /// A choice from among a PREVIOUSLY COMPUTED set ("exile two of them",
    /// "…from among them" — the among-restriction, queries.md §2): the
    /// domain is whatever `Effect::Noting{key, …}` recorded under the
    /// key, not a re-evaluated filter — re-evaluation would be wrong for
    /// "this way" anaphora ([CR#607.2a] linkage).
    AmongNoted(crate::Ident, Quantity),
    /// The top `count` cards of a library, top → down (an ORDERED set —
    /// position is the whole point). `of` names the library's player; the
    /// default `You` writes bare. Feeds `With`/`Distribute` ([CR#701.22a]).
    TopOfLibrary {
        count: Count,
        #[serde(default = "ref_you", skip_serializing_if = "ref_is_you")]
        of: Reference,
    },
    /// The whole ordered group bound by an enclosing `Effect::With` — the
    /// plural anaphor. Resolves to the frame's `those` binding, order
    /// preserved. Distinct from singular `That` (a `Reference`).
    Those,
    /// A bound object reference, lifted into a choice slot. Written bare in
    /// RON (no `Ref(...)` wrapper) — see the type docs.
    #[macro_ron(embed)]
    Ref(Reference),
    /// A remembered `Selection` macro invocation.
    #[macro_ron(expanded)]
    Expanded(Expansion<Selection>),
}

/// Lifts a bound [`Reference`] into a `Selection`. Trivial now that the
/// reference embeds directly; kept for the call sites that build a selection
/// from a reference value.
impl From<Reference> for Selection {
    fn from(reference: Reference) -> Self {
        Selection::Ref(reference)
    }
}

/// serde default for [`TopOfLibrary.of`] — the library belongs to "you"
/// unless the text names another player.
fn ref_you() -> Reference {
    Reference::You
}

/// `skip_serializing_if` predicate for [`TopOfLibrary.of`]: the default `You`
/// is omitted from RON.
fn ref_is_you(r: &Reference) -> bool {
    matches!(r, Reference::You)
}

impl Selection {
    /// The self-reference lifted into a choice slot (`Ref(This)`) — the object
    /// being resolved, as picked by self-directed verbs (`Sacrifice(This)`,
    /// `Tap(This)`, …).
    #[must_use]
    pub fn this() -> Selection {
        Selection::Ref(Reference::This)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CharacteristicFilter;
    use crate::Count;
    use crate::ObjectKind;
    use crate::Quantity;
    use crate::Type;

    fn read(source: &str) -> Selection {
        crate::ron::options().from_str(source).unwrap()
    }

    fn to_string(value: &Selection) -> String {
        crate::ron::options().to_string(value).unwrap()
    }

    #[test]
    fn quantifiers_wrap_filters() {
        assert_eq!(
            read("Each(Kind(Player))"),
            Selection::Each(Filter::Kind(ObjectKind::Player)),
        );
    }

    #[test]
    fn filter_variant_round_trip() {
        let v = Selection::Filter(Filter::Kind(ObjectKind::Player));
        assert_eq!(read(&to_string(&v)), v);
    }

    #[test]
    fn choose_single_round_trip() {
        let v = Selection::Choose(
            Quantity::Exactly(Count::Literal(1)),
            Filter::Characteristic(CharacteristicFilter::Type(Type::Creature)),
        );
        assert_eq!(read(&to_string(&v)), v);
    }

    /// References lift into Selection flat — `This`, `Target(0)`, … read
    /// directly into `Ref(...)`, no wrapper in the RON.
    #[test]
    fn references_lift_flat() {
        assert_eq!(read("This"), Selection::Ref(Reference::This));
        assert_eq!(read("Target(0)"), Selection::Ref(Reference::Target(0)));
        assert_eq!(
            read("ControllerOf(This)"),
            Selection::Ref(Reference::ControllerOf(Box::new(Reference::This))),
        );
    }

    /// `From<Reference>` is now the trivial `Ref` wrap.
    #[test]
    fn from_reference_wraps_in_ref() {
        assert_eq!(
            Selection::from(Reference::This),
            Selection::Ref(Reference::This),
        );
        assert_eq!(
            Selection::from(Reference::Target(2)),
            Selection::Ref(Reference::Target(2)),
        );
        assert_eq!(
            Selection::from(Reference::AttachHostOf(Box::new(Reference::This))),
            Selection::Ref(Reference::AttachHostOf(Box::new(Reference::This))),
        );
    }

    /// A bare reference round-trips through the embedded `Ref`: it writes
    /// without a `Ref(...)` wrapper and reads back to the same value.
    #[test]
    fn ref_round_trips_bare() {
        for v in [
            Selection::Ref(Reference::Target(0)),
            Selection::Ref(Reference::This),
            Selection::Ref(Reference::ControllerOf(Box::new(Reference::This))),
        ] {
            let written = to_string(&v);
            assert!(
                !written.contains("Ref("),
                "reference should write bare, got {written}"
            );
            assert_eq!(read(&written), v);
        }
    }

    #[test]
    fn top_of_library_round_trips() {
        let v = Selection::TopOfLibrary {
            count: Count::Literal(2),
            of: crate::Reference::You,
        };
        // `of: You` is the default and writes bare.
        assert_eq!(read("TopOfLibrary(count:2)"), v);
        assert_eq!(read(&to_string(&v)), v);
    }

    #[test]
    fn those_round_trips() {
        assert_eq!(read("Those"), Selection::Those);
        assert_eq!(read(&to_string(&Selection::Those)), Selection::Those);
    }
}
