use crate::Expansion;
use crate::Filter;
use crate::Quantity;
use crate::SupportsMacros;

/// One entry in an ability's announce list ([CR#601.2c,115]). A `TargetSpec`
/// is the only place "target" lives: it binds `Reference::Target(n)` for the
/// effect body to read, and is rechecked at resolution ([CR#608.2b]).
///
/// Separated from [`crate::Selection`] so that resolution-time choices
/// (`Each`, `Choose`, …) and announce-time targets never share a position —
/// targeting has legality recheck and retargeting rules that the other
/// choice forms don't.
///
/// Both serde impls are generated by `#[derive(SupportsMacros)]`: `Expanded`
/// writes the invocation back.
#[derive(Debug, Clone, PartialEq, Eq, Hash, SupportsMacros)]
pub enum TargetSpec {
    /// A quantity of targets matching the filter ([CR#115.1,115.6,601.2c]).
    /// Use `Quantity::one()` for a single target, `Quantity::Range(None,
    /// Some(n))` for "up to N", and `Quantity::Range(None, None)` for "any
    /// number of targets" (or the `Exactly`/`AtMost`/`AnyNumber` macros at the
    /// RON surface).
    Target(Quantity, Filter),
    /// A co-target set-distinctness constraint ([CR#115.7e], Arc Trail's
    /// "any *other* target"): this spec's final picks must not overlap the
    /// sibling specs at the given indices. Evaluated on the FINAL target
    /// set — retargeting may swap members; only the whole set is checked,
    /// at announce and at the [CR#608.2b] re-check. Never a fixed-binding
    /// exclusion (that is `AllOf([…, Not(Ref(…))])` inside the filter).
    Distinct(Vec<usize>, Box<TargetSpec>),
    /// A remembered `TargetSpec` macro invocation.
    #[macro_ron(expanded)]
    Expanded(Expansion<TargetSpec>),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::CharacteristicFilter;
    use crate::Count;
    use crate::Quantity;
    use crate::Type;

    fn read(source: &str) -> TargetSpec {
        crate::ron::options().from_str(source).unwrap()
    }

    fn creature_filter() -> Filter {
        Filter::Characteristic(CharacteristicFilter::Type(Type::Creature))
    }

    /// The announce-list grammar: `Target(Quantity, Filter)`, distinct from
    /// `Selection`'s resolution choices. The core reader carries no macros, so
    /// these spell the underlying `Range` primitive directly (the named
    /// `Exactly`/`AtMost`/`AnyNumber` forms are exercised at the cards layer,
    /// where the builtin macros are loaded).
    #[test]
    fn announce_forms_read() {
        assert_eq!(
            read("Target(Range(1, 1), Type(Creature))"),
            TargetSpec::Target(Quantity::one(), creature_filter()),
        );
        assert_eq!(
            read("Target(Range(None, 2), Type(Creature))"),
            TargetSpec::Target(
                Quantity::Range(None, Some(Count::Literal(2))),
                creature_filter(),
            ),
        );
        assert_eq!(
            read("Target(Range(None, None), Type(Creature))"),
            TargetSpec::Target(Quantity::Range(None, None), creature_filter()),
        );
    }

    /// Pins the derived `Serialize` round-trip — serialize → read is identity.
    #[test]
    fn target_round_trips() {
        for value in [
            TargetSpec::Target(Quantity::one(), creature_filter()),
            TargetSpec::Target(Quantity::Range(None, None), creature_filter()),
            TargetSpec::Target(
                Quantity::Range(None, Some(Count::Literal(2))),
                creature_filter(),
            ),
        ] {
            let written = crate::ron::options().to_string(&value).unwrap();
            assert_eq!(read(&written), value, "round-trip failed for {value:?}");
        }
    }
}
