[package]
publish = false
name = "deckmaste_card"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
deckmaste_core = { version = "0.1.0", path = "../deckmaste_core" }
macro_ron = { version = "0.1.0", path = "../macro_ron", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }
