//! `cargo xtask lean-check` end to end: the gate really invokes `lake`, so
//! these tests prove the whole path — read a plugin, emit its cards, build the
//! generated Lean, attribute the diagnostics, ratchet the verdicts.
//!
//! Both tests write `lean/Generated/` and run one `lake` build, so they hold a
//! lock rather than racing each other over the shared workbench directory.

use std::path::Path;
use std::path::PathBuf;
use std::sync::Mutex;

use xtask::lean_check::LeanCheckArgs;

/// The workbench directory is shared state; one gate run at a time.
static GATE: Mutex<()> = Mutex::new(());

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// Whether `lake` can be run at all. The gate is a Lean gate: with no Lean
/// toolchain there is nothing to check, and the test says so rather than
/// passing vacuously.
fn lake_is_available() -> bool {
    std::process::Command::new("lake")
        .arg("--version")
        .output()
        .is_ok()
}

fn skip(test: &str) -> bool {
    if lake_is_available() {
        return false;
    }
    eprintln!("SKIPPED {test}: `lake` is not on PATH, so no Lean toolchain can build the gate");
    true
}

/// Copies a plugin tree so a test can bless a baseline into it without
/// touching the tracked fixture.
fn copy_tree(from: &Path, to: &Path) {
    std::fs::create_dir_all(to).expect("the destination is creatable");
    for entry in std::fs::read_dir(from).expect("the source reads") {
        let entry = entry.expect("the entry reads");
        let target = to.join(entry.file_name());
        if entry.file_type().expect("the entry has a type").is_dir() {
            copy_tree(&entry.path(), &target);
        } else {
            std::fs::copy(entry.path(), &target).expect("the file copies");
        }
    }
}

/// The fixture plugin the whole workspace is checked against by default.
#[test]
fn the_testing_plugin_proves_every_card() {
    if skip("the_testing_plugin_proves_every_card") {
        return;
    }
    let _guard = GATE
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    let plugin = workspace_root().join("plugins_v2/testing");
    xtask::lean_check::run(&LeanCheckArgs::new(vec![plugin], false))
        .expect("every card in plugins_v2/testing proves `Card.check = []` against its baseline");
}

/// "Lawless Land" is a land face printed with a mana cost, which `cardCostOk`
/// in `lean/Semantics/Check/Card.lean` refuses with `.cardCost`. The gate must
/// single that card out — its neighbour is an ordinary land and must still
/// prove — and the ratchet must refuse the run until the failure is blessed.
#[test]
fn a_card_that_breaks_a_card_law_is_singled_out_and_refused_until_blessed() {
    if skip("a_card_that_breaks_a_card_law_is_singled_out_and_refused_until_blessed") {
        return;
    }
    let _guard = GATE
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    let fixture = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/plugins_v2_lawless");
    let temp = tempfile::tempdir().expect("a scratch directory");
    let plugin = temp.path().join("plugins_v2_lawless");
    copy_tree(&fixture, &plugin);

    // A baseline that claims both cards prove, so the run below is exactly the
    // "a `pass` card fails" case.
    let baseline = plugin.join("lean-check-baseline.ron");
    std::fs::write(
        &baseline,
        "// Generated by `cargo xtask lean-check <plugin> --bless`; do not edit.\n(\n    version: \
         1,\n    cards: [\n        (card: \"Lawful Land\", verdict: Pass),\n        (card: \
         \"Lawless Land\", verdict: Pass),\n    ],\n)\n",
    )
    .expect("the baseline writes");

    let error = xtask::lean_check::run(&LeanCheckArgs::new(vec![plugin.clone()], false))
        .expect_err("a card that breaks a Lean law fails the gate");
    assert!(
        format!("{error:#}").contains("off their baseline"),
        "{error:#}"
    );

    xtask::lean_check::run(&LeanCheckArgs::new(vec![plugin.clone()], true))
        .expect("blessing records the verdicts as they are");
    let blessed = std::fs::read_to_string(&baseline).expect("the blessed baseline reads");
    assert!(
        blessed.contains("(card: \"Lawful Land\", verdict: Pass),"),
        "the lawful land still proves:\n{blessed}"
    );
    assert!(
        blessed.contains("card: \"Lawless Land\","),
        "the lawless land is recorded as failing:\n{blessed}"
    );
    assert!(
        blessed.contains("verdict: Fail(reason:") && blessed.contains("decide"),
        "the recorded reason is the Lean diagnostic head:\n{blessed}"
    );

    xtask::lean_check::run(&LeanCheckArgs::new(vec![plugin], false))
        .expect("a blessed failure ratchets clean on the next run");
}
