[package]
name = "deckmaste_english_v3"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
deckmaste_construction_v3 = { path = "../deckmaste_construction_v3" }
deckmaste_lexical = { version = "0.1.0", path = "../deckmaste_lexical" }
thiserror = { workspace = true }

[dev-dependencies]
deckmaste_lexical_source = { path = "../deckmaste_lexical_source" }
clap = { version = "4.6.1", features = ["derive"] }
