[package]
publish = false
name = "deckmaste_construction"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[lints]
workspace = true

[features]
parser-metrics = []

[dependencies]
deckmaste_construction_core = { path = "../deckmaste_construction_core" }

[dev-dependencies]
macro_ron = { path = "../macro_ron" }
trybuild = "1.0"
