[package]
publish = false
name = "macro_ron"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
derive = ["dep:macro_ron_derive"]

[dependencies]
dpsi = { version = "0.1.0", features = ["serde"] }
deckmaste_features = { version = "0.1.0", path = "../deckmaste_features" }
elsa = "1.11.2"
ron = "0.12.1"
serde = { version = "1.0.228", features = ["derive", "rc"] }
macro_ron_derive = { version = "0.1.0", path = "../macro_ron_derive", optional = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3.27.0"
