[package]
publish = false
name = "xtask"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = { version = "1.0.102" }
clap = { version = "4.6.1", features = ["derive"] }
deckmaste_cards = { version = "0.1.0", path = "../deckmaste_cards" }
deckmaste_core = { version = "0.1.0", path = "../deckmaste_core" }
deckmaste_migrations = { version = "0.1.0", path = "../deckmaste_migrations" }
