[package]
publish = false
name = "deckmaste_construction_core"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
macro_ron = { version = "0.1.0", path = "../macro_ron" }
proc-macro2 = "1.0.106"
quote = "1.0.45"
ron = "0.12.1"
serde = { version = "1.0.228", features = ["derive"] }
syn = { version = "2.0.117", features = ["extra-traits", "full", "visit"] }
prettyplease = "0.2"
thiserror = { workspace = true }

[dev-dependencies]
deckmaste_data = { path = "../deckmaste_data" }
tempfile = "3.27.0"
