[package]
publish = false
name = "deckmaste_english_v2"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.102"
deckmaste_catalogs = { version = "0.1.0", path = "../deckmaste_catalogs" }
deckmaste_construction = { version = "0.1.0", path = "../deckmaste_construction" }
macro_ron = { version = "0.1.0", path = "../macro_ron" }
thiserror = { workspace = true }

[dev-dependencies]
deckmaste_construction_core = { path = "../deckmaste_construction_core" }
proc-macro2 = "1.0.106"
syn = { version = "2.0.117", features = ["full", "visit"] }
tempfile = "3.27.0"
