[package]
publish = false
name = "deckmaste_english_v2"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
test-support = []

[dependencies]
anyhow = "1.0.102"
deckmaste_construction = { version = "0.1.0", path = "../deckmaste_construction" }
macro_ron = { version = "0.1.0", path = "../macro_ron" }
ron = "0.12.1"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
syn = { version = "2.0.117", features = ["full", "visit"] }
tempfile = "3.27.0"
