||| The grammar-table emitter: renders the checker tables the Rust load-time
||| elaborator (`deckmaste_cards::elaborate`) consumes, as RON data files under
||| `crates/deckmaste_cards/tables/`. Run via `idris/scripts/emit-tables`
||| (`idris2 --find-ipkg --exec emitTables src/EmitTables.idr` from `idris/`).
|||
||| DRIFT CONTROL: every row VALUE is computed by applying `Core.idr`'s total
||| functions (`eventKindCaps`, `actionEventCaps`, `counterScope`,
||| `designationScope`, `agentScope`, the `bind*` Ctx transforms over the v2
||| antecedent stack, `zoneSort`, `\/`) — never hand-copied. The only
||| hand-written parts are (a) the KEY mapping from the Rust grammar's
||| node/verb spellings to the Idris kinds, (b) the per-row CR citations, and
||| (c) the checker-rule manifest (the catalog of error codes, each of which
||| must also have a reject fixture on the Rust side). If a Core.idr function
||| changes, the emitted rows change, and the Rust side's regenerate-and-diff
||| turns red.
|||
||| v2 notes:
|||   * `actionEventCaps` is now TOTAL-BY-ENUMERATION in Core.idr (the v1
|||     `NoCaps` catch-all is gone); the cost-action rows below still spell
|||     each eligible verb explicitly — a verb with no row is cost-INELIGIBLE
|||     to the checker, never silently capless-but-legal.
|||   * every caps row carries the `patient:` kind the event actually fixes
|||     (from `EventCaps.patientKind`) and the checker gates `EventPatient`
|||     reads on it — `None` means the patient is unreachable, not kind-free.
|||   * the sort-compat rows, the intro rows, and the event-caps `object_sort`
|||     column are DERIVED (idris-tables-fixtures-v2): sort-compat enumerates
|||     `compat` over one representative `Sort` per key; the intro columns are
|||     read off `slotAnte`/`actionIntro`/`refIntro`/`binderAnte`/`bindIt`/
|||     `bindAllot` probes (the "from_*"/"From*" tags are computed by varying
|||     one axis); `object_sort` is computed from `eventKindObjectSort` + the
|||     row's caps. Hand data is down to the key mapping, the Rust
|||     participant-slot names, and the per-row cites.
|||   * the checker-rule manifest carries the fixture-TWIN disposition per
|||     code: `Idris` = a Spec.idr/Experimental.idr `failing` block twins it
|||     (the `-- @twin` annotations name the reject fixture; the Rust
|||     `twin_gate` test enforces both directions), `RustOnly(why)` = the rule
|||     deliberately has no Idris twin, with the documented reason.
module EmitTables

import Core
import Resolutions
import System
import System.File

%default total

-- --------------------------------------------------------------------------
-- rendering primitives
-- --------------------------------------------------------------------------

bool : Bool -> String
bool True = "true"
bool False = "false"

-- The Rust checker's kind names (RefKind, spelled for the table reader).
kindName : RefKind -> String
kindName Empty = "Empty"
kindName AnObject = "Object"
kindName APlayer = "Player"
kindName Anything = "Any"

optKind : Maybe RefKind -> String
optKind Nothing = "None"
optKind (Just k) = "Some(" ++ kindName k ++ ")"

quoted : String -> String
quoted s = "\"" ++ s ++ "\""

header : String -> String
header what =
  "// GENERATED by idris/src/EmitTables.idr — do not edit by hand.\n"
  ++ "// Regenerate with idris/scripts/emit-tables; CI diffs the output.\n"
  ++ "// " ++ what ++ "\n"

-- --------------------------------------------------------------------------
-- event caps ([CR#603.2e,608.2k]): what each event pattern supplies its body
-- --------------------------------------------------------------------------

-- Where an event form's OBJECT antecedent takes its SORT from (the
-- anaphor-surface role-ante machinery): a named participant slot of the form
-- ("source"/"what"/"by"/"of"/"on"), the destination zone's `zone_sort`
-- ("to_zone"), a fixed sort ("spell"/"stack_object"/"token"), or nothing
-- ("none" — the form supplies no object, or its object has no useful noun).
-- DERIVED from `Core.eventKindObjectSort` + the row's caps by
-- `objectSortTag` below; the participant-slot NAME is the one hand input
-- (Rust grammar keying, like the key mapping itself).
ObjectSort : Type
ObjectSort = String

-- A row's caps source: a modeled `EventKind` (caps + object sort from the
-- Core functions), or a literal caps value for the model-gap forms (no
-- EventKind spine yet — CoinFlipped/DiceRolled/day-night/designations/Used).
data CapsSource = FromKind EventKind | LiteralCaps EventCaps

rowCaps : CapsSource -> EventCaps
rowCaps (FromKind k) = eventKindCaps k
rowCaps (LiteralCaps c) = c

-- The `object_sort` TAG, computed from the model: "none" when the row's caps
-- supply no object; "to_zone" for the zone-parameterized family (there
-- `eventKindObjectSort` IS `zoneSort` of the new zone, with the conservative
-- `Card` when the destination is unfixed — pinned by the 0-proofs below,
-- which is exactly the Rust walker's "to_zone" interpretation); a fixed noun
-- tag where the function fixes a stack/token noun; otherwise the Rust
-- participant-slot name, whose walker fallback (an unfiltered slot) is
-- exactly the conservative `Permanent` the function returns.
objectSortTag : CapsSource -> (slot : Maybe String) -> ObjectSort
objectSortTag src slot =
  if not (hasObject (rowCaps src)) then "none"
  else case src of
    LiteralCaps _ => fromMaybe "none" slot
    FromKind (ZoneChanged _ _) => "to_zone"
    FromKind k => case eventKindObjectSort k of
      Spell => "spell"
      StackObject => "stack_object"
      Token => "token"
      _ => fromMaybe "none" slot

-- the "to_zone" pin: the zone-parameterized family's object noun IS the new
-- zone's (`zoneSort`), falling back to the conservative "card" when the
-- destination is unfixed — the two facts the Rust walker's "to_zone" arm
-- reproduces ([CR#400.7e]).
0 zoneTagPin : map (\z => eventKindObjectSort (ZoneChanged Nothing (Just z)))
                 (the (List Zone) [Battlefield, Command, Exile, Graveyard, Hand, Library, Sideboard, Stack])
             = map Core.zoneSort
                 (the (List Zone) [Battlefield, Command, Exile, Graveyard, Hand, Library, Sideboard, Stack])
zoneTagPin = Refl

0 zoneTagPinUnfixed : eventKindObjectSort (ZoneChanged Nothing Nothing) = Sort.Card
zoneTagPinUnfixed = Refl

-- the participant-slot pin: every slot-tagged row's kind answers to the
-- conservative `Permanent` in the model — the Rust walker's slot-extraction
-- fallback, refined per-pattern from the slot's own filter.
0 slotTagPin : map Core.eventKindObjectSort
                 (the (List EventKind)
                   [ DealDamage Nothing, PutCounters, RemoveCounters
                   , Begins Play, Begins Attack, Begins Block, Begins Attach
                   , Begins Target, Becomes Tapped, Becomes Untapped
                   , Becomes PhasedOut, Becomes FaceDown, GainControl ])
             = the (List Sort)
                 [ Permanent, Permanent, Permanent, Permanent, Permanent
                 , Permanent, Permanent, Permanent, Permanent, Permanent
                 , Permanent, Permanent, Permanent ]
slotTagPin = Refl

-- One row: the Rust-side event KEY (the `Event` node shape, or
-- `Performed:<verb>`), the caps VALUE + object-sort tag computed from the
-- source, the participant-slot name where the tag derivation consumes one,
-- the cite.
capsRow : (key : String) -> CapsSource -> (slot : Maybe String) -> (cite : String) -> String
capsRow key src slot cite =
  let MkEventCaps o a m p d = rowCaps src
      objectSort = objectSortTag src slot in
  "        (key: " ++ quoted key
  ++ ", object: " ++ bool o
  ++ ", actor: " ++ bool a
  ++ ", amount: " ++ bool m
  ++ ", patient: " ++ optKind p
  ++ ", defender: " ++ bool d
  ++ ", object_sort: " ++ quoted objectSort
  ++ ", cite: " ++ quoted cite ++ "),\n"

-- The key mapping: each Rust `EventFilter` MASTER FORM → the Idris
-- `EventKind` whose `eventKindCaps` value the row carries. A form with no
-- row supplies NOTHING to the checker (safe direction: a body anaphor under
-- an unknown form is rejected). The handful of literal rows (marked) are
-- model gaps like the two documented holes above: forms the Idris EventKind
-- spine doesn't carry yet, given deliberate explicit values.
eventCapsRows : List String
eventCapsRows =
  [ -- object/zone forms. The moved object's noun follows its NEW zone
    -- ([CR#400.7] — the new object in the zone it moved to; the "to_zone"
    -- tag is computed by `objectSortTag`, pinned by `zoneTagPin`).
    capsRow "ZoneChange" (FromKind (ZoneChanged Nothing Nothing)) Nothing "[CR#603.6]"
    -- the recipient is a kind-poly patient ([CR#120.3] "a player or permanent")
  , capsRow "Damage" (FromKind (DealDamage Nothing {toKind = Just Anything})) (Just "source") "[CR#120.1]"
  , capsRow "LifeGained" (FromKind GainLife) Nothing "[CR#119.3]"
  , capsRow "LifeLost" (FromKind LoseLife) Nothing "[CR#119.3]"
  , capsRow "Drawn" (FromKind Draw) Nothing "[CR#121.1]"
  , capsRow "CounterPlaced" (FromKind PutCounters) (Just "on") "[CR#122.1]"
  , capsRow "CounterRemoved" (FromKind RemoveCounters) (Just "on") "[CR#122.1]"
    -- the onset family ([CR#603.2]) — the relation spine's inchoative aspect
  , capsRow "Cast" (FromKind (Begins Cast)) Nothing "[CR#601.2i]"
  , capsRow "Played" (FromKind (Begins Play)) (Just "what") "[CR#701.18a]"
  , capsRow "ActivatedAb" (FromKind (Begins Activate)) Nothing "[CR#602.2a]"
  , capsRow "AttackDeclared" (FromKind (Begins Attack)) (Just "by") "[CR#508.1k]"
  , capsRow "BlockDeclared" (FromKind (Begins Block)) (Just "by") "[CR#509.3a,509.3c]"
  , capsRow "Attached" (FromKind (Begins Attach)) (Just "what") "[CR#701.3a]"
  , capsRow "BecomesTarget" (FromKind (Begins Target)) (Just "what") "[CR#601.2c]"
    -- residual status transitions ([CR#603.2e])
  , capsRow "StateBecame:Tapped" (FromKind (Becomes Tapped)) (Just "of") "[CR#603.2e]"
  , capsRow "StateBecame:Untapped" (FromKind (Becomes Untapped)) (Just "of") "[CR#603.2e]"
  , capsRow "StateBecame:Phased" (FromKind (Becomes PhasedOut)) (Just "of") "[CR#702.26b]"
  , capsRow "StateBecame:TurnedFace" (FromKind (Becomes FaceDown)) (Just "of") "[CR#708]"
    -- turn structure / control / designations
  , capsRow "StepBegins" (FromKind (BeginStep (BeginningPhase UpkeepStep))) Nothing "[CR#603.2b]"
  , capsRow "ControlChanged" (FromKind GainControl) (Just "of") "[CR#613.1b]"
  , capsRow "DesignationChanged" (LiteralCaps NoCaps) Nothing "[CR#109.3]"
  , capsRow "TokenCreated" (FromKind CreateToken) Nothing "[CR#701.7]"
  , capsRow "Used" (LiteralCaps NoCaps) Nothing "[CR#608.2i]"
    -- literal rows (no EventKind yet): the flipping/rolling player is the
    -- actor; day/night is a game-scope expletive with no participants.
  , capsRow "CoinFlipped" (LiteralCaps (MkEventCaps False True False Nothing False)) Nothing "[CR#705.1]"
  , capsRow "DiceRolled" (LiteralCaps (MkEventCaps False True False Nothing False)) Nothing "[CR#706.1]"
  , capsRow "BecameDay" (LiteralCaps NoCaps) Nothing "[CR#731.1]"
  , capsRow "BecameNight" (LiteralCaps NoCaps) Nothing "[CR#731.1]"
  ]

eventCapsTable : String
eventCapsTable =
  header "Event caps: what each event pattern supplies its body's anaphora ([CR#603.2e,608.2k])."
  ++ "(\n    rows: [\n" ++ concat eventCapsRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- cause-verb entailments ([CR#701] keyword actions): verb → fact form
-- --------------------------------------------------------------------------

zoneName : Zone -> String
zoneName Battlefield = "Battlefield"
zoneName Command = "Command"
zoneName Exile = "Exile"
zoneName Graveyard = "Graveyard"
zoneName Hand = "Hand"
zoneName Library = "Library"
zoneName Sideboard = "Sideboard"
zoneName Stack = "Stack"

optZone : Maybe Zone -> String
optZone Nothing = "None"
optZone (Just z) = "Some(" ++ zoneName z ++ ")"

-- One row: the Rust `CauseVerb` spelling, the entailed master-form KIND (an
-- event-caps key), the zone coordinates the verb fixes, and the caps
-- guarantees a cause-narrowed pattern inherits (object/actor/amount; the
-- verb's own EventKind caps where the model has one, literal for the four
-- verbs outside the EventKind spine — model gaps like the documented holes).
entailRow : (verb : String) -> (kind : String)
         -> (from : Maybe Zone) -> (to : Maybe Zone)
         -> EventCaps -> (cite : String) -> String
entailRow verb kind from to (MkEventCaps o a m _ _) cite =
  "        (verb: " ++ quoted verb
  ++ ", kind: " ++ quoted kind
  ++ ", from: " ++ optZone from
  ++ ", to: " ++ optZone to
  ++ ", object: " ++ bool o
  ++ ", actor: " ++ bool a
  ++ ", amount: " ++ bool m
  ++ ", cite: " ++ quoted cite ++ "),\n"

-- Mill's entailed destination ([CR#701.17a]) — single-sourced: the
-- entailment row AND the Mill intro row's noun/zone (via `zoneSort`) read
-- this one definition (the Rust Mill player verb has no Idris Action twin).
millTo : Zone
millTo = Graveyard

-- The closed `CauseVerb` vocabulary, one CR-cited fact form each: the
-- normal form that makes Dies-matches-sacrifice structural and kills the
-- stringly `Performed` verb table.
entailmentRows : List String
entailmentRows =
  [ entailRow "Sacrifice" "ZoneChange" (Just Battlefield) (Just Graveyard)
      (eventKindCaps Sacrifice) "[CR#701.21a]"
  , entailRow "Destroy" "ZoneChange" (Just Battlefield) (Just Graveyard)
      (eventKindCaps Destroy) "[CR#701.8a]"
  , entailRow "Discard" "ZoneChange" (Just Hand) (Just Graveyard)
      (eventKindCaps Discard) "[CR#701.9a]"
  , entailRow "Exile" "ZoneChange" Nothing (Just Exile)
      (MkEventCaps True False False Nothing False) "[CR#701.13a]"
  , entailRow "Mill" "ZoneChange" (Just Library) (Just millTo)
      (MkEventCaps True True False Nothing False) "[CR#701.17a]"
  , entailRow "Play" "ZoneChange" Nothing (Just Battlefield)
      (eventKindCaps (Begins Play)) "[CR#701.18a]"
    -- fight damage is noncombat damage dealt by the fighting creature
  , entailRow "Fight" "Damage" Nothing Nothing
      (MkEventCaps True False True Nothing False) "[CR#701.14a]"
    -- explore reveals from the library; the card lands in hand or graveyard
  , entailRow "Explore" "ZoneChange" (Just Library) Nothing
      (MkEventCaps True True False Nothing False) "[CR#701.44a]"
    -- an applied regeneration shield's visible fact is the tap
  , entailRow "Regenerate" "StateBecame:Tapped" Nothing Nothing
      (eventKindCaps (Begins Regenerate)) "[CR#701.19a]"
  ]

entailmentTable : String
entailmentTable =
  header "Cause-verb entailments ([CR#701] keyword actions): each CauseVerb's fact form + inherited caps."
  ++ "(\n    rows: [\n" ++ concat entailmentRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- event lanes (the plan's §3.2 lane table): per-consumer algebra gates
-- --------------------------------------------------------------------------

-- Which LANE CLASS of the one evaluator ([[engine-one-evaluator]],
-- `eval.rs`) a consumer position's patterns run in: Live (trigger/delayed
-- scanning of a fact in its own wake), Would (the replacement pipeline's
-- intercepted intents), or History (recorded facts matched through their
-- per-fact LKI views). The bridge-caps table below is keyed per class.
data Matcher = Live | Would | History

matcherName : Matcher -> String
matcherName Live = "Live"
matcherName Would = "Would"
matcherName History = "History"

-- One row: the walker's lane key, whether `Within` / `Nth` / `OneOrMore`
-- are admitted, whether every disjunct must be kind-anchored (bottom
-- out in a master form), and the bridge matcher the lane evaluates on.
-- Positional discipline like `bindRows`' caps_from — per-row data, each
-- cited.
laneRow : (lane : String) -> (within : Bool) -> (nth : Bool)
       -> (oneOrMore : Bool) -> (anchored : Bool) -> Matcher
       -> (cite : String) -> String
laneRow lane within nth oneOrMore anchored matcher cite =
  "        (lane: " ++ quoted lane
  ++ ", within: " ++ bool within
  ++ ", nth: " ++ bool nth
  ++ ", one_or_more: " ++ bool oneOrMore
  ++ ", anchored: " ++ bool anchored
  ++ ", matcher: " ++ matcherName matcher
  ++ ", cite: " ++ quoted cite ++ "),\n"

laneRows : List String
laneRows =
  [ -- live lanes: a history window is vacuous against a live fact
    laneRow "Triggered.event" False True True True Live "[CR#603.2]"
  , laneRow "Delayed.event" False True True True Live "[CR#603.7c]"
  , laneRow "Replacement.would" False True True True Would "[CR#614.1]"
  , laneRow "CantHappen" False True True True Would "[CR#614.17c]"
  , laneRow "UntilEvent" False True True True Live "[CR#610.3]"
    -- the multiplier watches another ability's trigger — no ordinals
  , laneRow "TriggerMultiplier.cause" False False True True Live "[CR#603.2d]"
    -- history lanes: the window is the required field; batches don't count
  , laneRow "Happened" True True False False History "[CR#608.2i]"
  ]

laneTable : String
laneTable =
  header "Event lanes: which algebra refinements each consumer position admits ([CR#603.2,608.2i])."
  ++ "(\n    rows: [\n" ++ concat laneRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- bridge caps (`engine-eventfilter-bridge`): per-atom matcher support
-- --------------------------------------------------------------------------

-- One row: an `EventFilter` ATOM (a master-form key, a `Form:field`
-- refinement, an algebra node, or a `Lookback:*` history window) and
-- whether the ONE evaluator ([[engine-one-evaluator]], the engine's
-- `eval.rs`) evaluates it FAITHFULLY in each lane class. An unsupported
-- atom is load-REJECTED (`E-BRIDGE-CAP`), never silently mis-matched.
-- Every remaining False is a DELIBERATE cap with its reason inline (a
-- missing fact shape, a CR-grounded granularity, a family owned by
-- another subsystem); support values stay ENGINE capability facts,
-- pinned by the engine's bridge-agreement tests.
bridgeRow : (atom : String) -> (live : Bool) -> (would : Bool)
         -> (history : Bool) -> (cite : String) -> String
bridgeRow atom live would history cite =
  "        (atom: " ++ quoted atom
  ++ ", live: " ++ bool live
  ++ ", would: " ++ bool would
  ++ ", history: " ++ bool history
  ++ ", cite: " ++ quoted cite ++ "),\n"

bridgeRows : List String
bridgeRows =
  [ -- master forms. The one evaluator (engine-one-evaluator) serves every
    -- lane; a False would-column marks a kind the replacement pipeline does
    -- not intercept as an intent (`replace_registry::replaceable`) — those
    -- caps are DELIBERATE, each with its reason below.
    bridgeRow "ZoneChange" True True True "[CR#603.6]"
  , bridgeRow "Damage" True True True "[CR#120.1]"
  , bridgeRow "LifeGained" True True True "[CR#119.3]"
  , bridgeRow "LifeLost" True True True "[CR#119.3]"
  , bridgeRow "Drawn" True True True "[CR#121.1]"
  , bridgeRow "CounterPlaced" True True True "[CR#122.1]"
  , bridgeRow "CounterRemoved" True True True "[CR#122.1]"
  , bridgeRow "Cast" True True True "[CR#601.2i]"
  , bridgeRow "Played" True True True "[CR#701.18a]"
  , bridgeRow "ActivatedAb" True True True "[CR#602.2a]"
    -- attack/block prevention rides the Cant statics, not the replacement
    -- pipe (declare-time legality, no would-intent stage)
  , bridgeRow "AttackDeclared" True False True "[CR#508.1k]"
  , bridgeRow "BlockDeclared" True False True "[CR#509.3a]"
    -- the Attached fact follows the already-performed relation mutation
  , bridgeRow "Attached" True False True "[CR#701.3a]"
    -- tap/untap prevention rides the Cant/Skip families, not the pipe
  , bridgeRow "StateBecame:Tapped" True False True "[CR#603.2e]"
  , bridgeRow "StateBecame:Untapped" True False True "[CR#603.2e]"
    -- phasing / turn-face have no fact shapes yet (P0.W6)
  , bridgeRow "StateBecame:Phased" False False False "[CR#702.26b]"
  , bridgeRow "StateBecame:TurnedFace" False False False "[CR#708]"
    -- targeting is announce-time legality, never a replaceable event
  , bridgeRow "BecomesTarget" True False True "[CR#601.2c]"
    -- step onsets are recorded (active player on the view); skipping a
    -- step is the Skip elision pass, not a would-replacement
  , bridgeRow "StepBegins" True False True "[CR#603.2b]"
    -- no control-change emitter yet; prevention is Cant-static territory
  , bridgeRow "ControlChanged" True False True "[CR#613.1b]"
  , bridgeRow "DesignationChanged" True True True "[CR#109.3]"
  , bridgeRow "TokenCreated" True True True "[CR#701.7a]"
    -- AbilityUsed is recorded directly to history, never routed as an
    -- interceptable intent
  , bridgeRow "Used" True False True "[CR#608.2i]"
    -- coin/die facts carry an already-decided outcome — no would stage
  , bridgeRow "CoinFlipped" True False True "[CR#705.1]"
  , bridgeRow "DiceRolled" True False True "[CR#706.1]"
  , bridgeRow "BecameDay" True True True "[CR#731.1]"
  , bridgeRow "BecameNight" True True True "[CR#731.1]"
    -- refinement atoms (checked only when the field is present / non-default)
  , bridgeRow "Damage:combat" True True True "[CR#510.1]"
  , bridgeRow "Damage:amount" True True True "[CR#120.1]"
  , bridgeRow "LifeGained:amount" True True True "[CR#119.3]"
  , bridgeRow "LifeLost:amount" True True True "[CR#119.3]"
    -- KEPT: cards are drawn one at a time ([CR#121.2]) — a multi-draw is N
    -- facts, so a per-fact amount bound has nothing to compare against
  , bridgeRow "Drawn:amount" False False False "[CR#121.1]"
  , bridgeRow "CounterPlaced:amount" True True True "[CR#122.1]"
  , bridgeRow "CounterRemoved:amount" True True True "[CR#122.1]"
    -- KEPT: the fact carries the token SPEC — pre-mint spec matching needs
    -- a spec-side filter evaluator (design-gated)
  , bridgeRow "TokenCreated:what" False False False "[CR#701.7a]"
    -- KEPT: the hexproof-from source arm has no fact-record coordinate
  , bridgeRow "BecomesTarget:source" False False False "[CR#702.11d,702.16b]"
    -- KEPT: flip-WIN is call-relative; the fact records only heads
  , bridgeRow "CoinFlipped:won" False False False "[CR#705.2]"
    -- would-facts keep the raw engine cause triple — agent included
  , bridgeRow "Cause:agent" True True True "[CR#603.2]"
    -- `of` resolves through the consumer's frame (bound references are
    -- E-BIND-guarded); frameless lanes still reach the self-scoped `This`
    -- through the watcher. Would-lane stays False with `Used` above.
  , bridgeRow "Used:of" True False True "[CR#608.2i]"
    -- `Filter::Where` under a snapshot-evaluated participant slot: the
    -- snapshot matcher binds the candidate as `It` and evaluates the
    -- condition ([CR#603.10a])
  , bridgeRow "Where-in-snapshot" True True True "[CR#603.10a]"
    -- algebra nodes
  , bridgeRow "AllOf" True True True "[CR#603.2]"
  , bridgeRow "OneOf" True True True "[CR#603.2c]"
  , bridgeRow "Not" True True True "[CR#603.2]"
  , bridgeRow "Nth" True True True "[CR#603.2g]"
    -- When's condition is evaluated as the event occurs; a HISTORY read
    -- cannot reconstruct the as-it-occurred state ([CR#603.4]) — kept
  , bridgeRow "When" True True False "[CR#603.4]"
    -- Within is the history-window refinement; in live/would lanes it is
    -- vacuous BY DESIGN and stays refused (mirrors the lane table)
  , bridgeRow "Within" False False True "[CR#608.2i]"
  , bridgeRow "OneOrMore" True True False "[CR#603.2c]"
    -- history windows: open windows feed live-lane Nth ordinals too; a
    -- CLOSED past window (LastTurn) can never contain a current occurrence
    -- and stays live/would-refused; sub-turn markers are recorded
    -- (StepBegan) but no window derivation consumes them yet
    -- (engine-history-windows)
  , bridgeRow "Lookback:ThisTurn" True True True "[CR#608.2i]"
  , bridgeRow "Lookback:ThisGame" True True True "[CR#608.2i]"
  , bridgeRow "Lookback:LastTurn" False False True "[CR#608.2i]"
  , bridgeRow "Lookback:ThisCombat" False False False "[CR#506.1]"
  , bridgeRow "Lookback:ThisStep" False False False "[CR#500.1]"
  , bridgeRow "Lookback:SinceYour" False False False "[CR#603.2b]"
  ]

bridgeTable : String
bridgeTable =
  header "Bridge caps: which EventFilter atoms the one evaluator (engine-one-evaluator) evaluates faithfully per lane class; unsupported atoms are load-rejected (E-BRIDGE-CAP), each a deliberate cap ([CR#603.2])."
  ++ "(\n    rows: [\n" ++ concat bridgeRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- cost actions ([CR#118.3]): eligibility + payment-event caps
-- --------------------------------------------------------------------------

costRow : (action : String) -> EventCaps -> (cite : String) -> String
costRow action (MkEventCaps o a m p d) cite =
  "        (action: " ++ quoted action
  ++ ", object: " ++ bool o
  ++ ", actor: " ++ bool a
  ++ ", amount: " ++ bool m
  ++ ", patient: " ++ optKind p
  ++ ", defender: " ++ bool d
  ++ ", cite: " ++ quoted cite ++ "),\n"

-- Explicit row per cost-eligible player verb ([CR#118.3,601.2b]) — a verb
-- with NO row is not cost-eligible; there is no catch-all. The first three
-- ride `actionEventCaps` (the rows Core.idr defines); the rest are the
-- catch-all's victims, given their true caps via the matching event kind.
costActionRows : List String
costActionRows =
  [ costRow "Sacrifice" (actionEventCaps (the (Action Base) (Sacrifice (SameAs This)))) "[CR#701.21a]"
  , costRow "Discard" (actionEventCaps (the (Action Base) (Discard (Literal 1)))) "[CR#701.9a]"
  , costRow "Move" (actionEventCaps (the (Action Base) (Move This (ToZone Exile)))) "[CR#701.13]"
  , costRow "Tap" (eventKindCaps (Becomes Tapped)) "[CR#701.26a]"
  , costRow "Untap" (eventKindCaps (Becomes Untapped)) "[CR#701.26b]"
  , costRow "LoseLife" (eventKindCaps LoseLife) "[CR#119.3]"
  , costRow "RemoveCounters" (eventKindCaps RemoveCounters) "[CR#122.1]"
    -- Reveal has no event kind in the model; it binds nothing ([CR#701.20a]).
  , costRow "Reveal" NoCaps "[CR#701.20a]"
  ]

costActionTable : String
costActionTable =
  header "Cost-eligible player verbs ([CR#118.3,601.2b]) + the caps their payment event supplies an AdditionalCost body ([CR#601.2f])."
  ++ "(\n    rows: [\n" ++ concat costActionRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- scopes: counter carriers, designation carriers, deed agents
-- --------------------------------------------------------------------------

-- The Rust registry name of each curated counter kind (`CounterRef` idents
-- as the corpus spells them: object counters `<Kind>Counter`, player
-- counters bare).
rustCounterName : CounterKind -> String
rustCounterName Loyalty = "LoyaltyCounter"
rustCounterName Fate = "FateCounter"
rustCounterName Charge = "ChargeCounter"
rustCounterName P1P1 = "P1P1Counter"
rustCounterName M1M1 = "M1M1Counter"
rustCounterName Level = "LevelCounter"
rustCounterName Lore = "LoreCounter"
rustCounterName Stun = "StunCounter"
rustCounterName Shield = "ShieldCounter"
rustCounterName Poison = "Poison"
rustCounterName Energy = "Energy"
rustCounterName Experience = "Experience"

counterCite : CounterKind -> String
counterCite Poison = "[CR#122.1f]"
counterCite _ = "[CR#122.1]"

counterRow : CounterKind -> String
counterRow c =
  "        (name: " ++ quoted (rustCounterName c)
  ++ ", scope: " ++ kindName (counterScope c)
  ++ ", cite: " ++ quoted (counterCite c) ++ "),\n"

allCounterKinds : List CounterKind
allCounterKinds =
  [Loyalty, Fate, Charge, P1P1, M1M1, Level, Lore, Stun, Shield, Poison, Energy, Experience]

designationName : Designation -> String
designationName Monarch = "Monarch"
designationName TheInitiative = "TheInitiative"
designationName CitysBlessing = "CitysBlessing"
designationName Monstrous = "Monstrous"
designationName Goaded = "Goaded"
designationName Renowned = "Renowned"
designationName Suspected = "Suspected"
designationName Saddled = "Saddled"
designationName Solved = "Solved"

-- Per-designation CR homes, each verified against the CR text.
designationCite : Designation -> String
designationCite Monarch = "[CR#725.1]"
designationCite TheInitiative = "[CR#726.1]"
designationCite CitysBlessing = "[CR#702.131c]"
designationCite Monstrous = "[CR#701.37b]"
designationCite Goaded = "[CR#701.15b]"
designationCite Renowned = "[CR#702.112b]"
designationCite Suspected = "[CR#701.60b]"
designationCite Saddled = "[CR#702.171a]"
designationCite Solved = "[CR#719.3b]"

designationRow : Designation -> String
designationRow d =
  "        (name: " ++ quoted (designationName d)
  ++ ", scope: " ++ kindName (designationScope d)
  ++ ", cite: " ++ quoted (designationCite d) ++ "),\n"

allDesignations : List Designation
allDesignations =
  [Monarch, TheInitiative, CitysBlessing, Monstrous, Goaded, Renowned, Suspected, Saddled, Solved]

relationName : Relation -> String
relationName Attack = "Attack"
relationName Block = "Block"
relationName Cast = "Cast"
relationName Activate = "Activate"
relationName Play = "Play"
relationName Attach = "Attach"
relationName Target = "Target"
relationName Counter = "Counter"
relationName Regenerate = "Regenerate"

relationCite : Relation -> String
relationCite Attack = "[CR#508.1a]"
relationCite Block = "[CR#509.1a]"
relationCite Cast = "[CR#601.3]"
relationCite Activate = "[CR#602.1]"
relationCite Play = "[CR#701.18]"
relationCite Attach = "[CR#701.3a]"
relationCite Target = "[CR#115.1]"
relationCite Counter = "[CR#701.6a]"
relationCite Regenerate = "[CR#701.19]"

agentRow : Relation -> String
agentRow r =
  "        (relation: " ++ quoted (relationName r)
  ++ ", scope: " ++ kindName (agentScope r)
  ++ ", cite: " ++ quoted (relationCite r) ++ "),\n"

-- Per-relation PATIENT homes, each verified against the CR text: attack
-- reaches players/planeswalkers/battles, block reaches attackers, attach
-- reaches objects or players, targeting anything targetable; the rest act
-- on objects.
patientCite : Relation -> String
patientCite Attack = "[CR#508.1b]"
patientCite Block = "[CR#509.1a]"
patientCite Cast = "[CR#601.2a]"
patientCite Activate = "[CR#113.3b]"
patientCite Play = "[CR#701.18a]"
patientCite Attach = "[CR#701.3a]"
patientCite Target = "[CR#115.4]"
patientCite Counter = "[CR#701.6a]"
patientCite Regenerate = "[CR#701.19a]"

patientRow : Relation -> String
patientRow r =
  "        (relation: " ++ quoted (relationName r)
  ++ ", scope: " ++ kindName (patientScope r)
  ++ ", cite: " ++ quoted (patientCite r) ++ "),\n"

allRelations : List Relation
allRelations = [Attack, Block, Cast, Activate, Play, Attach, Target, Counter, Regenerate]

scopesTable : String
scopesTable =
  header "Carrier scopes: counter kinds ([CR#122.1]), designations, deed agents (`agentScope`)."
  ++ "(\n"
  ++ "    // `counterScope`'s object default IS model content ([CR#122.1] —\n"
  ++ "    // counters are object-borne unless a player-borne kind says so).\n"
  ++ "    counter_default: Object,\n"
  ++ "    counters: [\n" ++ concatMap counterRow allCounterKinds ++ "    ],\n"
  ++ "    designations: [\n" ++ concatMap designationRow allDesignations ++ "    ],\n"
  ++ "    agents: [\n" ++ concatMap agentRow allRelations ++ "    ],\n"
  ++ "    patients: [\n" ++ concatMap patientRow allRelations ++ "    ],\n"
  ++ ")\n"

-- --------------------------------------------------------------------------
-- kind lattice: the RefKind join ([CR#115.4] — "any target" is the top)
-- --------------------------------------------------------------------------

allKinds : List RefKind
allKinds = [Empty, AnObject, APlayer, Anything]

joinRow : (RefKind, RefKind) -> String
joinRow (a, b) =
  "        (left: " ++ kindName a
  ++ ", right: " ++ kindName b
  ++ ", join: " ++ kindName ((\/) a b) ++ "),\n"

latticeTable : String
latticeTable =
  header "The RefKind join-semilattice (`\\/`): OneOf widens object|player to Any ([CR#115.4])."
  ++ "(\n    joins: [\n"
  ++ concatMap joinRow [(a, b) | a <- allKinds, b <- allKinds]
  ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- bind rules: how each construct transforms the binding context
-- --------------------------------------------------------------------------

-- The probe: a Ctx with one antecedent of EVERY interesting site on the
-- stack (a target slot, a `With` frame, a loop element, an allotment) plus
-- full caps and both chosen channels — applying a transform and diffing
-- the stack's site population reveals exactly what it drops/keeps/binds.
fullCaps : EventCaps
fullCaps = MkEventCaps True True True (Just AnObject) True

slotProbe : Ante
slotProbe = MkAnte Permanent AnObject One TargetSlot Nothing Nothing

frameProbe : Cardinality -> Ante
frameProbe c = MkAnte Permanent AnObject c Frame Nothing Nothing

loopProbe : Ante
loopProbe = MkAnte Permanent AnObject One Loop Nothing Nothing

allotProbe : Ante
allotProbe = MkAnte Amount Anything One Allot Nothing Nothing

probe : Ctx
probe = MkCtx [slotProbe, frameProbe One, loopProbe, allotProbe] fullCaps
              (Just AColor) (Just AnObject)

cardinalityName : Cardinality -> String
cardinalityName One = "One"
cardinalityName Many = "Many"

optBool : Maybe Bool -> String
optBool Nothing = "None"
optBool (Just b) = "Some(" ++ bool b ++ ")"

-- site-population probes over a stack (the column extractors).
hasSlotA : List Ante -> Bool
hasSlotA = any (\a => isTargetSlot a.site)

hasLoopA : List Ante -> Bool
hasLoopA = any (\a => isBinderSite a.site && not (isFrameSite a.site))

hasAllotP : List Ante -> Bool
hasAllotP = hasAllot

frameCard : List Ante -> Maybe Cardinality
frameCard s = map (.card) (innermostFrame s)

optCard : Maybe Cardinality -> String
optCard Nothing = "None"
optCard (Just c) = "Some(" ++ cardinalityName c ++ ")"

isJust' : Maybe a -> Bool
isJust' Nothing = False
isJust' (Just _) = True

-- One row, with the drop/keep/bind fields COMPUTED by applying `transform`
-- to the all-bound probe (drops) and to `Base` (binds) and reading the
-- stack's site population. `caps_from` and `may_target` are positional
-- discipline the stack doesn't carry (may_target per
-- [CR#115.1a..115.1e,601.2c]), so they are per-row data here.
bindRow : (construct : String) -> (transform : Ctx -> Ctx)
       -> (capsFrom : String) -> (mayTarget : Maybe Bool) -> (cite : String)
       -> String
bindRow construct transform capsFrom mayTarget cite =
  let after = transform probe in
  let fresh = transform Base in
  "        (construct: " ++ quoted construct
  ++ ", drops_targets: " ++ bool (not (hasSlotA (stack after)))
  ++ ", keeps_that: " ++ bool (isJust' (frameCard (stack after)))
  ++ ", binds_targets: " ++ bool (hasSlotA (stack fresh))
  ++ ", binds_that: " ++ optCard (frameCard (stack fresh))
  ++ ", binds_it: " ++ bool (hasLoopA (stack fresh))
  ++ ", binds_allotment: " ++ bool (hasAllotP (stack fresh))
  ++ ", clears_allotment: " ++ bool (not (hasAllotP (stack after)))
  ++ ", caps_from: " ++ capsFrom
  ++ ", may_target: " ++ optBool mayTarget
  ++ ", cite: " ++ quoted cite ++ "),\n"

bindRows : List String
bindRows =
  [ bindRow "Targeted" (bindTargets [slotProbe]) "Keep" Nothing "[CR#115.1,601.2c]"
  , bindRow "With.One" (bindThat (frameProbe One)) "Keep" Nothing "[CR#608.2d]"
  , bindRow "With.Many" (bindThat (frameProbe Many)) "Keep" Nothing "[CR#608.2d]"
  , bindRow "Each" (bindIt loopProbe) "Keep" (Just False) "[CR#608.2]"
  , bindRow "DivideAmong" (bindAllot loopProbe) "Keep" (Just False) "[CR#601.2d]"
    -- Delayed: schedule for later — targets are DROPPED, the frame/product
    -- antecedents survive ([CR#603.7c]); the body reads the delayed event's
    -- own caps; a delayed trigger may announce its own targets.
  , bindRow "Delayed" (bindEvent NoCaps [] . unbindTargets) "Query" (Just True) "[CR#603.7c]"
    -- Reflexive: "when you do" — sees the FULL outer context ([CR#603.12a]).
  , bindRow "Reflexive" (bindEvent NoCaps []) "Query" (Just True) "[CR#603.12a]"
  , bindRow "Triggered" (bindEvent NoCaps []) "Query" (Just True) "[CR#603.2]"
  , bindRow "Replacement.Instead" (bindEvent NoCaps []) "Query" (Just False) "[CR#614.1a]"
  , bindRow "Replacement.Also" (bindEvent NoCaps []) "Query" (Just False) "[CR#614.1c]"
  , bindRow "AdditionalCost" (bindEvent NoCaps []) "Cost" Nothing "[CR#601.2f]"
    -- MayPay's "if they do" branch reads the payment like an
    -- AdditionalCost body ([CR#608.2d] resolution-time choices).
  , bindRow "MayPay" (bindEvent NoCaps []) "Cost" Nothing "[CR#608.2d]"
    -- Filter::Where / Selection::Pick bind the candidate as `It`.
  , bindRow "Where" (bindIt loopProbe) "Keep" Nothing "[CR#603.4]"
  , bindRow "Pick" (bindIt loopProbe) "Keep" Nothing "[CR#107.1]"
    -- An SBA body runs in the sweep — never a targeting position ([CR#704]).
  , bindRow "Sba" (\b => b) "Keep" (Just False) "[CR#704]"
  ]

bindTable : String
bindTable =
  header "Binding-context transitions per construct (the Endophora bind-family, applied to a probe)."
  -- (header text kept verbatim — the emitted bytes are pinned; the family now
  -- lives on the v2 antecedent stack)
  ++ "(\n    rows: [\n" ++ concat bindRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- sort compatibility (the anaphor surface's R1 compat table + the R2 gate's
-- one pre-approved loosening flag)
-- --------------------------------------------------------------------------

-- One row: an anaphor's WANTED sort key reaching an antecedent's HAVE sort
-- key. `widened: false` = an exact match (same noun; `OfType`/`OfType`
-- additionally requires the same card type, applied by the consumer);
-- `widened: true` = a widening row (compatible, but not exact — the R2
-- gate's exact-vs-widened distinction). A pair with NO row is incompatible.
-- DERIVED from the v2 `compat` function ([[idris-tables-fixtures-v2]]):
-- rows are the compat-TRUE pairs over one representative `Sort` per key
-- (`OfType` collapses at the key level — the same-card-type refinement is
-- the consumer's), and `widened` is computed as not-same-noun. The one hand
-- input is the per-pair cite (`compatCite`); a compat pair without a cite is
-- a COMPILE error (`compatCitesTotal`), never a silently dropped row. The
-- noun facts the rows carry: tokens aren't cards ([CR#108.2b]); "spell or
-- ability" reaches both stack-object nouns ([CR#405.1]); "that permanent"
-- reaches any battlefield noun ([CR#110.1]); a typed noun reaches exactly
-- its own type ([CR#205.2a]).
compatRow : (want : String) -> (have : String) -> (widened : Bool)
         -> (cite : String) -> String
compatRow want have widened cite =
  "        (want: " ++ quoted want
  ++ ", have: " ++ quoted have
  ++ ", widened: " ++ bool widened
  ++ ", cite: " ++ quoted cite ++ "),\n"

-- the shape key of a sort (OfType collapses — same as the Rust `Sort::key`).
sortKey : Sort -> String
sortKey Player = "Player"
sortKey Card = "Card"
sortKey Token = "Token"
sortKey Spell = "Spell"
sortKey StackObject = "StackObject"
sortKey Permanent = "Permanent"
sortKey (OfType _) = "OfType"
sortKey Amount = "Amount"
sortKey Pile = "Pile"

-- one representative `Sort` per emitted KEY (one per `sortKey` class;
-- `Creature` is the OfType probe — any type works, `compat` only asks
-- same-type).
allSortReps : List Sort
allSortReps =
  [Player, Card, Token, Spell, StackObject, Permanent, OfType Creature, Amount, Pile]

-- each compatible pair's CR home — the per-row cite (the one hand column).
compatCite : Sort -> Sort -> Maybe String
compatCite Player Player = Just "[CR#102.1]"
compatCite Card Card = Just "[CR#108.2]"
compatCite Token Token = Just "[CR#111.1]"
compatCite Spell Spell = Just "[CR#112.1]"
compatCite StackObject Spell = Just "[CR#405.1]"
compatCite StackObject StackObject = Just "[CR#405.1]"
compatCite Permanent Permanent = Just "[CR#110.1]"
compatCite Permanent (OfType _) = Just "[CR#110.1]"
compatCite Permanent Token = Just "[CR#110.1]"
compatCite (OfType _) (OfType _) = Just "[CR#205.2a]"
compatCite Amount Amount = Just "[CR#608.2i]"
compatCite Pile Pile = Just "[CR#700.3]"
compatCite _ _ = Nothing

-- every compat-TRUE pair carries a cite — a `compat` change that opens a new
-- pair without minting its cite breaks the BUILD, not the table.
0 compatCitesTotal :
  all (\w => all (\h => not (compat w h) || isJust (compatCite w h))
             EmitTables.allSortReps)
      EmitTables.allSortReps
  = True
compatCitesTotal = Refl

compatRows : List String
compatRows = concatMap rowsFor allSortReps
  where
    rowFor : Sort -> Sort -> Maybe String
    rowFor w h =
      if compat w h
        then map (compatRow (sortKey w) (sortKey h) (not (sameSort w h)))
                 (compatCite w h)
        else Nothing

    rowsFor : Sort -> List String
    rowsFor w = mapMaybe (rowFor w) allSortReps

compatTable : String
compatTable =
  header "Sort compatibility (R1): which antecedent sorts each anaphor sort reaches; `exact_sort_precedence` is the R2 gate's one pre-approved loosening (calibrated and FROZEN STRICT=off by [[cards-corpus-dry-run]], 2026-07-03: 0 gate fires / 5785 encodable faces, 0 mis-bindings in the 200-face hand audit)."
  ++ "(\n    exact_sort_precedence: false,\n    rows: [\n"
  ++ concat compatRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- zone sorts: what noun an object answers to once it sits in this zone
-- --------------------------------------------------------------------------

zoneSortRow : Zone -> (cite : String) -> String
zoneSortRow z cite =
  "        (zone: " ++ zoneName z
  ++ ", sort: " ++ quoted (sortKey (zoneSort z))
  ++ ", cite: " ++ quoted cite ++ "),\n"

-- Battlefield objects are permanents ([CR#110.1]), stack objects spells
-- ([CR#112.1]), anything else is a card ([CR#108.2]) — this is why "exile
-- target creature … return that card" resolves: the exile clause's product
-- answers to "card". The sort column is COMPUTED from `Core.zoneSort` — the
-- very function the v2 anaphor surface resolves with.
zoneSortRows : List String
zoneSortRows =
  [ zoneSortRow Battlefield "[CR#110.1]"
  , zoneSortRow Stack "[CR#112.1]"
  , zoneSortRow Graveyard "[CR#108.2]"
  , zoneSortRow Hand "[CR#108.2]"
  , zoneSortRow Library "[CR#108.2]"
  , zoneSortRow Exile "[CR#108.2]"
  , zoneSortRow Command "[CR#108.2]"
  ]

zoneSortTable : String
zoneSortTable =
  header "Zone sorts: the noun an object answers to in each zone ([CR#110.1,112.1,108.2])."
  ++ "(\n    rows: [\n" ++ concat zoneSortRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- intro: which clauses push antecedents (site, cardinality, sort, zone)
-- --------------------------------------------------------------------------

-- One row: a producing CLAUSE key; whether it pushes an OBJECT antecedent
-- (site/card/sort/zone rules apply) and/or an AMOUNT antecedent ("that
-- many/much"). Sort rules: a fixed sort name ("Card"/"Token"/"Pile"), or a
-- derivation the walker applies ("from_filter" — the clause's filter,
-- "from_destination" — zone_sort of the destination, "from_binder" — the
-- binder's own content). Zone rules: "none", a fixed zone, or
-- "from_destination" (the [CR#603.7c] expected_zone stamp).
-- DERIVED ([[idris-tables-fixtures-v2]]): each row's columns are read off a
-- Core intro-machinery PROBE (`slotAnte`/`actionIntro`/`refIntro`/
-- `binderAnte`/`bindIt`/`bindAllot`), and every "from_*"/"From*" tag is
-- COMPUTED by a second probe varying exactly that axis — the tag is emitted
-- only when the column actually tracks it, the fixed value otherwise. Hand
-- data is down to the clause-key mapping, the per-row cites, and the two
-- Rust-only shapes flagged inline (Mill, SeparatePiles.pile).
introRow : (clause : String) -> (object : Bool) -> (site : String)
        -> (card : String) -> (sort : String) -> (zone : String)
        -> (amount : Bool) -> (cite : String) -> String
introRow clause object site card sort zone amount cite =
  "        (clause: " ++ quoted clause
  ++ ", object: " ++ bool object
  ++ ", site: " ++ site
  ++ ", card: " ++ card
  ++ ", sort: " ++ quoted sort
  ++ ", zone: " ++ quoted zone
  ++ ", amount: " ++ bool amount
  ++ ", cite: " ++ quoted cite ++ "),\n"

-- the Rust walker's site spelling: the deterministic choice FRAME and the
-- resolution-time choice both land at "Chosen" (walk.rs marks frames with
-- `binder: true` rather than a site of their own).
introSiteName : Site -> String
introSiteName TargetSlot = "TargetSlot"
introSiteName Product = "Product"
introSiteName EventRole = "EventRole"
introSiteName Loop = "Loop"
introSiteName Allot = "Allot"
introSiteName Chosen = "Chosen"
introSiteName Frame = "Chosen"

cardTag : Cardinality -> String
cardTag One = "One"
cardTag Many = "Many"

sameZone : Zone -> Zone -> Bool
sameZone Battlefield Battlefield = True
sameZone Command Command = True
sameZone Exile Exile = True
sameZone Graveyard Graveyard = True
sameZone Hand Hand = True
sameZone Library Library = True
sameZone Sideboard Sideboard = True
sameZone Stack Stack = True
sameZone _ _ = False

sameZoneM : Maybe Zone -> Maybe Zone -> Bool
sameZoneM Nothing Nothing = True
sameZoneM (Just a) (Just b) = sameZone a b
sameZoneM _ _ = False

-- the clause's OBJECT antecedent (the non-Amount push), and its DESCRIPTIVE
-- antecedent — the amount push itself for the bare amount verbs, whose
-- site/card/sort columns describe the "that much" antecedent.
introObjAnte : List Ante -> Maybe Ante
introObjAnte = find (\a => not (sameSort a.sort Amount))

introDescrAnte : List Ante -> Maybe Ante
introDescrAnte as = case introObjAnte as of
  Just a => Just a
  Nothing => find (\a => sameSort a.sort Amount) as

-- the amount COMPANION ("that many/much") — an Amount push at a non-`Allot`
-- site (the `Allot` share is `Count::Allotment`'s, not an intro column).
introHasAmount : List Ante -> Bool
introHasAmount = any (\a => sameSort a.sort Amount && not (isAllotSite a.site))

-- an alternate probe — the SAME intro function at an input varying one axis
-- — plus the tag to emit when the column tracks that axis.
IntroAlt : Type
IntroAlt = Maybe (List Ante, String)

deriveCardCol : Ante -> IntroAlt -> String
deriveCardCol base Nothing = cardTag base.card
deriveCardCol base (Just (alt, tag)) = case introDescrAnte alt of
  Just a => if sameCard base.card a.card then cardTag base.card else tag
  Nothing => cardTag base.card

deriveSortCol : Ante -> IntroAlt -> String
deriveSortCol base Nothing = sortKey base.sort
deriveSortCol base (Just (alt, tag)) = case introDescrAnte alt of
  Just a => if sameSort base.sort a.sort then sortKey base.sort else tag
  Nothing => sortKey base.sort

zoneCol : Maybe Zone -> String
zoneCol Nothing = "none"
zoneCol (Just z) = zoneName z

deriveZoneCol : Ante -> IntroAlt -> String
deriveZoneCol base Nothing = zoneCol base.expectedZone
deriveZoneCol base (Just (alt, tag)) = case introDescrAnte alt of
  Just a => if sameZoneM base.expectedZone a.expectedZone
              then zoneCol base.expectedZone
              else tag
  Nothing => zoneCol base.expectedZone

-- one DERIVED row: columns read off `base` (the probe application), the tag
-- columns computed against the axis-varying alternates.
introRowD : (clause : String) -> (base : List Ante)
         -> (cardAlt : IntroAlt) -> (sortAlt : IntroAlt) -> (zoneAlt : IntroAlt)
         -> (cite : String) -> String
introRowD clause base cardAlt sortAlt zoneAlt cite =
  case introDescrAnte base of
    -- a clause that pushes nothing has no row (unreachable for these keys)
    Nothing => ""
    Just a =>
      introRow clause (isJust (introObjAnte base)) (introSiteName a.site)
               (deriveCardCol a cardAlt) (deriveSortCol a sortAlt)
               (deriveZoneCol a zoneAlt) (introHasAmount base) cite

-- probe filters: two nouns (`OfType Creature` on the battlefield default vs
-- `Card` in hand) so the from_filter probes actually vary the sort.
probeCreature : Predicate Base AnObject
probeCreature = HasChar Types Creature

probeHand : Predicate Base AnObject
probeHand = InZone Hand

probeToken : Characteristics Base
probeToken = ^: { types := [Creature] }

-- the loop element a `Each`/`DivideAmong` body binds — the head of the
-- `bindIt`/`bindAllot` stack over the binder's antecedent (`bindAllot` also
-- pushes the `Allot` share, so its probe keeps two entries).
loopHeadOf : Bindable Base Many AnObject -> List Ante
loopHeadOf dom = take 1 (stack (bindIt (binderAnte dom) Base))

allotHeadOf : Bindable Base Many AnObject -> List Ante
allotHeadOf dom = take 2 (stack (bindAllot (binderAnte dom) Base))

introRows : List String
introRows =
  [ -- announced target slots ([CR#115.3,601.2c]): columns from `slotAnte` —
    -- cardinality tracks the QUANTITY, the noun tracks the FILTER.
    introRowD "Targeted.slot"
      [slotAnte (Target (^1) probeCreature)]
      (Just ([slotAnte (Target (between (^1) (^2)) probeCreature)], "FromQuantity"))
      (Just ([slotAnte (Target (^1) probeHand)], "from_filter"))
      Nothing
      "[CR#115.3,601.2c]"
    -- moved objects: the effect finds what it moved ([CR#400.7j]); the noun
    -- AND the [CR#603.7c] expected zone track the destination (`actionIntro`).
  , introRowD "Move"
      (actionIntro (the (Action Base) (Move This (ToZone Exile))))
      Nothing
      (Just (actionIntro (the (Action Base) (Move This (ToZone Battlefield))), "from_destination"))
      (Just (actionIntro (the (Action Base) (Move This (ToZone Battlefield))), "from_destination"))
      "[CR#400.7j]"
  , introRowD "MoveGroup"
      (actionIntro (the (Action Base) (MoveArranged (SelectAll probeCreature) ChosenOrder (ToZone Exile))))
      Nothing
      (Just (actionIntro (the (Action Base) (MoveArranged (SelectAll probeCreature) ChosenOrder (ToZone Battlefield))), "from_destination"))
      (Just (actionIntro (the (Action Base) (MoveArranged (SelectAll probeCreature) ChosenOrder (ToZone Battlefield))), "from_destination"))
      "[CR#400.7j]"
    -- created tokens enter the battlefield ([CR#111.2]); arity derived from
    -- the count (the fact-signature product-arity column).
  , introRowD "Create"
      (actionIntro (the (Action Base) (CreateToken (^1) probeToken)))
      (Just (actionIntro (the (Action Base) (CreateToken (^2) probeToken)), "FromCount"))
      Nothing Nothing
      "[CR#111.2]"
    -- card-flow verbs push the moved cards AND an amount antecedent.
  , introRowD "Draw"
      (actionIntro (the (Action Base) (Draw (^1))))
      (Just (actionIntro (the (Action Base) (Draw (^2))), "FromCount"))
      Nothing Nothing
      "[CR#121.1]"
  , introRowD "Discard"
      (actionIntro (the (Action Base) (Discard (^1))))
      (Just (actionIntro (the (Action Base) (Discard (^2))), "FromCount"))
      Nothing Nothing
      "[CR#701.9a]"
    -- Mill: the one HAND card-flow row — the Rust player verb has no Idris
    -- `Action` twin (the Idris `mill` is a Composite macro over Move); its
    -- noun/zone are still single-sourced from the model (`zoneSort` of the
    -- entailed `millTo` destination), and count/amount mirror Draw/Discard.
  , introRow "Mill" True "Product" "FromCount"
      (sortKey (zoneSort millTo)) (zoneName millTo) True "[CR#701.17a]"
    -- amount-bearing verbs push "that much" ([CR#608.2i] look-back): the
    -- probe pushes ONLY `amountAnte`, so object=false and the descriptive
    -- columns are the amount antecedent's own.
  , introRowD "DealDamage"
      (actionIntro (the (Action Base) (DealDamage This (^1))))
      Nothing Nothing Nothing
      "[CR#120.1]"
  , introRowD "GainLife"
      (actionIntro (the (Action Base) (GainLife (^1))))
      Nothing Nothing Nothing
      "[CR#119.3]"
  , introRowD "LoseLife"
      (actionIntro (the (Action Base) (LoseLife (^1))))
      Nothing Nothing Nothing
      "[CR#119.3]"
    -- resolution-time choices push Chosen antecedents ([CR#608.2d]): the
    -- indefinite (`refIntro`) and the choice binders (`binderAnte` — the
    -- deterministic Frame spells "Chosen" on the Rust surface).
  , introRowD "A"
      (refIntro (the (Reference Base AnObject) (A probeCreature)))
      Nothing
      (Just (refIntro (the (Reference Base AnObject) (A probeHand)), "from_filter"))
      Nothing
      "[CR#608.2d]"
  , introRowD "With.ChooseOne"
      [binderAnte (the (Bindable Base One AnObject) (ChooseOne probeCreature))]
      Nothing
      (Just ([binderAnte (the (Bindable Base One AnObject) (ChooseOne probeHand))], "from_filter"))
      Nothing
      "[CR#608.2d]"
  , introRowD "With.Choose"
      [binderAnte (the (Bindable Base Many AnObject) (Choose (^2) probeCreature))]
      Nothing
      (Just ([binderAnte (the (Bindable Base Many AnObject) (Choose (^2) probeHand))], "from_filter"))
      Nothing
      "[CR#608.2d]"
  , introRowD "With.TheRef"
      [binderAnte (the (Bindable Base One AnObject) (TheRef This))]
      Nothing
      (Just ([binderAnte (the (Bindable Base One APlayer) (TheRef You))], "from_binder"))
      Nothing
      "[CR#608.2d]"
  , introRowD "With.Existing"
      [binderAnte (the (Bindable Base Many AnObject) (Existing (SelectAll probeCreature)))]
      Nothing
      (Just ([binderAnte (the (Bindable Base Many AnObject) (Existing (TopOfLibrary (^3))))], "from_binder"))
      Nothing
      "[CR#608.2d]"
  , introRowD "With.Produce"
      [binderAnte (the (Bindable Base One AnObject) (Produce (Move This (ToZone Exile))))]
      Nothing
      (Just ([binderAnte (the (Bindable Base One AnObject) (Produce (Move This (ToZone Battlefield))))], "from_binder"))
      Nothing
      "[CR#608.2d]"
    -- searches produce WHIFFABLE products ([CR#701.23,701.23b]); the noun is
    -- fixed `Card` — the from_binder probe AGREES across filters, so the
    -- fixed value is emitted (derivation, not assumption).
  , introRowD "With.SearchOne"
      [binderAnte (the (Bindable Base One AnObject) (SearchOne probeCreature))]
      Nothing
      (Just ([binderAnte (the (Bindable Base One AnObject) (SearchOne probeHand))], "from_binder"))
      Nothing
      "[CR#701.23]"
  , introRowD "With.Search"
      [binderAnte (the (Bindable Base Many AnObject) (Search (^1) probeCreature))]
      Nothing
      (Just ([binderAnte (the (Bindable Base Many AnObject) (Search (^1) probeHand))], "from_binder"))
      Nothing
      "[CR#701.23]"
    -- loop elements ([CR#608.2]); DivideAmong additionally binds Allotment
    -- via its bind-rules row ([CR#601.2d]) — `introHasAmount` excludes the
    -- Allot share by site.
  , introRowD "Each"
      (loopHeadOf (Existing (SelectAll probeCreature)))
      Nothing
      (Just (loopHeadOf (Existing (TopOfLibrary (^3))), "from_binder"))
      Nothing
      "[CR#608.2]"
  , introRowD "DivideAmong"
      (allotHeadOf (Existing (SelectAll probeCreature)))
      Nothing
      (Just (allotHeadOf (Existing (TopOfLibrary (^3))), "from_binder"))
      Nothing
      "[CR#601.2d]"
    -- piles ([CR#700.3]): the chosen pile IS the Idris `PileFrame`; the
    -- labeled per-pile groups are the Rust `SeparatePiles` generalization
    -- (the Idris `DivideAndChoose` is the fixed two-pile form), so their
    -- SITE is the one Rust-shaped column — noun/cardinality read off
    -- `PileFrame`.
  , let pf = PileFrame in
    introRow "SeparatePiles.pile" True "Product"
      (cardTag pf.card) (sortKey pf.sort) "none" False "[CR#700.3]"
  , introRowD "ChoosePile" [PileFrame] Nothing Nothing Nothing "[CR#700.3]"
  ]

introTable : String
introTable =
  header "Intro: which clauses push antecedents onto the stack (site, cardinality, sort, expected zone, amount companion)."
  ++ "(\n    rows: [\n" ++ concat introRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- static-part classes ([CR#611.2c]): fixed vs live affected sets under Until
-- --------------------------------------------------------------------------

classRow : (kind : String) -> (gatherOnce : Bool) -> String
classRow kind gatherOnce =
  "        (kind: " ++ quoted kind
  ++ ", class: " ++ (if gatherOnce then "GatherOnce" else "GatherLive")
  ++ ", cite: " ++ quoted "[CR#611.2c]" ++ "),\n"

-- [CR#611.2c] verbatim: characteristic-/controller-modifying parts fix
-- their set when the effect begins; rules-modifying parts stay live; a
-- mixed effect determines each part independently. (`Static` ability
-- position is always live re-gathering, [CR#611.3a].)
classRows : List String
classRows =
  [ classRow "Modify" True          -- characteristics/controller ([CR#613])
  , classRow "ModifyPlayer" True
  , classRow "Each" True            -- distributes a Modify; same locked-set rule ([CR#613.6])
  , classRow "Conditionally" False  -- re-checked continuously, never locked in ([CR#611.3a])
  , classRow "Deontic" False
  , classRow "CostModifier" False
  , classRow "CostOption" False
  , classRow "TriggerMultiplier" False
  , classRow "Replacement" False
  , classRow "Prevention" False
  , classRow "CantPrevent" False
  , classRow "SpendAsThough" False
  , classRow "Sba" False
  , classRow "OutcomeGate" False
  , classRow "CantHappen" False
  , classRow "PayPips" False
  , classRow "AsThough" False
  ]

classTable : String
classTable =
  header "Static-part classes under Until ([CR#611.2c]): characteristic-/controller-modifying parts gather once at start; rules-modifying parts stay live."
  ++ "(\n    rows: [\n" ++ concat classRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- checker-rule manifest: every error code the elaborator may emit
-- --------------------------------------------------------------------------

-- The TWIN disposition ([[idris-tables-fixtures-v2]] — the fixture-twin CI
-- gate's direction A): `IdrisTwin` = at least one `failing` block in
-- Spec.idr/Experimental.idr twins this code (its `-- @twin` annotation names
-- the reject fixture; the Rust `twin_gate` test cross-checks BOTH
-- directions); `RustOnly why` = the rule deliberately has no Idris twin,
-- with the documented reason riding the row.
data TwinDisposition = IdrisTwin | RustOnly String

twinField : TwinDisposition -> String
twinField IdrisTwin = "Idris"
twinField (RustOnly why) = "RustOnly(" ++ quoted why ++ ")"

ruleRow : (code : String) -> (cite : String) -> (summary : String) -> TwinDisposition -> String
ruleRow code cite summary twin =
  "        (code: " ++ quoted code
  ++ ", cite: " ++ quoted cite
  ++ ", summary: " ++ quoted summary
  ++ ", twin: " ++ twinField twin ++ "),\n"

-- The full code space. `active: false` families are laid out now and turn on
-- in the ticket that mints their grammar nodes (copy-except; macro contracts).
ruleRows : List String
ruleRows =
  [ ruleRow "E-BIND-TARGET" "[CR#115.3,601.2c]" "target slot referenced but not announced in scope" IdrisTwin
  , ruleRow "E-BIND-THAT" "[CR#608.2d]" "sorted singular anaphor That(Sort) with no compatible antecedent in scope" IdrisTwin
  , ruleRow "E-BIND-THAT-GROUP" "[CR#608.2d]" "plural anaphor They/Them(Sort) with no compatible Many antecedent in scope" IdrisTwin
  , ruleRow "E-BIND-IT" "[CR#608.2]" "It with no antecedent: outside every loop binder and with an empty antecedent stack" IdrisTwin
  , ruleRow "E-BIND-ALLOTMENT" "[CR#601.2d]" "Allotment read outside a DivideAmong body" IdrisTwin
  , ruleRow "E-BIND-EVENT" "[CR#603.2e,608.2k]" "event-role reference outside any event body" IdrisTwin
  , ruleRow "E-BIND-NOTE" "[CR#607.2]" "noted key read but never noted in scope"
      (RustOnly "the note channel is Rust-side linked-ability bookkeeping; the Idris model has no note primitive")
  , ruleRow "E-BIND-AMBIGUOUS" "[CR#608.2d]" "ambiguous reference - a second same-kind compatible antecedent exists; add Label/The, or use Target(n)" IdrisTwin
  , ruleRow "E-BIND-LABEL" "[CR#608.2d]" "labeled reference (The/TheGroup/pile label) naming no label in scope" IdrisTwin
  , ruleRow "E-CAPS-OBJECT" "[CR#603.2e,608.2k]" "EventObject read where the event caps supply no object" IdrisTwin
  , ruleRow "E-CAPS-ACTOR" "[CR#603.2e,608.2k]" "EventActor read where the event caps supply no actor" IdrisTwin
  , ruleRow "E-CAPS-PATIENT" "[CR#120.3,608.2k]" "EventPatient read where the event fixes no patient kind" IdrisTwin
  , ruleRow "E-CAPS-DEFENDER" "[CR#506.2,508.5]" "DefendingPlayer read where no combat onset supplies one" IdrisTwin
  , ruleRow "E-CAPS-AMOUNT" "[CR#107.3,608.2i]" "amount anaphor/aggregation without an amount-guaranteeing antecedent" IdrisTwin
  , ruleRow "E-CAPS-ANCHOR" "[CR#603.2]" "event position that must bottom out in master forms doesn't (bare Not / unanchored disjunct)"
      (RustOnly "the Idris EventQuery separates kinds from facets, so an unanchored pattern is unrepresentable by construction; the anchor check exists for the Rust EventFilter algebra")
  , ruleRow "E-CAPS-CONTRADICTION" "[CR#603.2g]" "conjunction over incompatible master forms or against a cause entailment - the pattern can never match"
      (RustOnly "the Idris kinds list is a disjunction - a conjunction of master forms is unrepresentable by construction; the contradiction check is the Rust algebra's")
  , ruleRow "E-LANE-WITHIN" "[CR#603.2]" "Within refinement in a live event lane (vacuous outside history counting)"
      (RustOnly "lane admissibility is per-consumer engine data, deliberately not modeled at the Idris type level")
  , ruleRow "E-LANE-BATCH" "[CR#603.2c]" "OneOrMore/Nth refinement in a lane that forbids it"
      (RustOnly "lane admissibility is per-consumer engine data, deliberately not modeled at the Idris type level")
  , ruleRow "E-BRIDGE-CAP" "[CR#603.2]" "event construct the lane's evaluator cannot faithfully evaluate - a deliberate load cap (missing fact shape, CR-grounded granularity, or a family owned by another subsystem)"
      (RustOnly "bridge support values are engine capability facts (what the one evaluator's fact record carries today), not model content")
  , ruleRow "E-POS-TARGETED" "[CR#115.1a..115.1e,601.2c]" "Targeted outside an announce root (replacement/static/loop position)"
      (RustOnly "may_target positional discipline rides the bind-rules rows as per-row data; the Idris stack deliberately does not carry it")
  , ruleRow "E-POS-RIDER" "[CR#614.12]" "enter rider on a non-battlefield destination"
      (RustOnly "enter riders are Rust grammar nodes with no Idris twin; the destination check is the elaborator's")
  , ruleRow "E-POS-PREVENTION" "[CR#615.1,615.1a]" "damage-prevention written as a generic Instead (a no-op damage replacement) - spell the marked Prevention class"
      (RustOnly "the marked Prevention class is a Rust grammar node; the Idris model spells prevention as ReplaceAmount")
  , ruleRow "E-POS-SIMULTANEOUS" "[CR#701.12]" "exchange-family batch primitive (Simultaneous/GainControl) outside an exchange-family macro body - the engine's batch wiring is exchange-only until it generalizes"
      (RustOnly "the exchange-family batch primitives are Rust grammar nodes; the Idris model has no Simultaneous or one-shot GainControl")
  , ruleRow "E-KIND-FILTER" "[CR#109.1]" "filter kind conflicts with its slot's expected kind" IdrisTwin
  , ruleRow "E-KIND-COUNTER-SCOPE" "[CR#122.1]" "counter kind used on a carrier its scope forbids" IdrisTwin
  , ruleRow "E-KIND-COUNTER-UNDECLARED" "[CR#122.1]" "counter reference names no declared counter kind"
      (RustOnly "counter kinds are grammar-curated (a closed enum) in Idris, so an undeclared kind is unrepresentable; the check guards the Rust open registry")
  , ruleRow "E-KIND-DESIGNATION-SCOPE" "[CR#109.3]" "designation used on a carrier its scope forbids" IdrisTwin
  , ruleRow "E-KIND-NOTE-DOMAIN" "[CR#607.2]" "noted key read with a domain its declared kind doesn't store"
      (RustOnly "the note channel is Rust-side linked-ability bookkeeping; the Idris model has no note primitive")
  , ruleRow "E-KIND-PATIENT-SCOPE" "[CR#508.1b,509.1a,115.4]" "deed patient kind conflicts with its relation's patientScope row"
      (RustOnly "the row VALUES are emitted from the Idris patientScope function, but the Idris Deed keeps its patient kind-poly - the scope check itself is the elaborator's")
  , ruleRow "E-KIND-SUBTYPE-CATEGORY" "[CR#205.3]" "subtype value whose category disagrees with the loaded registry declaration"
      (RustOnly "subtypeCategory is total by construction in Idris; the check guards the Rust open registry's declared categories")
  , ruleRow "E-KIND-KEYWORD-SHAPE" "[CR#702]" "keyword use whose args don't fit the declared ParamShape (a bare parameterized keyword)" IdrisTwin
  , ruleRow "E-FLOOR-TYPES" "[CR#109.3]" "card/token face with no card types" IdrisTwin
  , ruleRow "E-FLOOR-SUBTYPE" "[CR#205.3d]" "subtype whose governing card type is absent from the face" IdrisTwin
  , ruleRow "E-FLOOR-LOYALTY" "[CR#209]" "printed loyalty on a non-Planeswalker face"
      (RustOnly "the Idris face keeps printed loyalty lax (CharacteristicsOk is deliberately the one-type floor); the printed-stat floor is the elaborator's")
  , ruleRow "E-FLOOR-DEFENSE" "[CR#210]" "printed defense on a non-Battle face"
      (RustOnly "the Idris face keeps printed defense lax (CharacteristicsOk is deliberately the one-type floor); the printed-stat floor is the elaborator's")
  , ruleRow "E-FLOOR-TOKEN-TYPES" "[CR#111.1,110.4]" "token spec with non-permanent card types"
      (RustOnly "the Idris CreateToken demands only the one-type floor; the permanent-types token floor is the elaborator's")
  , ruleRow "E-FLOOR-RANGE" "[CR#115.6]" "literal quantity range with inverted bounds" IdrisTwin
  , ruleRow "E-FLOOR-TARGET-QTY" "[CR#115.1]" "target slot whose quantity permits zero targets" IdrisTwin
  , ruleRow "E-FLOOR-BLOCK-QTY" "[CR#509.1]" "block-arrangement bound satisfiable only by zero blockers" IdrisTwin
  , ruleRow "E-FLOOR-MODAL-COUNT" "[CR#700.2d]" "modal choose-count exceeds the number of modes" IdrisTwin
  , ruleRow "E-FLOOR-MODAL-EMPTY" "[CR#700.2]" "modal effect with no modes" IdrisTwin
  , ruleRow "E-FLOOR-DIVIDE" "[CR#601.2d]" "divided amount statically smaller than the minimum group size"
      (RustOnly "the Idris Distribute carries no static divide floor (a senseless split is engine-resolved); the literal floor is the elaborator's")
  , ruleRow "E-FLOOR-PILES" "[CR#700.3]" "pile shape floor: no pile labels, or duplicate pile labels"
      (RustOnly "pile labels are the Rust SeparatePiles generalization; the Idris DivideAndChoose is the fixed two-pile form")
  , ruleRow "E-FLOOR-NTH" "[CR#603.2g]" "Nth occurrence index below one - a 0th occurrence never occurs"
      (RustOnly "the Idris IsNth keeps n=0 a harmless never-matching facet by documented choice; the floor is the elaborator's")
  , ruleRow "E-FLOOR-DESTINATION" "[CR#401.4,405.1]" "bare Library/Stack zone as a Move destination (ordered positions only via Library(Anchor); the stack is never a destination)" IdrisTwin
  , ruleRow "E-FLOOR-DEED-AGENT" "[CR#702.11d,702.16b]" "DeedAgent with neither arm present (the two-armed agent constrains through at least one arm)"
      (RustOnly "the two-armed DeedAgent is a Rust grammar node; the Idris Enact carries a single agent predicate")
  , ruleRow "E-COST-INELIGIBLE" "[CR#118.3]" "cost Do(action) whose verb is not cost-eligible"
      (RustOnly "the Idris Cost.Do is deliberately unrestricted (a senseless cost no-ops); eligibility is the emitted cost-actions closed set, checked by the elaborator")
  , ruleRow "E-COST-X" "[CR#107.3]" "Count::X read where no {X} is declared by the carrying cost"
      (RustOnly "the {X} declaration channel (has_x) is positional discipline the Idris model does not carry")
  ]

rulesTable : String
rulesTable =
  header "Checker-rule manifest: every E-code the elaborator may emit, with its fixture-TWIN disposition (Idris = a Spec/Experimental failing block twins it; RustOnly = documented no-twin reason)."
  ++ "(\n    rows: [\n" ++ concat ruleRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- entry point
-- --------------------------------------------------------------------------

outDir : String
outDir = "../crates/deckmaste_cards/tables/"

resolutionDir : String
resolutionDir = "../crates/deckmaste_cards/tests/resolution/"

emitAt : (path : String) -> String -> IO ()
emitAt path contents = do
  Right () <- writeFile path contents
    | Left err => do
        putStrLn ("emit-tables: failed to write " ++ path ++ ": " ++ show err)
        exitFailure
  putStrLn ("wrote " ++ path)

emit : (file : String) -> String -> IO ()
emit file contents = emitAt (outDir ++ file) contents

-- the per-card resolution-table fixtures (Resolutions.idr) — the Rust
-- `resolution` test replays each card's canon RON twin and demands
-- byte-for-byte agreement on the anaphor rows.
emitResolutions : IO ()
emitResolutions =
  traverse_ (\p => emitAt (resolutionDir ++ fst p ++ ".txt")
                          (renderResolutions (fst p) (snd p)))
            resolutionFixtures

export
emitTables : IO ()
emitTables = do
  emit "event-caps.ron" eventCapsTable
  emit "entailments.ron" entailmentTable
  emit "event-lanes.ron" laneTable
  emit "bridge-caps.ron" bridgeTable
  emit "cost-actions.ron" costActionTable
  emit "scopes.ron" scopesTable
  emit "kind-lattice.ron" latticeTable
  emit "bind-rules.ron" bindTable
  emit "sort-compat.ron" compatTable
  emit "zone-sorts.ron" zoneSortTable
  emit "intro.ron" introTable
  emit "static-classes.ron" classTable
  emit "checker-rules.ron" rulesTable
  emitResolutions

-- `--exec main` convenience: the same entry.
main : IO ()
main = emitTables
