||| The grammar-table emitter: renders `entailments.ron`
||| (`crates/deckmaste_cards/tables/entailments.ron`), the one table the Rust
||| engine still loads independently (`deckmaste_engine::entail`) — not the
||| Rust load-time elaborator, which was deleted along with the twelve other
||| tables this module used to emit (event-caps, bridge-caps, cost-actions,
||| scopes, kind-lattice, bind-rules, sort-compat, zone-sorts, intro,
||| static-classes, checker-rules, event-lanes) and the per-card resolution
||| fixtures (`Resolutions.idr`, also deleted). Anaphora/binding resolution
||| now happens purely at engine eval time
||| (`deckmaste_engine::stack::{Frame,Anaphora}` + `resolve.rs`), so there is
||| no load-time gate left for those tables to feed. Run via
||| `idris/scripts/emit-tables`
||| (`idris2 --find-ipkg --exec emitTables src/EmitTables.idr` from `idris/`).
|||
||| DRIFT CONTROL: every row VALUE is computed by applying `Core.idr`'s total
||| functions (`eventKindCaps`) — never hand-copied. The only hand-written
||| parts are the KEY mapping from the Rust grammar's verb spellings to the
||| Idris kinds and the per-row CR citations. If a Core.idr function changes,
||| the emitted rows change, and the Rust side's regenerate-and-diff turns
||| red.
module EmitTables

import Core
import System
import System.File

%default total

-- --------------------------------------------------------------------------
-- rendering primitives
-- --------------------------------------------------------------------------

bool : Bool -> String
bool True = "true"
bool False = "false"

quoted : String -> String
quoted s = "\"" ++ s ++ "\""

header : String -> String
header what =
  "// GENERATED by idris/src/EmitTables.idr — do not edit by hand.\n"
  ++ "// Regenerate with idris/scripts/emit-tables; CI diffs the output.\n"
  ++ "// " ++ what ++ "\n"

-- --------------------------------------------------------------------------
-- cause-verb entailments ([CR#701] keyword actions): verb → fact form
-- --------------------------------------------------------------------------

zoneName : Zone -> String
zoneName Battlefield = "Battlefield"
zoneName Command = "Command"
zoneName Exile = "Exile"
zoneName Graveyard = "Graveyard"
zoneName Hand = "Hand"
zoneName Library = "Library"
zoneName Sideboard = "Sideboard"
zoneName Stack = "Stack"

optZone : Maybe Zone -> String
optZone Nothing = "None"
optZone (Just z) = "Some(" ++ zoneName z ++ ")"

-- One row: the Rust `CauseVerb` spelling, the entailed master-form KIND (an
-- event-caps key), the zone coordinates the verb fixes, and the caps
-- guarantees a cause-narrowed pattern inherits (object/actor/amount; the
-- verb's own EventKind caps where the model has one, literal for the four
-- verbs outside the EventKind spine — model gaps like the documented holes).
entailRow : (verb : String) -> (kind : String)
         -> (from : Maybe Zone) -> (to : Maybe Zone)
         -> EventCaps -> (cite : String) -> String
entailRow verb kind from to (MkEventCaps o a m _ _) cite =
  "        (verb: " ++ quoted verb
  ++ ", kind: " ++ quoted kind
  ++ ", from: " ++ optZone from
  ++ ", to: " ++ optZone to
  ++ ", object: " ++ bool o
  ++ ", actor: " ++ bool a
  ++ ", amount: " ++ bool m
  ++ ", cite: " ++ quoted cite ++ "),\n"

-- Mill's entailed destination ([CR#701.17a]).
millTo : Zone
millTo = Graveyard

-- The closed `CauseVerb` vocabulary, one CR-cited fact form each: the
-- normal form that makes Dies-matches-sacrifice structural and kills the
-- stringly `Performed` verb table.
entailmentRows : List String
entailmentRows =
  [ entailRow "Sacrifice" "ZoneChange" (Just Battlefield) (Just Graveyard)
      (eventKindCaps Sacrifice) "[CR#701.21a]"
  , entailRow "Destroy" "ZoneChange" (Just Battlefield) (Just Graveyard)
      (eventKindCaps Destroy) "[CR#701.8a]"
  , entailRow "Discard" "ZoneChange" (Just Hand) (Just Graveyard)
      (eventKindCaps Discard) "[CR#701.9a]"
  , entailRow "Exile" "ZoneChange" Nothing (Just Exile)
      (MkEventCaps True False False Nothing False) "[CR#701.13a]"
  , entailRow "Mill" "ZoneChange" (Just Library) (Just millTo)
      (MkEventCaps True True False Nothing False) "[CR#701.17a]"
  , entailRow "Play" "ZoneChange" Nothing (Just Battlefield)
      (eventKindCaps (Begins Play)) "[CR#701.18a]"
    -- fight damage is noncombat damage dealt by the fighting creature
  , entailRow "Fight" "Damage" Nothing Nothing
      (MkEventCaps True False True Nothing False) "[CR#701.14a]"
    -- explore reveals from the library; the card lands in hand or graveyard
  , entailRow "Explore" "ZoneChange" (Just Library) Nothing
      (MkEventCaps True True False Nothing False) "[CR#701.44a]"
    -- an applied regeneration shield's visible fact is the tap
  , entailRow "Regenerate" "StateBecame:Tapped" Nothing Nothing
      (eventKindCaps (Begins Regenerate)) "[CR#701.19a]"
  ]

entailmentTable : String
entailmentTable =
  header "Cause-verb entailments ([CR#701] keyword actions): each CauseVerb's fact form + inherited caps."
  ++ "(\n    rows: [\n" ++ concat entailmentRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- entry point
-- --------------------------------------------------------------------------

outDir : String
outDir = "../crates/deckmaste_cards/tables/"

emitAt : (path : String) -> String -> IO ()
emitAt path contents = do
  Right () <- writeFile path contents
    | Left err => do
        putStrLn ("emit-tables: failed to write " ++ path ++ ": " ++ show err)
        exitFailure
  putStrLn ("wrote " ++ path)

emit : (file : String) -> String -> IO ()
emit file contents = emitAt (outDir ++ file) contents

export
emitTables : IO ()
emitTables = do
  emit "entailments.ron" entailmentTable

-- `--exec main` convenience: the same entry.
main : IO ()
main = emitTables
