||| The grammar-table emitter: renders the checker tables the Rust load-time
||| elaborator (`deckmaste_cards::elaborate`) consumes, as RON data files under
||| `crates/deckmaste_cards/tables/`. Run via `idris/scripts/emit-tables`
||| (`idris2 --find-ipkg --exec emitTables src/EmitTables.idr` from `idris/`).
|||
||| DRIFT CONTROL: every row VALUE is computed by applying `Core.idr`'s total
||| functions (`eventKindCaps`, `actionEventCaps`, `counterScope`,
||| `designationScope`, `agentScope`, the `bind*` Endophora transforms, `\/`)
||| — never hand-copied. The only hand-written parts are (a) the KEY mapping
||| from the Rust grammar's node/verb spellings to the Idris kinds, (b) the
||| per-row CR citations, and (c) the checker-rule manifest (the catalog of
||| error codes, each of which must also have a reject fixture on the Rust
||| side). If a Core.idr function changes, the emitted rows change, and the
||| Rust side's regenerate-and-diff turns red.
|||
||| The two known holes of the current model are deliberately NOT inherited:
|||   * `actionEventCaps`'s `NoCaps` catch-all (Core.idr): the cost-action
|||     table below carries an EXPLICIT row per cost-eligible action — the
|||     verbs the catch-all would swallow (Tap/Untap/LoseLife/RemoveCounters)
|||     get rows computed from the matching `eventKindCaps` kind, and `Reveal`
|||     (no event kind) gets an explicit no-caps row. A verb with no row is
|||     cost-INELIGIBLE to the checker, never silently capless-but-legal.
|||   * `Facet.Patient`'s free kind (Core.idr): every caps row carries the
|||     `patient:` kind the event actually fixes (from `EventCaps.patientKind`)
|||     and the checker gates `EventPatient` reads on it — `None` means the
|||     patient is unreachable, not kind-free.
module EmitTables

import Core
import System
import System.File

-- --------------------------------------------------------------------------
-- rendering primitives
-- --------------------------------------------------------------------------

bool : Bool -> String
bool True = "true"
bool False = "false"

-- The Rust checker's kind names (RefKind, spelled for the table reader).
kindName : RefKind -> String
kindName Empty = "Empty"
kindName AnObject = "Object"
kindName APlayer = "Player"
kindName Anything = "Any"

optKind : Maybe RefKind -> String
optKind Nothing = "None"
optKind (Just k) = "Some(" ++ kindName k ++ ")"

quoted : String -> String
quoted s = "\"" ++ s ++ "\""

header : String -> String
header what =
  "// GENERATED by idris/src/EmitTables.idr — do not edit by hand.\n"
  ++ "// Regenerate with idris/scripts/emit-tables; CI diffs the output.\n"
  ++ "// " ++ what ++ "\n"

-- --------------------------------------------------------------------------
-- event caps ([CR#603.2e,608.2k]): what each event pattern supplies its body
-- --------------------------------------------------------------------------

-- One row: the Rust-side event KEY (the `Event` node shape, or
-- `Performed:<verb>`), the caps VALUE computed via `eventKindCaps`, the cite.
capsRow : (key : String) -> EventCaps -> (cite : String) -> String
capsRow key (MkEventCaps o a m p d) cite =
  "        (key: " ++ quoted key
  ++ ", object: " ++ bool o
  ++ ", actor: " ++ bool a
  ++ ", amount: " ++ bool m
  ++ ", patient: " ++ optKind p
  ++ ", defender: " ++ bool d
  ++ ", cite: " ++ quoted cite ++ "),\n"

-- The key mapping: each Rust `EventFilter` MASTER FORM → the Idris
-- `EventKind` whose `eventKindCaps` value the row carries. A form with no
-- row supplies NOTHING to the checker (safe direction: a body anaphor under
-- an unknown form is rejected). The handful of literal rows (marked) are
-- model gaps like the two documented holes above: forms the Idris EventKind
-- spine doesn't carry yet, given deliberate explicit values.
eventCapsRows : List String
eventCapsRows =
  [ -- object/zone forms
    capsRow "ZoneChange" (eventKindCaps (ZoneChanged Nothing Nothing)) "[CR#603.6]"
    -- the recipient is a kind-poly patient ([CR#120.3] "a player or permanent")
  , capsRow "Damage" (eventKindCaps (DealDamage Nothing {toKind = Just Anything})) "[CR#120.1]"
  , capsRow "LifeGained" (eventKindCaps GainLife) "[CR#119.3]"
  , capsRow "LifeLost" (eventKindCaps LoseLife) "[CR#119.3]"
  , capsRow "Drawn" (eventKindCaps Draw) "[CR#121.1]"
  , capsRow "CounterPlaced" (eventKindCaps PutCounters) "[CR#122.1]"
  , capsRow "CounterRemoved" (eventKindCaps RemoveCounters) "[CR#122.1]"
    -- the onset family ([CR#603.2]) — the relation spine's inchoative aspect
  , capsRow "Cast" (eventKindCaps (Begins Cast)) "[CR#601.2i]"
  , capsRow "Played" (eventKindCaps (Begins Play)) "[CR#701.18a]"
  , capsRow "ActivatedAb" (eventKindCaps (Begins Activate)) "[CR#602.2a]"
  , capsRow "AttackDeclared" (eventKindCaps (Begins Attack)) "[CR#508.1k]"
  , capsRow "BlockDeclared" (eventKindCaps (Begins Block)) "[CR#509.3a,509.3c]"
  , capsRow "Attached" (eventKindCaps (Begins Attach)) "[CR#701.3a]"
  , capsRow "BecomesTarget" (eventKindCaps (Begins Target)) "[CR#601.2c]"
    -- residual status transitions ([CR#603.2e])
  , capsRow "StateBecame:Tapped" (eventKindCaps (Becomes Tapped)) "[CR#603.2e]"
  , capsRow "StateBecame:Untapped" (eventKindCaps (Becomes Untapped)) "[CR#603.2e]"
  , capsRow "StateBecame:Phased" (eventKindCaps (Becomes PhasedOut)) "[CR#702.26b]"
  , capsRow "StateBecame:TurnedFace" (eventKindCaps (Becomes FaceDown)) "[CR#708]"
    -- turn structure / control / designations
  , capsRow "StepBegins" (eventKindCaps (BeginStep (BeginningPhase UpkeepStep))) "[CR#603.2b]"
  , capsRow "ControlChanged" (eventKindCaps GainControl) "[CR#613.1b]"
  , capsRow "DesignationChanged" NoCaps "[CR#109.3]"
  , capsRow "TokenCreated" (eventKindCaps CreateToken) "[CR#701.7]"
  , capsRow "Used" NoCaps "[CR#608.2i]"
    -- literal rows (no EventKind yet): the flipping/rolling player is the
    -- actor; day/night is a game-scope expletive with no participants.
  , capsRow "CoinFlipped" (MkEventCaps False True False Nothing False) "[CR#705.1]"
  , capsRow "DiceRolled" (MkEventCaps False True False Nothing False) "[CR#706.1]"
  , capsRow "BecameDay" NoCaps "[CR#731.1]"
  , capsRow "BecameNight" NoCaps "[CR#731.1]"
  ]

eventCapsTable : String
eventCapsTable =
  header "Event caps: what each event pattern supplies its body's anaphora ([CR#603.2e,608.2k])."
  ++ "(\n    rows: [\n" ++ concat eventCapsRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- cause-verb entailments ([CR#701] keyword actions): verb → fact form
-- --------------------------------------------------------------------------

zoneName : Zone -> String
zoneName Battlefield = "Battlefield"
zoneName Command = "Command"
zoneName Exile = "Exile"
zoneName Graveyard = "Graveyard"
zoneName Hand = "Hand"
zoneName Library = "Library"
zoneName Sideboard = "Sideboard"
zoneName Stack = "Stack"

optZone : Maybe Zone -> String
optZone Nothing = "None"
optZone (Just z) = "Some(" ++ zoneName z ++ ")"

-- One row: the Rust `CauseVerb` spelling, the entailed master-form KIND (an
-- event-caps key), the zone coordinates the verb fixes, and the caps
-- guarantees a cause-narrowed pattern inherits (object/actor/amount; the
-- verb's own EventKind caps where the model has one, literal for the four
-- verbs outside the EventKind spine — model gaps like the documented holes).
entailRow : (verb : String) -> (kind : String)
         -> (from : Maybe Zone) -> (to : Maybe Zone)
         -> EventCaps -> (cite : String) -> String
entailRow verb kind from to (MkEventCaps o a m _ _) cite =
  "        (verb: " ++ quoted verb
  ++ ", kind: " ++ quoted kind
  ++ ", from: " ++ optZone from
  ++ ", to: " ++ optZone to
  ++ ", object: " ++ bool o
  ++ ", actor: " ++ bool a
  ++ ", amount: " ++ bool m
  ++ ", cite: " ++ quoted cite ++ "),\n"

-- The closed `CauseVerb` vocabulary, one CR-cited fact form each: the
-- normal form that makes Dies-matches-sacrifice structural and kills the
-- stringly `Performed` verb table.
entailmentRows : List String
entailmentRows =
  [ entailRow "Sacrifice" "ZoneChange" (Just Battlefield) (Just Graveyard)
      (eventKindCaps Sacrifice) "[CR#701.21a]"
  , entailRow "Destroy" "ZoneChange" (Just Battlefield) (Just Graveyard)
      (eventKindCaps Destroy) "[CR#701.8a]"
  , entailRow "Discard" "ZoneChange" (Just Hand) (Just Graveyard)
      (eventKindCaps Discard) "[CR#701.9a]"
  , entailRow "Exile" "ZoneChange" Nothing (Just Exile)
      (MkEventCaps True False False Nothing False) "[CR#701.13a]"
  , entailRow "Mill" "ZoneChange" (Just Library) (Just Graveyard)
      (MkEventCaps True True False Nothing False) "[CR#701.17a]"
  , entailRow "Play" "ZoneChange" Nothing (Just Battlefield)
      (eventKindCaps (Begins Play)) "[CR#701.18a]"
    -- fight damage is noncombat damage dealt by the fighting creature
  , entailRow "Fight" "Damage" Nothing Nothing
      (MkEventCaps True False True Nothing False) "[CR#701.14a]"
    -- explore reveals from the library; the card lands in hand or graveyard
  , entailRow "Explore" "ZoneChange" (Just Library) Nothing
      (MkEventCaps True True False Nothing False) "[CR#701.44a]"
    -- an applied regeneration shield's visible fact is the tap
  , entailRow "Regenerate" "StateBecame:Tapped" Nothing Nothing
      (eventKindCaps (Begins Regenerate)) "[CR#701.19a]"
  ]

entailmentTable : String
entailmentTable =
  header "Cause-verb entailments ([CR#701] keyword actions): each CauseVerb's fact form + inherited caps."
  ++ "(\n    rows: [\n" ++ concat entailmentRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- event lanes (the plan's §3.2 lane table): per-consumer algebra gates
-- --------------------------------------------------------------------------

-- Which ENGINE MATCHER a lane's patterns run on until the one-evaluator
-- rebase (the `engine-eventfilter-bridge` compile-down): the live trigger
-- matcher (`event_matches`), the replacement would-matcher
-- (`event_pattern_matches` over abstract intents), or the history scan
-- (the live matcher over recorded facts + `History::scan` windows). The
-- bridge-caps table below is keyed per matcher.
data Matcher = Live | Would | History

matcherName : Matcher -> String
matcherName Live = "Live"
matcherName Would = "Would"
matcherName History = "History"

-- One row: the walker's lane key, whether `Within` / `Nth` / `OneOrMore`
-- are admitted, whether every disjunct must be kind-anchored (bottom
-- out in a master form), and the bridge matcher the lane evaluates on.
-- Positional discipline like `bindRows`' caps_from — per-row data, each
-- cited.
laneRow : (lane : String) -> (within : Bool) -> (nth : Bool)
       -> (oneOrMore : Bool) -> (anchored : Bool) -> Matcher
       -> (cite : String) -> String
laneRow lane within nth oneOrMore anchored matcher cite =
  "        (lane: " ++ quoted lane
  ++ ", within: " ++ bool within
  ++ ", nth: " ++ bool nth
  ++ ", one_or_more: " ++ bool oneOrMore
  ++ ", anchored: " ++ bool anchored
  ++ ", matcher: " ++ matcherName matcher
  ++ ", cite: " ++ quoted cite ++ "),\n"

laneRows : List String
laneRows =
  [ -- live lanes: a history window is vacuous against a live fact
    laneRow "Triggered.event" False True True True Live "[CR#603.2]"
  , laneRow "Delayed.event" False True True True Live "[CR#603.7c]"
  , laneRow "Replacement.would" False True True True Would "[CR#614.1]"
  , laneRow "CantHappen" False True True True Would "[CR#614.17c]"
  , laneRow "UntilEvent" False True True True Live "[CR#610.3]"
    -- the multiplier watches another ability's trigger — no ordinals
  , laneRow "TriggerMultiplier.cause" False False True True Live "[CR#603.2d]"
    -- history lanes: the window is the required field; batches don't count
  , laneRow "Happened" True True False False History "[CR#608.2i]"
  ]

laneTable : String
laneTable =
  header "Event lanes: which algebra refinements each consumer position admits ([CR#603.2,608.2i])."
  ++ "(\n    rows: [\n" ++ concat laneRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- bridge caps (`engine-eventfilter-bridge`): per-atom matcher support
-- --------------------------------------------------------------------------

-- One row: an `EventFilter` ATOM (a master-form key, a `Form:field`
-- refinement, an algebra node, or a `Lookback:*` history window) and
-- whether each bridge matcher evaluates it FAITHFULLY today. An atom a
-- lane's matcher does not support is load-REJECTED (`E-BRIDGE-CAP`), never
-- silently mis-matched; the one-evaluator rebase ([[engine-one-evaluator]])
-- lifts the caps by replacing the matchers, not by editing card data.
-- Support values are ENGINE capability facts (which arms exist in
-- `trigger.rs` / `replace_registry.rs` / `history.rs`) — hand-maintained
-- here like the checker-rule manifest, pinned by the engine's
-- bridge-agreement test.
bridgeRow : (atom : String) -> (live : Bool) -> (would : Bool)
         -> (history : Bool) -> (cite : String) -> String
bridgeRow atom live would history cite =
  "        (atom: " ++ quoted atom
  ++ ", live: " ++ bool live
  ++ ", would: " ++ bool would
  ++ ", history: " ++ bool history
  ++ ", cite: " ++ quoted cite ++ "),\n"

bridgeRows : List String
bridgeRows =
  [ -- master forms. The would-matcher lowers only the three intent shapes
    -- the engine emits (`intent_event`): zone moves, damage, life gain.
    bridgeRow "ZoneChange" True True True "[CR#603.6]"
  , bridgeRow "Damage" True True True "[CR#120.1]"
  , bridgeRow "LifeGained" True True True "[CR#119.3]"
  , bridgeRow "LifeLost" True False True "[CR#119.3]"
  , bridgeRow "Drawn" True False True "[CR#121.1]"
  , bridgeRow "CounterPlaced" True False True "[CR#122.1]"
  , bridgeRow "CounterRemoved" True False True "[CR#122.1]"
  , bridgeRow "Cast" True False True "[CR#601.2i]"
  , bridgeRow "Played" True False True "[CR#701.18a]"
  , bridgeRow "ActivatedAb" True False True "[CR#602.2a]"
  , bridgeRow "AttackDeclared" True False True "[CR#508.1k]"
  , bridgeRow "BlockDeclared" True False True "[CR#509.3a]"
  , bridgeRow "Attached" True False True "[CR#701.3a]"
  , bridgeRow "StateBecame:Tapped" True False True "[CR#603.2e]"
  , bridgeRow "StateBecame:Untapped" True False True "[CR#603.2e]"
    -- phasing / turn-face have no fact shapes yet (P0.W6)
  , bridgeRow "StateBecame:Phased" False False False "[CR#702.26b]"
  , bridgeRow "StateBecame:TurnedFace" False False False "[CR#708]"
  , bridgeRow "BecomesTarget" True False True "[CR#601.2c]"
    -- step onsets are read off TurnState, never recorded to history
  , bridgeRow "StepBegins" True False False "[CR#603.2b]"
  , bridgeRow "ControlChanged" True False True "[CR#613.1b]"
  , bridgeRow "DesignationChanged" True False True "[CR#109.3]"
  , bridgeRow "TokenCreated" True False True "[CR#701.7a]"
  , bridgeRow "Used" True False True "[CR#608.2i]"
  , bridgeRow "CoinFlipped" True False True "[CR#705.1]"
  , bridgeRow "DiceRolled" True False True "[CR#706.1]"
  , bridgeRow "BecameDay" True False True "[CR#731.1]"
  , bridgeRow "BecameNight" True False True "[CR#731.1]"
    -- refinement atoms (checked only when the field is present / non-default)
  , bridgeRow "Damage:combat" True True True "[CR#510.1]"
  , bridgeRow "Damage:amount" True False True "[CR#120.1]"
  , bridgeRow "LifeGained:amount" True False True "[CR#119.3]"
  , bridgeRow "LifeLost:amount" True False True "[CR#119.3]"
  , bridgeRow "Drawn:amount" False False False "[CR#121.1]"
  , bridgeRow "CounterPlaced:amount" True False True "[CR#122.1]"
  , bridgeRow "CounterRemoved:amount" True False True "[CR#122.1]"
  , bridgeRow "TokenCreated:what" False False False "[CR#701.7a]"
  , bridgeRow "BecomesTarget:source" False False False "[CR#702.11d,702.16b]"
  , bridgeRow "CoinFlipped:won" False False False "[CR#705.2]"
    -- the would-matcher's lifted cause carries no agent
  , bridgeRow "Cause:agent" True False True "[CR#603.2]"
    -- `Used` resolves object identity through the watcher — only the
    -- self-scoped `of: This` is resolvable outside a frame ([CR#400.7])
  , bridgeRow "Used:of" False False False "[CR#608.2i]"
    -- `Filter::Where` under a snapshot-evaluated participant slot
    -- (`ZoneChange.what` / `Played.what` — the moved object is gone); the
    -- would-matcher evaluates the same slot LIVE (the intent's object)
  , bridgeRow "Where-in-snapshot" False True False "[CR#603.10a]"
    -- algebra nodes
  , bridgeRow "AllOf" True True True "[CR#603.2]"
  , bridgeRow "OneOf" True True True "[CR#603.2c]"
  , bridgeRow "Not" False False False "[CR#603.2]"
  , bridgeRow "Nth" False False False "[CR#603.2g]"
  , bridgeRow "When" False False False "[CR#603.4]"
  , bridgeRow "Within" False False False "[CR#608.2i]"
  , bridgeRow "OneOrMore" True True False "[CR#603.2c]"
    -- history windows (`Happened`/`EventCount`/`EventSum` lookbacks): the
    -- log is turn-tagged; sub-turn markers are unrecorded
  , bridgeRow "Lookback:ThisTurn" False False True "[CR#608.2i]"
  , bridgeRow "Lookback:ThisGame" False False True "[CR#608.2i]"
  , bridgeRow "Lookback:LastTurn" False False True "[CR#608.2i]"
  , bridgeRow "Lookback:ThisCombat" False False False "[CR#506.1]"
  , bridgeRow "Lookback:ThisStep" False False False "[CR#500.1]"
  , bridgeRow "Lookback:SinceYour" False False False "[CR#603.2b]"
  ]

bridgeTable : String
bridgeTable =
  header "Bridge caps (engine-eventfilter-bridge): which EventFilter atoms each engine matcher evaluates faithfully; unsupported atoms are load-rejected (E-BRIDGE-CAP) until the one-evaluator rebase ([CR#603.2])."
  ++ "(\n    rows: [\n" ++ concat bridgeRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- cost actions ([CR#118.3]): eligibility + payment-event caps
-- --------------------------------------------------------------------------

costRow : (action : String) -> EventCaps -> (cite : String) -> String
costRow action (MkEventCaps o a m p d) cite =
  "        (action: " ++ quoted action
  ++ ", object: " ++ bool o
  ++ ", actor: " ++ bool a
  ++ ", amount: " ++ bool m
  ++ ", patient: " ++ optKind p
  ++ ", defender: " ++ bool d
  ++ ", cite: " ++ quoted cite ++ "),\n"

-- Explicit row per cost-eligible player verb ([CR#118.3,601.2b]) — a verb
-- with NO row is not cost-eligible; there is no catch-all. The first three
-- ride `actionEventCaps` (the rows Core.idr defines); the rest are the
-- catch-all's victims, given their true caps via the matching event kind.
costActionRows : List String
costActionRows =
  [ costRow "Sacrifice" (actionEventCaps (the (Action Base) (Sacrifice (SameAs This)))) "[CR#701.21a]"
  , costRow "Discard" (actionEventCaps (the (Action Base) (Discard (Literal 1)))) "[CR#701.9a]"
  , costRow "Move" (actionEventCaps (the (Action Base) (Move This (ToZone Exile)))) "[CR#701.13]"
  , costRow "Tap" (eventKindCaps (Becomes Tapped)) "[CR#701.26a]"
  , costRow "Untap" (eventKindCaps (Becomes Untapped)) "[CR#701.26b]"
  , costRow "LoseLife" (eventKindCaps LoseLife) "[CR#119.3]"
  , costRow "RemoveCounters" (eventKindCaps RemoveCounters) "[CR#122.1]"
    -- Reveal has no event kind in the model; it binds nothing ([CR#701.20a]).
  , costRow "Reveal" NoCaps "[CR#701.20a]"
  ]

costActionTable : String
costActionTable =
  header "Cost-eligible player verbs ([CR#118.3,601.2b]) + the caps their payment event supplies an AdditionalCost body ([CR#601.2f])."
  ++ "(\n    rows: [\n" ++ concat costActionRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- scopes: counter carriers, designation carriers, deed agents
-- --------------------------------------------------------------------------

-- The Rust registry name of each curated counter kind (`CounterRef` idents
-- as the corpus spells them: object counters `<Kind>Counter`, player
-- counters bare).
rustCounterName : CounterKind -> String
rustCounterName Loyalty = "LoyaltyCounter"
rustCounterName Fate = "FateCounter"
rustCounterName Charge = "ChargeCounter"
rustCounterName P1P1 = "P1P1Counter"
rustCounterName M1M1 = "M1M1Counter"
rustCounterName Level = "LevelCounter"
rustCounterName Lore = "LoreCounter"
rustCounterName Stun = "StunCounter"
rustCounterName Shield = "ShieldCounter"
rustCounterName Poison = "Poison"
rustCounterName Energy = "Energy"
rustCounterName Experience = "Experience"

counterCite : CounterKind -> String
counterCite Poison = "[CR#122.1f]"
counterCite _ = "[CR#122.1]"

counterRow : CounterKind -> String
counterRow c =
  "        (name: " ++ quoted (rustCounterName c)
  ++ ", scope: " ++ kindName (counterScope c)
  ++ ", cite: " ++ quoted (counterCite c) ++ "),\n"

allCounterKinds : List CounterKind
allCounterKinds =
  [Loyalty, Fate, Charge, P1P1, M1M1, Level, Lore, Stun, Shield, Poison, Energy, Experience]

designationName : Designation -> String
designationName Monarch = "Monarch"
designationName TheInitiative = "TheInitiative"
designationName CitysBlessing = "CitysBlessing"
designationName Monstrous = "Monstrous"
designationName Goaded = "Goaded"
designationName Renowned = "Renowned"
designationName Suspected = "Suspected"
designationName Saddled = "Saddled"
designationName Solved = "Solved"

-- Per-designation CR homes, each verified against the CR text.
designationCite : Designation -> String
designationCite Monarch = "[CR#725.1]"
designationCite TheInitiative = "[CR#726.1]"
designationCite CitysBlessing = "[CR#702.131c]"
designationCite Monstrous = "[CR#701.37b]"
designationCite Goaded = "[CR#701.15b]"
designationCite Renowned = "[CR#702.112b]"
designationCite Suspected = "[CR#701.60b]"
designationCite Saddled = "[CR#702.171a]"
designationCite Solved = "[CR#719.3b]"

designationRow : Designation -> String
designationRow d =
  "        (name: " ++ quoted (designationName d)
  ++ ", scope: " ++ kindName (designationScope d)
  ++ ", cite: " ++ quoted (designationCite d) ++ "),\n"

allDesignations : List Designation
allDesignations =
  [Monarch, TheInitiative, CitysBlessing, Monstrous, Goaded, Renowned, Suspected, Saddled, Solved]

relationName : Relation -> String
relationName Attack = "Attack"
relationName Block = "Block"
relationName Cast = "Cast"
relationName Activate = "Activate"
relationName Play = "Play"
relationName Attach = "Attach"
relationName Target = "Target"
relationName Counter = "Counter"
relationName Regenerate = "Regenerate"

relationCite : Relation -> String
relationCite Attack = "[CR#508.1a]"
relationCite Block = "[CR#509.1a]"
relationCite Cast = "[CR#601.3]"
relationCite Activate = "[CR#602.1]"
relationCite Play = "[CR#701.18]"
relationCite Attach = "[CR#701.3a]"
relationCite Target = "[CR#115.1]"
relationCite Counter = "[CR#701.6a]"
relationCite Regenerate = "[CR#701.19]"

agentRow : Relation -> String
agentRow r =
  "        (relation: " ++ quoted (relationName r)
  ++ ", scope: " ++ kindName (agentScope r)
  ++ ", cite: " ++ quoted (relationCite r) ++ "),\n"

-- Per-relation PATIENT homes, each verified against the CR text: attack
-- reaches players/planeswalkers/battles, block reaches attackers, attach
-- reaches objects or players, targeting anything targetable; the rest act
-- on objects.
patientCite : Relation -> String
patientCite Attack = "[CR#508.1b]"
patientCite Block = "[CR#509.1a]"
patientCite Cast = "[CR#601.2a]"
patientCite Activate = "[CR#113.3b]"
patientCite Play = "[CR#701.18a]"
patientCite Attach = "[CR#701.3a]"
patientCite Target = "[CR#115.4]"
patientCite Counter = "[CR#701.6a]"
patientCite Regenerate = "[CR#701.19a]"

patientRow : Relation -> String
patientRow r =
  "        (relation: " ++ quoted (relationName r)
  ++ ", scope: " ++ kindName (patientScope r)
  ++ ", cite: " ++ quoted (patientCite r) ++ "),\n"

allRelations : List Relation
allRelations = [Attack, Block, Cast, Activate, Play, Attach, Target, Counter, Regenerate]

scopesTable : String
scopesTable =
  header "Carrier scopes: counter kinds ([CR#122.1]), designations, deed agents (`agentScope`)."
  ++ "(\n"
  ++ "    // `counterScope`'s object default IS model content ([CR#122.1] —\n"
  ++ "    // counters are object-borne unless a player-borne kind says so).\n"
  ++ "    counter_default: Object,\n"
  ++ "    counters: [\n" ++ concatMap counterRow allCounterKinds ++ "    ],\n"
  ++ "    designations: [\n" ++ concatMap designationRow allDesignations ++ "    ],\n"
  ++ "    agents: [\n" ++ concatMap agentRow allRelations ++ "    ],\n"
  ++ "    patients: [\n" ++ concatMap patientRow allRelations ++ "    ],\n"
  ++ ")\n"

-- --------------------------------------------------------------------------
-- kind lattice: the RefKind join ([CR#115.4] — "any target" is the top)
-- --------------------------------------------------------------------------

allKinds : List RefKind
allKinds = [Empty, AnObject, APlayer, Anything]

joinRow : (RefKind, RefKind) -> String
joinRow (a, b) =
  "        (left: " ++ kindName a
  ++ ", right: " ++ kindName b
  ++ ", join: " ++ kindName ((\/) a b) ++ "),\n"

latticeTable : String
latticeTable =
  header "The RefKind join-semilattice (`\\/`): OneOf widens object|player to Any ([CR#115.4])."
  ++ "(\n    joins: [\n"
  ++ concatMap joinRow [(a, b) | a <- allKinds, b <- allKinds]
  ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- bind rules: how each construct transforms the binding context
-- --------------------------------------------------------------------------

-- The probe: an Endophora with EVERYTHING bound, so applying a transform and
-- diffing fields reveals exactly what it drops/keeps.
fullCaps : EventCaps
fullCaps = MkEventCaps True True True (Just AnObject) True

probe : Endophora
probe = MkEndophora [AnObject] (Just (One, AnObject)) (Just AnObject) fullCaps
                    (Just AColor) (Just AnObject) True

cardinalityName : Cardinality -> String
cardinalityName One = "One"
cardinalityName Many = "Many"

optCard : Maybe (Cardinality, RefKind) -> String
optCard Nothing = "None"
optCard (Just (c, _)) = "Some(" ++ cardinalityName c ++ ")"

optBool : Maybe Bool -> String
optBool Nothing = "None"
optBool (Just b) = "Some(" ++ bool b ++ ")"

isJust' : Maybe a -> Bool
isJust' Nothing = False
isJust' (Just _) = True

-- One row, with the drop/keep/bind fields COMPUTED by applying `transform`
-- to the all-bound probe (drops) and reading what it introduces. `caps_from`
-- and `may_target` are positional discipline the Endophora doesn't carry
-- (may_target per [CR#115.1a..115.1e,601.2c]; the ticket's context threading
-- rules), so they are per-row data here.
bindRow : (construct : String) -> (transform : Endophora -> Endophora)
       -> (capsFrom : String) -> (mayTarget : Maybe Bool) -> (cite : String)
       -> String
bindRow construct transform capsFrom mayTarget cite =
  let after = transform probe in
  "        (construct: " ++ quoted construct
  ++ ", drops_targets: " ++ bool (null (targetKinds after))
  ++ ", keeps_that: " ++ bool (isJust' (thatKind after))
  ++ ", binds_targets: " ++ bool (not (null (targetKinds (transform Base))))
  ++ ", binds_that: " ++ optCard (thatKind (transform Base))
  ++ ", binds_it: " ++ bool (isJust' (itKind (transform Base)))
  ++ ", binds_allotment: " ++ bool (hasAllotment (transform Base))
  ++ ", clears_allotment: " ++ bool (not (hasAllotment after))
  ++ ", caps_from: " ++ capsFrom
  ++ ", may_target: " ++ optBool mayTarget
  ++ ", cite: " ++ quoted cite ++ "),\n"

bindRows : List String
bindRows =
  [ bindRow "Targeted" (bindTargets [AnObject]) "Keep" Nothing "[CR#115.1,601.2c]"
  , bindRow "With.One" (bindThat One AnObject) "Keep" Nothing "[CR#608.2d]"
  , bindRow "With.Many" (bindThat Many AnObject) "Keep" Nothing "[CR#608.2d]"
  , bindRow "Each" (bindIt AnObject) "Keep" (Just False) "[CR#608.2]"
  , bindRow "DivideAmong" (bindAllot AnObject) "Keep" (Just False) "[CR#601.2d]"
    -- Delayed: schedule for later — targets are DROPPED, `That` survives
    -- ([CR#603.7c]); the body reads the delayed event's own caps; a delayed
    -- trigger may announce its own targets.
  , bindRow "Delayed" (bindEvent NoCaps . unbindTargets) "Query" (Just True) "[CR#603.7c]"
    -- Reflexive: "when you do" — sees the FULL outer context ([CR#603.12a]).
  , bindRow "Reflexive" (bindEvent NoCaps) "Query" (Just True) "[CR#603.12a]"
  , bindRow "Triggered" (bindEvent NoCaps) "Query" (Just True) "[CR#603.2]"
  , bindRow "Replacement.Instead" (bindEvent NoCaps) "Query" (Just False) "[CR#614.1a]"
  , bindRow "Replacement.Also" (bindEvent NoCaps) "Query" (Just False) "[CR#614.1c]"
  , bindRow "AdditionalCost" (bindEvent NoCaps) "Cost" Nothing "[CR#601.2f]"
    -- Filter::Where / Selection::Pick bind the candidate as `It`.
  , bindRow "Where" (bindIt AnObject) "Keep" Nothing "[CR#603.4]"
  , bindRow "Pick" (bindIt AnObject) "Keep" Nothing "[CR#107.1]"
    -- An SBA body runs in the sweep — never a targeting position ([CR#704]).
  , bindRow "Sba" (\b => b) "Keep" (Just False) "[CR#704]"
  ]

bindTable : String
bindTable =
  header "Binding-context transitions per construct (the Endophora bind-family, applied to a probe)."
  ++ "(\n    rows: [\n" ++ concat bindRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- checker-rule manifest: every error code the elaborator may emit
-- --------------------------------------------------------------------------

ruleRow : (code : String) -> (cite : String) -> (summary : String) -> String
ruleRow code cite summary =
  "        (code: " ++ quoted code
  ++ ", cite: " ++ quoted cite
  ++ ", summary: " ++ quoted summary ++ "),\n"

-- The full code space. `active: false` families are laid out now and turn on
-- in the ticket that mints their grammar nodes (copy-except; macro contracts).
ruleRows : List String
ruleRows =
  [ ruleRow "E-BIND-TARGET" "[CR#115.3,601.2c]" "target slot referenced but not announced in scope"
  , ruleRow "E-BIND-THAT" "[CR#608.2d]" "singular That read outside a one-binder With"
  , ruleRow "E-BIND-THAT-GROUP" "[CR#608.2d]" "group That read outside a many-binder With"
  , ruleRow "E-BIND-IT" "[CR#608.2]" "It read outside an Each/DivideAmong/Where/Pick binder"
  , ruleRow "E-BIND-ALLOTMENT" "[CR#601.2d]" "Allotment read outside a DivideAmong body"
  , ruleRow "E-BIND-EVENT" "[CR#603.2e,608.2k]" "event-role reference outside any event body"
  , ruleRow "E-BIND-NOTE" "[CR#607.2]" "noted key read but never noted in scope"
  , ruleRow "E-CAPS-OBJECT" "[CR#603.2e,608.2k]" "EventObject read where the event caps supply no object"
  , ruleRow "E-CAPS-ACTOR" "[CR#603.2e,608.2k]" "EventActor read where the event caps supply no actor"
  , ruleRow "E-CAPS-PATIENT" "[CR#120.3,608.2k]" "EventPatient read where the event fixes no patient kind"
  , ruleRow "E-CAPS-DEFENDER" "[CR#506.2,508.5]" "DefendingPlayer read where no combat onset supplies one"
  , ruleRow "E-CAPS-AMOUNT" "[CR#107.3,608.2i]" "amount anaphor/aggregation without an amount-guaranteeing antecedent"
  , ruleRow "E-CAPS-ANCHOR" "[CR#603.2]" "event position that must bottom out in master forms doesn't (bare Not / unanchored disjunct)"
  , ruleRow "E-CAPS-CONTRADICTION" "[CR#603.2g]" "conjunction over incompatible master forms or against a cause entailment - the pattern can never match"
  , ruleRow "E-LANE-WITHIN" "[CR#603.2]" "Within refinement in a live event lane (vacuous outside history counting)"
  , ruleRow "E-LANE-BATCH" "[CR#603.2c]" "OneOrMore/Nth refinement in a lane that forbids it"
  , ruleRow "E-BRIDGE-CAP" "[CR#603.2]" "event construct the lane's bridge matcher cannot faithfully evaluate - load-capped until the one-evaluator rebase"
  , ruleRow "E-POS-TARGETED" "[CR#115.1a..115.1e,601.2c]" "Targeted outside an announce root (replacement/static/loop position)"
  , ruleRow "E-POS-RIDER" "[CR#614.12]" "enter rider on a non-battlefield destination"
  , ruleRow "E-POS-PREVENTION" "[CR#615.1,615.1a]" "damage-prevention written as a generic Instead (a no-op damage replacement) - spell the marked Prevention class"
  , ruleRow "E-POS-SIMULTANEOUS" "[CR#701.12]" "exchange-family batch primitive (Simultaneous/GainControl) outside an exchange-family macro body - the engine's batch wiring is exchange-only until it generalizes"
  , ruleRow "E-KIND-FILTER" "[CR#109.1]" "filter kind conflicts with its slot's expected kind"
  , ruleRow "E-KIND-COUNTER-SCOPE" "[CR#122.1]" "counter kind used on a carrier its scope forbids"
  , ruleRow "E-KIND-COUNTER-UNDECLARED" "[CR#122.1]" "counter reference names no declared counter kind"
  , ruleRow "E-KIND-DESIGNATION-SCOPE" "[CR#109.3]" "designation used on a carrier its scope forbids"
  , ruleRow "E-KIND-NOTE-DOMAIN" "[CR#607.2]" "noted key read with a domain its declared kind doesn't store"
  , ruleRow "E-KIND-PATIENT-SCOPE" "[CR#508.1b,509.1a,115.4]" "deed patient kind conflicts with its relation's patientScope row"
  , ruleRow "E-KIND-SUBTYPE-CATEGORY" "[CR#205.3]" "subtype value whose category disagrees with the loaded registry declaration"
  , ruleRow "E-KIND-KEYWORD-SHAPE" "[CR#702]" "keyword use whose args don't fit the declared ParamShape (a bare parameterized keyword)"
  , ruleRow "E-FLOOR-TYPES" "[CR#109.3]" "card/token face with no card types"
  , ruleRow "E-FLOOR-SUBTYPE" "[CR#205.3d]" "subtype whose governing card type is absent from the face"
  , ruleRow "E-FLOOR-LOYALTY" "[CR#209]" "printed loyalty on a non-Planeswalker face"
  , ruleRow "E-FLOOR-DEFENSE" "[CR#210]" "printed defense on a non-Battle face"
  , ruleRow "E-FLOOR-TOKEN-TYPES" "[CR#111.1,110.4]" "token spec with non-permanent card types"
  , ruleRow "E-FLOOR-RANGE" "[CR#115.6]" "literal quantity range with inverted bounds"
  , ruleRow "E-FLOOR-TARGET-QTY" "[CR#115.1]" "target slot whose quantity permits zero targets"
  , ruleRow "E-FLOOR-BLOCK-QTY" "[CR#509.1]" "block-arrangement bound satisfiable only by zero blockers"
  , ruleRow "E-FLOOR-MODAL-COUNT" "[CR#700.2d]" "modal choose-count exceeds the number of modes"
  , ruleRow "E-FLOOR-MODAL-EMPTY" "[CR#700.2]" "modal effect with no modes"
  , ruleRow "E-FLOOR-DIVIDE" "[CR#601.2d]" "divided amount statically smaller than the minimum group size"
  , ruleRow "E-FLOOR-NTH" "[CR#603.2g]" "Nth occurrence index below one - a 0th occurrence never occurs"
  , ruleRow "E-FLOOR-DESTINATION" "[CR#401.4,405.1]" "bare Library/Stack zone as a Move destination (ordered positions only via Library(Anchor); the stack is never a destination)"
  , ruleRow "E-FLOOR-DEED-AGENT" "[CR#702.11d,702.16b]" "DeedAgent with neither arm present (the two-armed agent constrains through at least one arm)"
  , ruleRow "E-COST-INELIGIBLE" "[CR#118.3]" "cost Do(action) whose verb is not cost-eligible"
  , ruleRow "E-COST-X" "[CR#107.3]" "Count::X read where no {X} is declared by the carrying cost"
  ]

rulesTable : String
rulesTable =
  header "Checker-rule manifest: every E-code the elaborator may emit (each twinned to a reject fixture)."
  ++ "(\n    rows: [\n" ++ concat ruleRows ++ "    ],\n)\n"

-- --------------------------------------------------------------------------
-- entry point
-- --------------------------------------------------------------------------

outDir : String
outDir = "../crates/deckmaste_cards/tables/"

emit : (file : String) -> String -> IO ()
emit file contents = do
  Right () <- writeFile (outDir ++ file) contents
    | Left err => do
        putStrLn ("emit-tables: failed to write " ++ file ++ ": " ++ show err)
        exitFailure
  putStrLn ("wrote " ++ outDir ++ file)

export
emitTables : IO ()
emitTables = do
  emit "event-caps.ron" eventCapsTable
  emit "entailments.ron" entailmentTable
  emit "event-lanes.ron" laneTable
  emit "bridge-caps.ron" bridgeTable
  emit "cost-actions.ron" costActionTable
  emit "scopes.ron" scopesTable
  emit "kind-lattice.ron" latticeTable
  emit "bind-rules.ron" bindTable
  emit "checker-rules.ron" rulesTable

-- `--exec main` convenience: the same entry.
main : IO ()
main = emitTables
