[package]
publish = false
name = "deckmaste_english_construction_compiler"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
proc-macro2 = "1.0.106"
quote = "1.0.45"
syn = { version = "2.0.117", features = ["full"] }
deckmaste_english_features = { path = "../deckmaste_english_features" }

[dev-dependencies]
trybuild = "1.0"
prettyplease = "0.2"
serde = { version = "1.0.228", features = ["derive"] }
ron = "0.12.1"
